### ISSUE TITLE
shipit_static_analysis: the same issue has reported 6 times.

### ISSUE THREAD

**Issue by staktrace** [mozilla/release-services#1000]
**MozReview URL:** https://reviewboard.mozilla.org/r/230952/

**Problem:** reviewbot reported the same error 6 times. https://bugzilla.mozilla.org/show_bug.cgi?id=1448490#c3. And then the other error 2 twice. (I was tempted to file a new issue for each one of the redundant error messages...)

**Comment by sylvestre** [comment]
We have a fix for that: https://github.com/mozilla-releng/services/pull/957
should be deployed next week

**Comment by sylvestre** [comment]
Should be fixed now.
