### ISSUE TITLE
Include version in the footer of the docs

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1001]
- All projects in this repository are documented in one place:
- https://docs.mozilla-releng.net/ (staging: https://docs.staging.mozilla-releng.net/, testing: https://docs.testing.mozilla-releng.net/)
- All code/documentation is in ``src/docs`` folder
- [Sphinx](http://www.sphinx-doc.org) is used as a tool to document it.
- Configuration for our Sphinx documentation is located in ``src/docs/conf.py`` this is also the place where you configure version of your documentation
- [This is the place](https://github.com/mozilla/release-services/blob/master/src/docs/conf.py#L66) where we need to set version  

We need to change above mentioned code to:
- first read from `RELEASE_VERSION` variable, prepend `v` and append `(dev)` string to it. and example of a version would be `v51(dev)
- if there is no `RELEASE_VERSION` we should read version from `./src/docs/VERSION` which should be a symlink to `./VERSION`
- the build process will need to be changed also in `./src/docs/default.nix`
- we should then change the template of out theme change footer to be like on https://mozilla-releng.net/

**Comment by championballer** [comment]
Can I work on this?

**Comment by rail** [comment]
You are very welcome to do so! :)

**Comment by championballer** [comment]
I am just starting out here, so please guide me as to how I can go about solving this? What do we mean by revisions here and what is expected exactly?

**Comment by garbas** [comment]
@championballer Hi, I'm going to update shortly the description of the ticket please let me know if it is still unclear.

**Comment by championballer** [comment]
Thanks. I will go through it and try completing this. If I face any issues, I will update them here. :)

**Comment by sangimanishrao** [comment]
Hey, can I work on this, if this has not been assigned to anyone else?

**Comment by garbas** [comment]
@sangimanishrao sure, feel free to take it. it looks like @championballer didn't have time to finish it.

**Comment by sangimanishrao** [comment]
Okay, working on it.

**Comment by theshteves** [comment]
### Hey @garbas, I'd like to get this checked in by Friday
Is there a difference between the docs version & the release version?  Both the `.VERSION` in `src/docs` & `src/releng-frontend` both reflect `1.0.0` which I'm assuming you would like to be synced with the release version?

```shell
find release-services -type f -name '*VERSION*' | xargs cat {}
```
tells me that all `VERSION` files except `src/tooltool/client/VERSION` & `VERSION` are at 1.0.0
so `src/docs/VERSION` does NOT appear to be symlinked to `.VERSION` in today's master branch

**Comment by garbas** [comment]
Hey @theshteves,

sorry I was away last week and couldn't respond. to explain the process of how we should determine version.

1. First we should try to read `RELEASE_VERSION` system variable and if exists we should format it so that we prepend `v` letter and append ` (dev)`. `RELEASE_VERSION` system variable is set in `./please shell` and `./please run` command.

2. If `RELEASE_VERSION` system variable does not exists (during the build) then we fallback to file `src/docs/VERSION` which will always be there (or build will fail). In this case we should only prepend letter `v` in front of the name
