### ISSUE TITLE
shipit_static_analysis: False positive with modernize-use-equals-default

### ISSUE THREAD

**Issue by froydnj** [mozilla/release-services#1006]
**MozReview URL:** https://reviewboard.mozilla.org/r/226034/#review236498

**Problem:** The bot reports that `= default` should be used to define a trivial destructor.  The problem is that the surrounding context makes clear that the destructor is non-trivial.

(It also reports an issue similar to #999, FWIW.)

**Comment by abpostelnicu** [comment]
This has been fixed in the latest versions of clang, starting with 5.0. @La0 told me that we can use the clang-tidy package from taskcluster in nix environment, so we should test it and if it confirms that everything is OK we should go with it.

**Comment by karlt** [comment]
https://reviewboard.mozilla.org/r/235180/#comment307566
https://reviewboard.mozilla.org/r/235180/#comment307568
https://reviewboard.mozilla.org/r/235180/#comment307570

**Comment by marco-c** [comment]
@abpostelnicu did we confirm this is fixed?

**Comment by marco-c** [comment]
Or is this the same as #888?
