### ISSUE TITLE
shipit-uplift: Fix 500s

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1011]
Several 500 errors are triggered on shipit-uplift:

- AttributeError/bugs/<int:bugzilla_id>/patches: 'ProgrammingError' object has no attribute 'description' [backend_common/api.py line 145](https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/3070623/)
- AttributeError/bugs/<int:bugzilla_id>/patches: 'ProgrammingError' object has no attribute 'code' [backend_common/api.py line 144](https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/672044/)
- ProgrammingError/bugs/<int:bugzilla_id>/patches
(psycopg2.ProgrammingError) operator does not exist: character varying = integer[] [shipit_uplift/api.py line 348](https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/672043/)

**Comment by rv404674** [comment]
hi @La0 , i am a newcomer, can i take up this issue. Any suggestions for me. Thanks

**Comment by jarkyll** [comment]
@rv404674 & @La0 Any update on this issue? If possible, could I take this up?

**Comment by La0** [comment]
Uplifts projects are off.
