### ISSUE TITLE
create a check that python project is listed in `nix/setup.cfg`

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1041]
currently there is no way to automatically list all of the projects in `nix/setup.cfg` but what we could do is have a check that ensures project we are running is listed there.

This could be a quick check written in shell [before we run flake8](https://github.com/mozilla-releng/services/blob/master/nix/lib/default.nix#L774).

**Comment by ramkv** [comment]
Hi Can I Work on this issue ? ,I need some guidance though I'm new to the codebase and I don't understand how to get a list of all projects and check them .
