### ISSUE TITLE
Strip out userinfo queries in backend_common/auth0

### ISSUE THREAD

**Issue by srfraser** [mozilla/release-services#1044]
We may want to remove the entire library. So far it's only used by shipit_signoff, which got shelved a while back.

auth0 is moving to OIDC conformant mode, which means the userinfo queries will no longer be supported. To get group information (if we go that route in the future) we'll need to use https://github.com/mozilla-iam/person-api

**Comment by garbas** [comment]
@rail i think shipit-workflow is using auth0.py module from backend_common. you think you could take on this ticket to keep auth0.py lean and clean :)

**Comment by rail** [comment]
I can look at this.

**Comment by rail** [comment]
back to the pool

**Comment by m-agboola** [comment]
Hi, is this issue still open? I'd like to work on it if it is.
