### ISSUE TITLE
Add more metric around mach steps

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1053]

**Comment by rv404674** [comment]
Hi @La0 . Is this issue still open, and if yes, can you explain in more detail, what the issue is. I am a newcome.

**Comment by La0** [comment]
@rv404674 The goal here is to add more Datadog metrics (our monitoring tool) around all the mach commands used in `src/staticanalysis/bot`.

Right now we only have one timer around all of those steps, we would need one per mach call: https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/static_analysis_bot/workflow.py#L155

**Comment by rv404674** [comment]
hey @La0 , i think the PR is completed, do take a look, when you get some time. :)
