### ISSUE TITLE
reduce docker nix closure (currently 1GB)

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1064]
This is a blocker to get `./please tools base-image` command to work again.

### Initial research

Command:

1. ``nix path-info --json -rS `which docker`  | jq 'map(select(.closureSize > 1e6)) | sort_by(.closureSize) | map([.path, .closureSize/1e6])'`` (shows all the dependencies of docker sorted by their closure size)

2. ``nix path-info --json -rs `which docker`  | jq 'map(select(.narSize > 1e6)) | sort_by(.narSize) | map([.path, .narSize/1e6])'``(shows all the dependencies of docker sorted by their output size)

3. ``nix-store -q --tree `which docker` `` (show all the dependencies of docker in a tree like form)

Looking at the output of the above commands it looks that there is one big offender which would solve our problem or at least it would solve the majority of our size problem.

When inspecting the tree graph (command nr. 3) we can see that `go_1_9` package is a dependency which is clearly a mistake since go binaries should not depend on go compiler but should be self contained.

Running the following commands reveals the offender
```
% nix why-depends -f . docker go_1_9                                                                                             ✘ 1 
/nix/store/m8vcm7pqgv1pbyqyiz94ymfdsygbkg60-docker-17.12.1-ce
╚═══libexec/docker/docker-containerd -> /nix/store/8png0k8a86mm2a5xi9d87vj7hchpj5kr-docker-containerd/bin/containerd
    => /nix/store/8png0k8a86mm2a5xi9d87vj7hchpj5kr-docker-containerd
    ╚═══bin/containerd: …cannot close stream 0/nix/store/9i60b3jr255xa66q3cb1psp8rgwdfv4q-go-1.9.4/share/goacBalancerWrap…
        => /nix/store/9i60b3jr255xa66q3cb1psp8rgwdfv4q-go-1.9.4
```

From command nr. 1 and 2 we can see that we will save at least 0.6GB which is the majority.

**Comment by garbas** [comment]
@La0 @rail i thought i would be more verbose what i'm doing with nix and how to see which part of the closure is biggest and how to reduce it.

**Comment by Anton-Latukha** [comment]
Good day.

Go 1.9 was pinned to Docker. That is why Go was not removed from closure.
Solved after https://github.com/NixOS/nixpkgs/pull/41435 merge.
