### ISSUE TITLE
`./please --help` should not show `.please-wrapper`

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1071]
in click you can set program name when creating a command

```
@click.command('please')
```

otherwise it gets it from the file.

**Comment by rv404674** [comment]
hi @garbas can i take up this bug. I am a newcomer, so can you explain it a little more.
Thanks.

**Comment by rv404674** [comment]
hey @garbas , whenver you get time, do explain context a little bit please. Thankyou. :)

**Comment by garbas** [comment]
@rv404674 sorry for late answer.

when you run `./please --help` you can see at the top of the output `.please-wrapper`, that should actually be `./please` and this is what we need to fix.

I attempted to fix this [here](https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/__init__.py#L69) but it looks like it doesn't work.

Maybe it should be `name="./please"` instead of just `"please"`.

Here is [the link to the documentation](https://click.palletsprojects.com/en/7.x/api/#click.group) of `@click.group` decorator.

**Comment by rv404674** [comment]
Thanks @garbas,  I will be sending a patch for this today itself.
