### ISSUE TITLE
Implement a new `Coverage` service which uses the ActiveData ES cluster

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1095]
https://github.com/mozilla-releng/services/blob/407149a850300b42e7fa9fe5ac65616e329bd911/src/shipit_uplift/shipit_uplift/coverage.py#L37

CC @ekyle

**Comment by La0** [comment]
See #1261 for latest fixes to enable this on staging.

**Comment by La0** [comment]
#1310 adds a new endpoint & api version bases only on Active data

**Comment by marco-c** [comment]
We can close this now, as the service is there (even though it is still a WIP).
