### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by emilio** [mozilla/release-services#1106]
**MozReview URL:** https://reviewboard.mozilla.org/r/239302/

**Problem:** Reviewbot claims that the following code:

```cpp
MediaList::MediaList() = default;
```

Would be equivalent to the code I wrote:

```cpp
MediaList::MediaList()
  : mRawList(Servo_MediaList_Create().Consume())
{
}
```

Which is obviously not the case.

**Comment by garbas** [comment]
ping @marco-c @La0 @jankeromnes 

/me just making sure this issue is not lost

**Comment by abpostelnicu** [comment]
I've seen this elsewhere on our bot, strangely this cannot be reproduced locally. using:

`./mach static-analysis check -c=-*,modernize-use-equals-default layout/style/ServoBindings.cpp`

But the truth is I've only tried on MacOS and the bot runs of Linux, I'm gonna test it on Linux also.

**Comment by marco-c** [comment]
Duplicate of #888.
