### ISSUE TITLE
Allow multiple instanceTypes in our provisioners

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1129]
By allowing multiple instanceTypes, we might be able to save money by always using the cheapest option.

We should also probably review the configuration, e.g. I don't know how:
```
  "minPrice": 8,
  "maxPrice": 8,
```
were chosen for `releng-svc-compute`.

Or why:
```
  "minPrice": 4,
  "maxPrice": 4.6,
```
were chosen for `releng-svc`.

**Comment by marco-c** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1455706.

**Comment by garbas** [comment]
@marco-c we need some help from taskcluster team here right?

**Comment by marco-c** [comment]
Likely yes. I have no knowledge about this stuff.

**Comment by marco-c** [comment]
I've performed the change for our provisioners, allowing different kinds of instance types.
