### ISSUE TITLE
Remove '/coverage' from endpoints

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1145]
Now that the coverage endpoints are out of shipit-uplift, it's obvious that they are about coverage.

**Comment by La0** [comment]
This will be done when legacy endpoints are killed, and v2 took over

**Comment by jarkyll** [comment]
@marco-c @La0 Have the legacy endpoints been killed yet?

**Comment by marco-c** [comment]
Not yet, but there is still some work necessary before this can be done.

**Comment by La0** [comment]
We should remove those endpoints when doing #2121

**Comment by marco-c** [comment]
This was done.
