### ISSUE TITLE
shipit_code_coverage_backend: Make endpoint to retrieve raw file coverage also retrieve coverage for a directory

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1160]
This is needed for the file viewer on the frontend.

**Comment by marco-c** [comment]
The API to retrieve file or directory coverage could be a single API that returns either a directory or a file:
Directory
```JSON
{
  "type": "directory",
  "children": [{
      "name": "dom/tools/",
      "type": "directory",
      "coverage": 58.0
  }, {
      "name": "dom/test.cpp",
      "type": "file",
      "coverage": 58.0
  }],
  "coverage": 69.9
}
```

File
```JSON
{
  "type": "file",
  "children": [],
  "coverage": [null, 101010, 30, 40, 50, 60, 0, null]
}
```

**Comment by jankeromnes** [comment]
I'll try to implement this (but feel free to steal this issue if you're faster).

**Comment by marco-c** [comment]
> Should the file coverage result also include per-line covering test files?

For now I'd keep it simple and just return the aggregate result, then we can think about how to improve it 
(we need to think what the frontend should look like, which filters we want to support, etc.). I think showing a list of chunks is not so interesting, but in the future we could add some filtering capabilities to the frontend (e.g. "only show Windows coverage", or "only show web-platform-tests coverage"). And when we have per-test coverage we could show a list of tests covering the file.

**Comment by jankeromnes** [comment]
Un-assigning myself for now. Please feel free to take over this issue.

**Comment by La0** [comment]
Live on staging : https://coverage.staging.moz.tools/v2/path
