### ISSUE TITLE
Review usage of the API from the frontend

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1198]
We can remove some complexity from the backend. There are some parts of the replies that I added at the time for easing debugging, but pretty sure the frontend is not using them for anything important (e.g. the git changeset).

**Comment by marco-c** [comment]
The code-coverage-addon is using:
- coverage/file?changeset=XXX&path=YYY, only the 'data' field is used;
- coverage/changeset_summary/XXX, only the 'commit_added' and 'commit_covered' fields are used.

**Comment by marco-c** [comment]
@jankeromnes could you check what the frontend is using, and what we could remove?

**Comment by La0** [comment]
| Endpoint                                | Function                          | Webextension |  React |
|-----------------------------------------|-----------------------------------|--------------|--------|
| /coverage/file                          | api.coverage_for_file             | Yes (only data)         |        |
| /coverage/changeset/{changeset}         | api.coverage_by_changeset         | Yes (only the 'commit_added' and 'commit_covered')         |        |
| /coverage/changeset_summary/{changeset} | api.coverage_summary_by_changeset |              |        |
| /coverage/supported_extensions          | api.coverage_supported_extensions |              |        |
| /coverage/latest                        | api.coverage_latest               |              |        |
