### ISSUE TITLE
purity likeage in  shipit-static-analysis   

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1200]
Something is causing that we often have to rebuild `shipit-static-analysis`. Quick look didn't reveal anything, but I suspect something is being pulled in via `src` or `src` of its dependencies that is causing often rebuild.

@marco-c @La0 maybe you have some idea what could be the cause, but I think we should look at this soon since it is affecting speed of all of our build.

**Comment by La0** [comment]
We are in the process of removing `gecko-env` and most dependencies from `staticanalysis/bot`, it will only be a pure python tool, and should be pure again.

ETA: 1 to 2 months

**Comment by La0** [comment]
Only 1 month late !

Now the `staticanalysis/bot` is a pure Python tool, and builds in a few minutes on Taskcluster
