### ISSUE TITLE
shipit_static_analysis: Support a stack of revisions

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1215]
We should support stack of revisions too (when the developer manually sets dependencies between them).

**Comment by marco-c** [comment]
Example: https://phabricator.services.mozilla.com/D819 (go to "Stack").

**Comment by marco-c** [comment]
I've asked the Phabricator people, they have several options to improve things for the "multiple patches" case, but on the client side, so it doesn't affect us.
Eventually, on the Phabricator server side, it's still going to be a stack of revisions.

So I think we can start working on this already.

@jankeromnes could you create some test revisions (like the one we already have) and link them manually?

**Comment by marco-c** [comment]
https://phabricator-dev.allizom.org/D679 and https://phabricator-dev.allizom.org/D680

**Comment by jankeromnes** [comment]
> @jankeromnes could you create some test revisions (like the one we already have) and link them manually?

Sure! Linked revisions:

- https://phabricator-dev.allizom.org/D679/
- https://phabricator-dev.allizom.org/D680/

Analysis tasks:

- https://tools.taskcluster.net/groups/Hd3OXQ_PRJaJFlbUqVJgEA/
- https://tools.taskcluster.net/groups/K962Tr2dTHCEARmPRT_j2g/

**Comment by marco-c** [comment]
> https://tools.taskcluster.net/groups/Hd3OXQ_PRJaJFlbUqVJgEA/ (expected to succeed)

It failed too, probably because of #1214.

**Comment by marco-c** [comment]
Actually, it failed because the generated patch failed to apply. I've opened #1440.

**Comment by La0** [comment]
Diff PHIDs: PHID-DIFF-uzcwvmpujxv5fvbz7ey6 & PHID-DIFF-aap7hum7cwxxjvvv6334

**Comment by jankeromnes** [comment]
I've updated https://phabricator-dev.allizom.org/D679 and https://phabricator-dev.allizom.org/D680 using [moz-phab](https://github.com/mozilla-conduit/review), triggering:

- https://tools.taskcluster.net/groups/Hd3OXQ_PRJaJFlbUqVJgEA (failed due to #1440 again)
- https://tools.taskcluster.net/groups/K962Tr2dTHCEARmPRT_j2g (failed because the patch doesn't apply, expected until we support parent revisions correctly)

**Comment by marco-c** [comment]
The two tasks are the same as yesterday, probably tasks were not triggered as we temporarily made the staging bot look at Phabricator prod instead of staging (in order to more easily verify some patches).

**Comment by jankeromnes** [comment]
@marco-c has an interesting theory about these failures:

> 15:35:38 marco> maybe only the first in the stack has the base?
> 15:37:02 marco> bastien: so maybe we have to get the base revision from the first patch in the stack
> 15:37:27 marco> then for the second (third and so on) patches, we checkout to the base of the first, then apply the first

**Comment by La0** [comment]
I reproduced locally both bugs, the diffs posted by @jankeromnes are correctly formatted (base revision on diffs). 
I produced a [WIP PR](https://github.com/mozilla/release-services/pull/1469) to fix the issue on missing base revision when searching for parents diffs. 

So now the task with `PHID-DIFF-5nlbhqr5hhiqrajhjm3j` is also failing on patch apply, which is weird

**Comment by La0** [comment]
With my WIP PR from above, both revisions from @jankeromnes now apply successfully (they did not 2 days ago)
