### ISSUE TITLE
shipit_code_coverage_frontend: Investigate using FuzzManager's coverage front-end

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1217]
They already have a fully-working and nice-looking front-end with per-directory view, filtering, etc (using Vue.js):

https://github.com/MozillaSecurity/FuzzManager/blob/master/server/covmanager/templates/collections/index.html

Since it's all open source, maybe we could somehow extract the Vue components from their Django templates, and re-use it as our own front-end?

**Comment by marco-c** [comment]
They have a few different needs than us, but definitely some of the things we can share (mainly, the file viewer).

**Comment by La0** [comment]
As @choller pointed out during this morning's meeting, the Vue.js code is tightly coupled with the django templates.
To use their (non-)components, we first need to help them extract the [components](https://vuejs.org/v2/guide/components.html) into single file `.vue` files, and compile the application with webpack.

Now that's not a huge load of work, but we have to make a technological decision here: invest in react or Vue.js ... Ping @sylvestre

**Comment by marco-c** [comment]
We're already using React in Armen's frontend, so we'll probably have to keep using it.

**Comment by jankeromnes** [comment]
@La0 thanks for reviewing their code! What amount of work do you think would be required to just quickly rip out the HTML / CSS / JS code from their django templates, and move them into an independent clean Vue repository? (That way they could then start migrating to it.)

Our current front-end has minimalistic React components, with very custom styling (while FuzzManager's front-end seems to re-use the standard TaskCluster style), and it's missing a directory viewer, and syntax highlighting for code files (both shouldn't be extremely hard to implement either).

I also don't know about the performance of each front-end. I feel like we're lacking enough information in order to make a good technical decision (but maybe we want to make a political one).

However, since swapping front-ends would be very involved, I'll continue implementing the missing features in Armen's front-end for now, in order to get a better idea of the remaining work load.

**Comment by La0** [comment]
@jankeromnes Sorry for the late reply, i missed this notification.

The easy part is moving the code in a separate code/folder, but then you would only have standalone components that cannot interact together (because they create one Vue application per Django template, instead of using a single Vue app with multiple components).
So you would then need to refactor the whole codebase into simpler components, linked by a Vue js app, and a VueX store (a bit like redux, but way easier)

I would say it's a 1.5 or 2 weeks effort to have a nice clean state.

**Comment by jankeromnes** [comment]
In today's meeting, we suggested keeping our existing front-end, but porting the look & feel of FuzzManager's front-end over (and maybe that's mostly Bootstrap).

**Comment by marco-c** [comment]
> In today's meeting, we suggested keeping our existing front-end, but porting the look & feel of FuzzManager's front-end over (and maybe that's mostly Bootstrap).

That was basically done with some quick-and-dirty code, now a bit improved and living at https://github.com/mozilla/code-coverage. In the long term, we might consider integrating stuff in Searchfox (to have a centralized place where all source code browsing happens).
