### ISSUE TITLE
new "./please signin" command

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1221]
We need a new command included in `./please`, to setup Taskcluster authentication on a developer computer.

`./please signin` command should the same as `taskcluster signin` does ([here](https://github.com/taskcluster/taskcluster-cli/blob/master/cmds/signin/signin.go)).

The taskcluster credentials should be then stored in `~/.pleaserc`.

**Comment by Hyperion101010** [comment]
La0 i am interested to help here
I am an undergrad student, contributing from few months for Mozilla. :)

**Comment by marco-c** [comment]
This might be a little involved to fix as a first contribution, you might want to look for some of the issues with the `skill:good-first-bug` label.

Unless @garbas can break this down to smaller tasks.

**Comment by Hyperion101010** [comment]
I have solved some good first bugs
would give this a try

**Comment by jee1mr** [comment]
@marco-c Alright. I'll pick up some good first bugs.

**Comment by Hyperion101010** [comment]
So now is this my target ?
To build a new "./please signin" command

**Comment by garbas** [comment]
@Hyperion101010 yes, i reworded it since it wasn't clear before. signin command is already implemented in link mentioned in description. we need to implement it in python as part of the please command.

**Comment by Hyperion101010** [comment]
People let me know which irc shall i contact while working and it'll be helpful if i know at what time UTC you people are available so that i can get some good help .And i'll start working on this issue.

**Comment by marco-c** [comment]
The IRC channel is #release-services.

**Comment by La0** [comment]
I'm working on this.
