### ISSUE TITLE
Add API to retrieve list of changesets with overall coverage

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1226]
This is going to be needed by the frontend in order to build a graph showing the evolution of the coverage.

**Comment by marco-c** [comment]
@vipulchhabra99 this issue is going to require quite a bit of work, it's not suitable as a good first issue.

**Comment by La0** [comment]
That endpoint would be available on `/v2/history`.
By default, a **GET** request on that endpoint will provide the data points for the last year
Each data point will have these attributes:
* changeset
* timestamp
* overall coverage in percent (float)

The endpoint will support 2 query parameters, to customize the date range:
* `start` to specify the minimum timestamp
* `end` to specify the maximum timestamp

During the GCP ingestion of pushes, the backend will need to create new elements in Redis:
1. a `history:<repo>:<changeset>` hash, storing timestamp & overall coverage (could also store more stats in the future)
2. a `history:<repo>` sorted set of changeset, sorted by their timestamp. This will allow us to efficiently query a range of date
