### ISSUE TITLE
shipit-static-analysis: Index Taskcluster tasks

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1230]
The static analysis should setup these [Taskcluster index routes](https://docs.taskcluster.net/docs/reference/core/taskcluster-index/references/api) so we can look them up:

* `project.releng.services.static-analysis.<channel>.<source>.latest` where **source** is either `mozreview` or `phabricator`
* `project.releng.services.static-analysis.<channel>.<source>.<review_id>` where **review_id** is the Mozreview ID or Phabricator Diff ID

**channel** must be in:
 * testing
 * staging
 * production

**Comment by marco-c** [comment]
@La0 this is done, right?

**Comment by marco-c** [comment]
I assume yes.
