### ISSUE TITLE
shipit-static-analysis: Use mzl.la links for bug reports

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1235]
As suggested by @marco-c in #1229, we should use mzl.la links for our bug reports.

**Comment by sylvestre** [comment]
Don't spend too much time on this, github urls aren't long

**Comment by marco-c** [comment]
We switched to a full github URL with 3ee50c9cdd4df8948fb8b59f561a5a75d6227277, and then switched to Bugzilla with b8da320918ab93e8146c7f10dd9096f9c1945b6c.
