### ISSUE TITLE
shipit_static_analysis: Enable `before/after` comparison in production

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1236]
We are currently experimenting with a better heuristic to detect which code defects were caused by a given patch (as opposed to code defects that were already present in the code before the patch).

Currently, our bot uses `IN_PATCH` (i.e. "only report defects that are on lines directly modified by the patch"). While good enough, this heuristic misses new defects that are adjacent in the control graph (e.g. if you modify a function, you might indirectly cause a defect at a call site somewhere else in the code).

Our new approach is called `BEFORE_AFTER`, and runs analysis twice: once before applying the patch, and once more after the patch is applied, in order to detect which defects are actually new.

To enable `BEFORE_AFTER` in production, we should evaluate its results on staging, and verify that they are indeed superior, and also bug free.

TODO:

- [x] 1. Verify that `BEFORE_AFTER` works on staging, without any bugs
- [x] 2. ~~Determine whether `BEFORE_AFTER` is a clear improvement over `IN_PATCH`~~ (we'll likely want to combine both in order to catch more bugs)
- [ ] 3. Enable `BEFORE_AFTER` in production
- [ ] 4. Verify that it also works well in production, and that developers are happy with the results

**Comment by jankeromnes** [comment]
Regarding `1. Verify that BEFORE_AFTER works on staging, without any bugs`, we believe that:

> - [ ] the bot reported 6 extra defects that were *not* in the patch (pre-existing issues, should not be reported):
>   - `modernize-raw-string-literal`
>   - `modernize-use-equals-default` * 5

from https://github.com/mozilla-releng/services/issues/1166#issuecomment-397387354 may be a `BEFORE_AFTER` bug (i.e. these defects are considered "newly introduced by the patch", even though they look like pre-existing defects).

Additionally, running the same analysis on staging but with `IN_PATCH` instead of `BEFORE_AFTER` will reveal further differences between these heuristics. I'll do that soon.

**Comment by jankeromnes** [comment]
Regarding `2. Determine whether BEFORE_AFTER is a clear improvement over IN_PATCH`, I'm worried that `BEFORE_AFTER` will work too well, and that we will miss opportunities for developers to fix pre-existing defects, because it will no longer report pre-existing defects on lines modified by a developer.

E.g. if I refactor a line containing a serious defect, I'm happy if the bot complains about this defect, even though I didn't actually cause it. That way, I can drive-by fix it along with any other nits, and thus improve the Firefox source code.

This is a minor problem, but if the bot stops surfacing these "improvement opportunities", I'm afraid that we'll miss serious defects that could easily be fixed by someone stopping by. Maybe we could somehow combine `IN_PATCH` and `BEFORE_AFTER`?

@sylvestre @La0 any thoughts?

**Comment by sylvestre** [comment]
In general, developers are like "oh, this isn't really my problem or what I am trying to fix now".

In a perfect world, we would be able to separate ride along defects and new defect.

Maybe we would start a discussion on dev-platform about that?

**Comment by jankeromnes** [comment]
New validation run to find before/after bugs:

- 1/2: `PHID-DIFF-sj6o2ldoy3qrly32tf7x` https://tools.taskcluster.net/task-inspector/#EUINu1tdT9eq9cFtBEQbKA
- 2/2: `PHID-DIFF-3reimpzvzlbnn7hhmjrc` https://tools.taskcluster.net/task-inspector/#N6C9GhV-Ty2ZdugKl9Jezw

**Comment by jankeromnes** [comment]
Both failed. Then I deployed `master` to `staging`, and re-uploaded:

- 1/2: `PHID-DIFF-q5imboxwn3nvorgjoisi` https://tools.taskcluster.net/task-inspector/#ZiWfvHJ3S0qxE-h9pBuvBw
- 2/2: `PHID-DIFF-5tgaftrsvnjrezdov5an` https://tools.taskcluster.net/task-inspector/#cDD__u_oTQ-6fYtZV6T0wQ

**Comment by jankeromnes** [comment]
Again:

- 1/2, [PHID-DIFF-3drb6zzj4ezbssrxdluu](https://phabricator-dev.allizom.org/D714), https://tools.taskcluster.net/task-inspector/#fUSW_VRGTJ-Zza0B0PcTZg
- 2/2, [PHID-DIFF-ffrmwh6qhekydjukpozu](https://phabricator-dev.allizom.org/D715), https://tools.taskcluster.net/task-inspector/#K8SWxa5BRESxGSygYkvueg

**Comment by jankeromnes** [comment]
Again:

- 1/2, [PHID-DIFF-3drb6zzj4ezbssrxdluu](https://phabricator-dev.allizom.org/D714), https://tools.taskcluster.net/task-inspector/#fUSW_VRGTJ-Zza0B0PcTZg
- 2/2, [PHID-DIFF-3imcuyzrmmhdpgrr5w6r](https://phabricator-dev.allizom.org/D715), https://tools.taskcluster.net/task-inspector/#GgYHF5ywShWzK28Mej6S2Q

**Comment by jankeromnes** [comment]
Attempted another validation with staging@99a13b60386e801229304e20e77892d65efedae5 deployed... and it failed:


- [QfLd7Z2SQJaireYqMBnPUQ](https://tools.taskcluster.net/groups/QfLd7Z2SQJaireYqMBnPUQ) | 1/2. PHID-DIFF-7c3wyz42vvsz54sghexw | Error: unknown
- [FRJKWSj8TKuLigrMIr_d_A](https://tools.taskcluster.net/groups/QfLd7Z2SQJaireYqMBnPUQ) | 2/2. PHID-DIFF-fq6cdeuk5t5gkd7zi7br | Error: unknown

**Comment by jankeromnes** [comment]
Re-deploying to `staging` with the fix from #1700. Stand by for a new validation upload.

**Comment by jankeromnes** [comment]
One more bug: #1701

**Comment by jankeromnes** [comment]
Pushed the #1701 fix to `staging` and trying again:

- https://tools.taskcluster.net/groups/BlJIUVwxSJ2TE58I16fDog
- https://tools.taskcluster.net/groups/NwWQcUloRQ2P5xek33jRcQ

**Comment by jankeromnes** [comment]
Ok, this last round went through:

1. https://tools.taskcluster.net/groups/Is-U5PvZQ4y35jUEef7Oig/
2. https://tools.taskcluster.net/groups/cx-rHe9xSvahlfGnvIl5_Q/

Let's have a look at the results:

## 1

https://tools.taskcluster.net/groups/Is-U5PvZQ4y35jUEef7Oig/
https://phabricator-dev.allizom.org/D842

Several defects are correctly marked `is_new: true` or `is_new: false`, so there is at least some success, which is good.

The most valuable detections are the new defects that are not in the patch, because with `IN_PATCH` alone they go unreported:
- `devtools/client/menus.js:31 eslint use strict`

This heuristic also recognizes defects that are in the patch but already existed before the patch (I think that these are sufficiently rare that we can still report them, so that they eventually get fixed one day), e.g.:
- `dom/media/CubebUtils.cpp:661 readability-else-after-return`

Problems:

- [ ] random issues in [js/src/jsapi.cpp](https://github.com/jankeromnes/gecko-dev/commit/178dd1b610df766846f3445a62e7d15ace947726#diff-84ee602d6f00e281ca8bf8febc7671c0) are have `is_new: true`, even though they're obviously not caused by the patch:
  - `js/src/jsapi.cpp:115 google-build-using-namespace`
  - `js/src/jsapi.cpp:121 google-global-names-in-headers`
  - `js/src/jsapi.cpp:628 modernize-redundant-void-arg`
  - `js/src/jsapi.cpp:1075 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:1079 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:1085 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:1277 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:1762 modernize-raw-string-literal`
  - `js/src/jsapi.cpp:1797 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:2011 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:2030 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:2193 google-runtime-references`
  - `js/src/jsapi.cpp:3257 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:3319 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:3762 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:3874 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:3984 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:4599 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:5799 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:5956 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:5967 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6323 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6326 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6371 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6374 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6448 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6482 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6515 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6552 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6680 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6768 readability-implicit-bool-conversion`
  - `js/src/jsapi.cpp:6780 readability-implicit-bool-conversion`
  - etc...
- [ ] also some in [dom/media/CubebUtils.cpp](https://github.com/jankeromnes/gecko-dev/commit/178dd1b610df766846f3445a62e7d15ace947726#diff-6d55009e71e52e75188260ce1b329b0f):
  - `dom/media/CubebUtils.cpp:685 readability-implicit-bool-conversion`
  - `dom/media/CubebUtils.cpp:697 readability-implicit-bool-conversion`

## 2

https://tools.taskcluster.net/groups/cx-rHe9xSvahlfGnvIl5_Q/
https://phabricator-dev.allizom.org/D843

Problems:

- TODO

**Comment by marco-c** [comment]
> This heuristic also recognizes defects that are in the patch but already existed before the patch (I think that these are sufficiently rare that we can still report them, so that they eventually get fixed one day)

I think we should try to reduce these cases as much as possible, as the point of the before/after is to only report new issues to avoid nagging developers too much. We can't fix the problem completely as the heuristic is an heuristic, but at least we should make sure the heuristic is not always failing in these cases.

**Comment by jankeromnes** [comment]
> I think we should try to reduce these cases as much as possible, as the point of the before/after is to only report new issues to avoid nagging developers too much.

Actually, my interpretation is that we want before/after because it can find *more* real bugs (e.g. bugs that you caused elsewhere in the code).

Most of the complaints I've heard are that reviewbot *didn't* find a bug, so the developer merged their patch, only to get backed out again because of the bug that slipped through.

I've never heard complaints about reviewbot reporting *too many* issues. There were one or two times were developers got confused, because we report defects that they didn't cause, but that's been pretty rare and a short explanation always resolved it.

But maybe we could improve the wording on pre-existing issues? E.g. something like "Optional: We also found this pre-existing issue that you may be interested in fixing"?

**Comment by marco-c** [comment]
We do want more real bugs, but without showing bugs that are not introduced by the patch. If we just wanted to have more real bugs, the heuristic would be unnecessary, we could just report everything.

> I've never heard complaints about reviewbot reporting too many issues. There were one or two times were developers got confused, because we report defects that they didn't cause, but that's been pretty rare and a short explanation always resolved it.

This is because of the current policy of the bot (IN PATCH), which very rarely reports pre-existing issues, but I bet developers would complain more often if we didn't only show issues in the patch. This is why Facebook implemented this heuristic in Infer (and we took inspiration from theirs).

> But maybe we could improve the wording on pre-existing issues? E.g. something like "Optional: We also found this pre-existing issue that you may be interested in fixing"?

This might be reasonable, but probably as a next step. It is not a blocker for enabling before/after.

**Comment by jankeromnes** [comment]
> [...] but without showing bugs that are not introduced by the patch. If we just wanted to have more real bugs, the heuristic would be unnecessary, we could just report everything.

That's where I disagree. I think that there is value in showing pre-existing defects in the lines that you're currently modifying, but not in showing pre-existing defects in code that you're not touching.

Let's say I'm renaming a variable in a for loop. Maybe I'd like to know that the for loop could use a const ref to be more efficient? (Even though it's someone else's "mistake".) However, I probably don't want to know about the 2000 other defects in the file where the for loop is.

> but I bet developers would complain more often if we didn't only show issues in the patch

That is a reasonable bet. Personally I think that developers wouldn't mind, and would probably even like to know about a few defects that happen to be on the lines they're already editing.

**Comment by marco-c** [comment]
> That's where I disagree. I think that there is value in showing pre-existing defects in the lines that you're currently modifying, but not in showing pre-existing defects in code that you're not touching.

I'm not 100% against this, but at the moment I think it's more valuable to only show `new` issues. I could agree on enabling IN_PATCH + BEFORE_AFTER combination for some specific checkers where the false positive rate is low. Also, what's the difference between lines you're currently modifying and the context of those lines? Why should we show pre-existing issues in lines modified but not in surrounding lines? You could make the same argument here and say "since you're modifying something here, why don't you fix this too?". After all, you are "touching" the loop even if you're just modifying something inside the loop.

> That is a reasonable bet. Personally I think that developers wouldn't mind, and would probably even like to know about a few defects that happen to be on the lines that they're already editing.

The experience at other companies using static analysis is that false positives killed the usefullness of the tools, so we should be careful. If we are too noisy, developers might start to ignore the bot.

**Comment by jankeromnes** [comment]
> but at the moment I think it's more valuable to only show `new` issues

Once BEFORE_AFTER works well enough, there will be a significant overlap between `in_patch` and `is_new`, so most of the time a defect with have both `in_patch && is_new`.

For the few defects where that's not the case:

- I agree that showing `!in_patch && new` defects is good (assuming that it's not a false positive), because it increases our coverage and prevents more bugs from landing into Nightly
- I disagree that we should suddenly start hiding `in_patch && !new` defects, because I believe they're sufficiently rare; fixing them improves Firefox; and showing them until today has never seemed to be a problem

> Also, what's the difference between lines you're currently modifying and the context of those lines? Why should we show pre-existing issues in lines modified but not in surrounding lines? You could make the same argument here and say "since you're modifying something here, why don't you fix this too?". After all, you are "touching" the loop even if you're just modifying something inside the loop.

I feel this is overcomplicating things. We already report `in_patch` defects today, and developer feedback is overwhelmingly positive. We can continue to report them, for free.

However, I don't think it's worth it to implement the reporting of pre-existing defects from wider context, as this sounds like a lot of work and uncertain returns.

> The experience at other companies using static analysis is that false positives killed the usefullness of the tools, so we should be careful. If we are too noisy, developers might start to ignore the bot.

I agree that reporting false positives is really bad for static analysis tools, as this hurts developers' trust in the tool, and increases their incentive to simply ignore or bypass it.

However, I would argue that reporting a few pre-existing defects on lines that you're modifying is not a "false positive", but more like a "prior true positive" (i.e. it's not reporting something bogus that should be ignored, it's reporting an actual, serious defect that was there before and should probably be fixed).

Again, until now, nobody has complained when our bot reports a serious defect even though it already existed before the patch. So I don't see why we should artificially reduce the coverage of our bot. The only complaint I've had with IN_PATCH so far is that it's sometimes missing additional bugs, which we're fixing with the BEFORE_AFTER heuristic.

**Comment by jankeromnes** [comment]
> I disagree that we should suddenly start hiding `in_patch && !new` defects, because I believe they're sufficiently rare; fixing them improves Firefox; and showing them until today has never seemed to be a problem

Actually, `in_patch && !new` defects probably don't even exist (because `in_patch: true` necessarily means that the line was modified, so the before/after heuristic will see a different hash, hence the defect will automatically have `is_new: true`).

So, I conclude that `in_patch` defects are actually a subset of `before_after` defects, and it follows that we don't need to merge both approaches.

Simply `before_after` should be all that's needed to cover all bugs, and if I'm right we'll be able to retire `in_patch`.

**Comment by marco-c** [comment]
Fair enough, if we haven't seen many complaints then I'm OK with keeping reporting in_patch defects (even though sometimes developers don't complain but just silently ignore things :cry:).

Note before_after will not catch all in_patch bugs. For example, in_patch reports pre-existing issues in lines for which you only change indentation, while before_after doesn't as it ignores indentation when hashing.

**Comment by jankeromnes** [comment]
> Fair enough, if we haven't seen many complaints then I'm OK with keeping reporting in_patch defects

Glad that we agree! :) However, now I really do believe that before_after will catch all in_patch bugs:

> Note before_after will not catch all in_patch bugs. For example, in_patch reports pre-existing issues in lines for which you only change indentation, while before_after doesn't as it ignores indentation when hashing.

In my latest test, before_after didn't seem to ignore indentation: [dom/media/CubebUtils.cpp:683](https://github.com/jankeromnes/gecko-dev/commit/505cd30152e69a2c7b228b6a03f66bb9844cfe01#diff-6d55009e71e52e75188260ce1b329b0fR683) is re-indented but otherwise unchanged by the test patch, however the defect `readability-implicit-bool-conversion` has `is_new: true`. (Also, this is totally fine by me, since I advocated for reporting these kinds of issues in the first place.)

**Comment by jankeromnes** [comment]
Additionally, while trying to reproduce #1722 on staging, comment https://github.com/mozilla/release-services/issues/1722#issuecomment-445816010 actually validated `BEFORE_AFTER` with 100% success.

But let's try that again with just `master` and no debug logs:

1. https://tools.taskcluster.net/task-inspector/#FreM4iKrTnOeSrX41SJ2yA
2. https://tools.taskcluster.net/task-inspector/#HFj7gRXQTh6WWv3c-NDKcQ

**Comment by marco-c** [comment]
It might be nice if we had a way to tell "here are the issues you should really fix, and here are the issues you might want to fix". It would be useful for https://github.com/mozilla/release-services/issues/1447 too.

> However, now I really do believe that before_after will catch all in_patch bugs:
> [...]
> In my latest test, before_after didn't seem to ignore indentation

This is a bug because the hash is supposed to remove the leading white lines to ignore indentation:
https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/static_analysis_bot/__init__.py#L65
https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/static_analysis_bot/__init__.py#L77.

If it isn't happening, we should figure out why because there might be a hidden bug.

**Comment by marco-c** [comment]
> If it isn't happening, we should figure out why because there might be a hidden bug.

Ah, it's because that section of the diff is not only changing indentation, it's also modifying a line by adding " }".

The heuristic only ignores pure indentation changes. In that case, in_patch would be true and is_new would be false.

**Comment by jankeromnes** [comment]
So this is extremely strange.

With just `master` deployed to `staging`, Task 1. has 165 occurrences of `"is_new": true` in its [report.json](https://taskcluster-artifacts.net/FreM4iKrTnOeSrX41SJ2yA/0/public/results/report.json)

However, with the following commit applied (adding debug logs):

https://github.com/jankeromnes/services/commit/379f75ba89a3ea9d05ce4c58b13ee4370322aadf

... Task 1. has 37 occurrences of `"is_new": true` its its [report.json](https://taskcluster-artifacts.net/LcptlLJrQMOj-rd1s_9zXA/0/public/results/report.json)

**Comment by jankeromnes** [comment]
I find it pretty strange that in a problematic analysis with many false positives, the [live.log](https://taskcluster-artifacts.net/MQzyOubCT0uebYPSdUMGAA/0/public/logs/live_backing.log) will say:

> static_analysis_bot.workflow: Detected 243 issue(s) before patch
> [...]
> static_analysis_bot.workflow: Detected 278 issue(s) after patch

but still the [report.json](https://taskcluster-artifacts.net/MQzyOubCT0uebYPSdUMGAA/0/public/results/report.json) will have 165 issues with `"is_new": true`. This doesn't add up.

**Comment by jankeromnes** [comment]
All `before/after` fixes have been deployed to `production` and `testing`.

`production` still uses `IN_PATCH` (the default value), while `testing` is configured for silent analysis with `PUBLICATION: BEFORE_AFTER`. This will allow comparing analysis results as new analyses come in.

Here is a validation run with my [bad patches]():

## production

1. https://tools.taskcluster.net/task-inspector/#LDNW2NGmQvSYYM9HRw8zFQ
2. https://tools.taskcluster.net/task-inspector/#LrrIErK1S_ydq3L7nYzNMQ

## testing

1. https://tools.taskcluster.net/task-inspector/#UdudK5PbSaW-MHhM19GYew
2. https://tools.taskcluster.net/task-inspector/#WDhc4qweQ265x-o1WLtyhw

**Comment by La0** [comment]
Before/after was enabled for a few weeks, worked nicely.

Now that we switched to Try tasks, it needs to be implemented in tree.
