### ISSUE TITLE
shipit-static-analysis: Integration tests

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1255]
Those integration tests would be useful to implement:

- [ ] Taskcluster static analysis artifact download
- [ ] `clang-tidy` output on a known file (especially headers/footers)
- [ ] `clang-format` output on a known file
- [ ] `./mach lint output` on a known file
- [ ] `./mach static-analysis check` output on a known file
- [ ] Analysis on known files, expecting a specific set of issues
- [ ] Mercurial clone

**Comment by abpostelnicu** [comment]
We already have 1 and 2 implemented but on taskcluster as the task Sa.
It can be ran locally as:

./mach static-analysis autotest

It does the following:
1. Download clang-tidy from the artifacts server.
2. Tests all of the enabled checkers with pre-defined test files. Please see: https://dxr.mozilla.org/mozilla-central/source/tools/clang-tidy/test

If I can be of any help on this topic please let me know.

**Comment by La0** [comment]
Outdated.
