### ISSUE TITLE
shipit_static_analysis: Phabricator reporter should be able to filter analyzers

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1264]
In our bot's configuration on Taskcluster, we have two `ANALYZERS` keys:
- One global, that enables analyzers (i.e. `clang-tidy`, `clang-format` and `mozlint`) for every reporter (i.e. `email`, `mozreview`, `phabricator`)
- One specific to the MozReview reporter, in order to filter out analyzers that aren't ready yet (i.e. `clang-format`) from published reviews

The Phabricator reporter doesn't have such a filter though. So, in order to enable Phabricator reviews in production (issue #1166), I've had to globally disable the `clang-format` analyzer (so it's removed from everywhere, even debug email reports, which is not ideal).

We should:

- [ ] implement an analyzer filter for the Phabricator reporter
- [ ] use it to filter out `clang-format` from reviews until it's ready
- [ ] re-enable `clang-format` globally / in debug email reports

**Comment by jankeromnes** [comment]
For the analyzer filter in the `PhabricatorReporter`, we could do something similar to what the (now removed) `MozReviewReporter` did:

https://github.com/mozilla/release-services/blob/548d354c297908c65e48182a195b2952d84f1f84/src/staticanalysis/bot/static_analysis_bot/report/mozreview.py#L52-L60

However, I'm not sure if we should set `self.analyzers` in `__init__`:

https://github.com/mozilla/release-services/blob/b61159dccf7a24e54715df180aecb92b21d4156f/src/staticanalysis/bot/static_analysis_bot/report/phabricator.py#L22-L24

or just below in `setup_api`:

https://github.com/mozilla/release-services/blob/b61159dccf7a24e54715df180aecb92b21d4156f/src/staticanalysis/bot/static_analysis_bot/report/phabricator.py#L26-L29

or if we should implement a new `setup_analyzers` method.

@La0 you mentioned that we had two ways of setting up `self.api` in `PhabricatorReporter` because of tests. Should we also implement two ways to set up `self.analyzers`? Which ones?

**Comment by La0** [comment]
Done in #1626
