### ISSUE TITLE
shipit_bot_uplift: Automate Firefox patch uplifts

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1270]
Every now and then, a Firefox patch needs to be uplifted (i.e. backported) from the development branch ([mozilla-central](https://hg.mozilla.org/mozilla-central/)) to a more stable branch (e.g. [mozilla-beta](https://hg.mozilla.org/releases/mozilla-beta/) or [mozilla-esr60](https://hg.mozilla.org/releases/mozilla-esr60/)), bypassing the normal release cycle.

This requires a special [approval process](https://wiki.mozilla.org/Release_Management/Uplift_rules), and incurs repeated manual work from the [Release Management](https://wiki.mozilla.org/Release_Management) team, with the risk of accidentally introducing new bugs to existing Firefox releases.

The uplift process is ripe for automation, and there are several opportunities for us to save time; move faster; and reduce the risk of introducing new bugs to Firefox releases.

TODO:
- [ ] react to new uplift requests, and run some basic sanity checks on the patch
  - [ ] if it doesn't apply cleanly, clear the uplift request, and needinfo the patch author (so that they can rebase the patch)
  - [ ] if possible, properly handle patch dependencies (e.g. apply batches of 7-8 patches, ordered by "last resolved" to preserve landing order)
  - [ ] investigate automatically sending a Try push in order to further complement the sanity checks (to use Try resources responsibly, we could use `./mach try coverage` when it's ready)
- [ ] react to uplift approvals (granted by relman), and automatically apply the patch to the targeted release branch (e.g. via Phabricator and Lando)
  - [ ] check bugzilla report of approved uplift + not fixed on target branch
  - [ ] graft mozilla-central changeset onto target branch (batch of 7-8 patches, order by "last resolved")
  - [ ] edit the commit message with "a=approver" (relman) 
  - [ ] ... but defer the actual merging to a Human operator (e.g. a release manager clicking on Lando's "merge" button)
- [ ] finally, when we've gained sufficient confidence in our uplift bot, automatically trigger the final merge step as well
  - [ ] also auto-fix bugzilla tracking flags using bugherder

**Comment by sylvestre** [comment]
@rvandermeulen is that ok with you?

**Comment by rvandermeulen** [comment]
Yes, I think this encapsulates things well.

**Comment by jankeromnes** [comment]
The upliftbot code now lives under [/src/uplift/bot/](https://github.com/mozilla/release-services/blob/master/src/uplift/bot/).

Every 60 minutes, the bot fetches all the bugs with an uplift approval-request flag (set to `?`):

https://github.com/mozilla/release-services/blob/4786e978be95930eb7dc59f7560f550f5ff0783a/src/uplift/bot/uplift_bot/sync.py#L353-L364

... and iterates over every patch (grouped by branch), trying to merge them like so:

https://github.com/mozilla/release-services/blob/4786e978be95930eb7dc59f7560f550f5ff0783a/src/uplift/bot/uplift_bot/mercurial.py#L90-L121

(Note: `is_mergeable` should probably be renamed to `merge` because it actually merges the patch.)

When a merge fails, I believe it's simply reported to the uplift backend (along with other analysis results and bug data).

Instead, when a merge fails, we should make the bot clear the uplift request in Bugzilla, and needinfo the patch author with a comment indicating that the patch didn't apply cleanly.

**Comment by jankeromnes** [comment]
> Instead,  when a merge fails, we should make the bot clear the uplift request in  Bugzilla, and needinfo the patch author with a comment indicating that  the patch didn't apply cleanly.

To implement this new behavior, we could tweak upliftbot's main workflow.

Here is where all the merge tests are run, and the email report is sent:

https://github.com/mozilla/release-services/blob/32728edef0969a1d7278f56dd9bf3694ae008250/src/uplift/bot/uplift_bot/sync.py#L362-L367

We could implement a new upliftbot module (or methods) that knows how to clear an uplift-request and post a comment with needinfo to Bugzilla, and then send it the failed `merge_tests`, either before or after the email report is sent.

**Comment by jankeromnes** [comment]
With @calixteman's help, we were able to use `libmozdata` to remove an approval flag; post a comment; and set a needinfo in https://bugzilla-dev.allizom.org/show_bug.cgi?id=1395057

It looks like we'll have to do it in two separate requests:

- either `clear request` then `comment + needinfo` as shown below,
- or `clear request + comment` then `needinfo`.

```python
# Clear a given `flag` from a given `attachment`:
data = {
    'flags': [
        {
            'name': flag['name'],
            'status': 'X'
        },
    ],
}
Bugzilla([str(attachment['id'])]).put(data, attachment=True)

# Post a comment to explain why we clear the flag, and set needinfo on the uplift requester:
data = {
    'comment': { 'body': 'Sorry, request denied because of reasons. Please try again!' },
    'flags': [
         {
             'name': 'needinfo',
             'requestee': flag['setter'],
             'status': '?',
             'new': 'true'
         },
    ],
}
Bugzilla(bugids=['1395057']).put(data)
```

**Comment by jankeromnes** [comment]
Note: The uplift cancellation code is currently being implemented in #1466.

**Comment by jankeromnes** [comment]
Since we don't yet supported rebased patches in attachments, we should probably start by only posting a comment in the bug (without needinfo, and without cancelling the uplift request), just explaining that Uplift Bot failed to cherry-pick the patch from mozilla-central.

We could also add a special whiteboard tag (or keyword), to indicate whether Uplift Bot succeeded or failed to cherry-pick the patch.

**Comment by La0** [comment]
Uplifts projects are off.
