### ISSUE TITLE
Investigate why an issue wasn't published

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#1274]
The dashboard says that it found and published a clang analyzer issue:
![image](https://user-images.githubusercontent.com/733326/42865460-fc062ffe-8a69-11e8-8a5e-158f4f0da8a2.png)

It points to:
https://nextcairn.com/mozilla-sa/#/check/clang-tidy.clang-analyzer-deadcode.DeadStores
Which links to
https://reviewboard.mozilla.org/r/256212/ (see also https://bugzilla.mozilla.org/show_bug.cgi?id=1447945)
which doesn't show any activity from the bot.

**Comment by La0** [comment]
This issue is the only difference between staging|testing vs. production (if we ignore clang-format).

9 other clang-tidy issues were found everywhere (modernize-use-auto & modernize-use-equals-default)

**Comment by La0** [comment]
Production [TC task](https://tools.taskcluster.net/groups/JlKLtGVrSZ-_P1X08TcCyQ/tasks/JlKLtGVrSZ-_P1X08TcCyQ/details) ran fine, simply did not identify it.

**Comment by La0** [comment]
Created a [new production task](https://tools.taskcluster.net/groups/QshSNFQRSD69E36rfC594g/tasks/QshSNFQRSD69E36rfC594g/details) as the initial one may not have the latest updates and misses some clang-tidy checks
