### ISSUE TITLE
Disable or update shipit-bot-uplift

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1275]
Until its version of libmozdata gets updated, it's spamming hg.mozilla.org

I just removed the hooks definition on TC

**Comment by garbas** [comment]
@La0 was new version of libmozdata released recently? i suppose i have to run update again on projects in #1267

**Comment by La0** [comment]
@garbas not yet, @calixteman is working on it.
I'll make the updates on the projects using a separate PR

**Comment by calixteman** [comment]
I released a new version (0.1.40) of libmozdata with the fix for hgmo.

**Comment by garbas** [comment]
@La0 I had to rerun update dependencies in #1278 which picked up libmozdata 0.1.40. I assume that PR will also fix this issue.

**Comment by La0** [comment]
I deleted again the production hook, re-created after the last release.

@garbas Thanks for your PR, i'm testing #1278 today, it should indeed fix this

**Comment by La0** [comment]
I confirm that libmozdata 0.1.40 is now shipped on master, hence on staging/testing.

Will be enabled on production during next release.
