### ISSUE TITLE
cli_common: Map from Phabricator's differential IDs to a base revision on mozilla-central

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1277]
All Conduit endpoints require an API key, [even the read-only ones](https://discourse.phabricator-community.org/t/getting-ssh-public-keys-from-phab/1636).

Implementing this requires setting up a Phabricator API key configuration, then querying `https://phabricator.services.mozilla.com/api/differential.querydiffs` as described in [this bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1366401#c6). Maybe use the [lando-api library](https://github.com/mozilla-conduit/lando-api/blob/9d1dffa7f908b4efdc0e04850629a6bb97645e74/landoapi/phabricator.py#L300).

This is needed by https://github.com/mozilla/code-coverage-addon/issues/6, to add support for viewing code coverage in Phabricator. This will also be needed by static analysis, for the same reasons.

**Comment by marco-c** [comment]
Maybe there's another solution we don't know about, @smacleod?

**Comment by smacleod** [comment]
Authenticated access is really the only option. That being said, a service could be built to do these lookups on the users behalf and expose the base commit to unauthenticated users.

I would recommend against using the deprecated `differential.querydiffs` conduit method. Instead `differential.diff.search` should be used, with its `commits` attachment. You might want to use a more recent version of lando-api's Phabricator client than the one linked as well.

**Comment by marco-c** [comment]
> Authenticated access is really the only option. That being said, a service could be built to do these lookups on the users behalf and expose the base commit to unauthenticated users.

OK, this is what we're going to do then.

So, https://github.com/mozilla/code-coverage-addon/issues/6 will depend on this to be solved first.
