### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: XXX

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1297]
Both static analysis and code coverage tasks are failing with this message.

**Comment by La0** [comment]
Random [SA task failing on staging](https://tools.taskcluster.net/groups/IlYClSFPQVqmt3uQcbkQNA/tasks/IlYClSFPQVqmt3uQcbkQNA/runs/0/logs/public%2Flogs%2Flive.log)

**Comment by marco-c** [comment]
https://tools.taskcluster.net/groups/XRfGqQExTjiZlb0nXST0UQ/tasks/XRfGqQExTjiZlb0nXST0UQ/runs/0/logs/public%2Flogs%2Flive.log

**Comment by La0** [comment]
This is most certainly due to [using app as default user](https://github.com/mozilla/release-services/blob/master/nix/lib/default.nix#L713) in the docker image, introduced in the [Dockerflow PR](https://github.com/mozilla/release-services/pull/1183)

**Comment by La0** [comment]
Should be fixed by the revert from #1301

**Comment by marco-c** [comment]
I've verified code coverage is fixed and @La0 verified static analysis.

**Comment by sylvestre** [comment]
Can we retrigger the SA jobs?

**Comment by La0** [comment]
This is only on staging, no need :smile:
