### ISSUE TITLE
Evaluate running our code analysis on Try

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1298]
When we started `reviewbot`, we had a choice between (1) using a Try taskgraph for our code analysis, or (2) to re-implement our own analysis inside a simple unique Taskcluster/Services task. We opted for (2), because it was simpler and faster to implement (enforcing review-time defect coverage as fast as possible), and it wasn't clear what additional work was required, or how long a Try-based solution would take to complete analysis.

@marco-c proposed that it's time to re-evaluate using a Try-based solution.

To do so, I suggest that we:

- [ ] compare the analysis types we run, and look for Try equivalents (create them if they don't exist)
  - [x] `mozlint` = `ES` (eslint/js) + `f8` (flake8/python) + `spell` (codespell)
    - there is also `mozlint-cpp-virtual-final`, `mozlint-mingw-cap`, `mozlint-py-compat`
    - there are currently no artifacts for these tasks other than the logs
  - [x] clang-tidy (Mozilla-specific analyzers) ~= for now, there is only the build-time analysis with `clang-plugin` (jobs `linux64-st-an`, `win32-st-an`, `win64-st-an`)
    - but maybe we don't want to wait for a full build in our analysis?
    - there are currently no artifacts for these tasks other than the logs
  - [ ] clang-tidy (upstream checkers) = https://bugzilla.mozilla.org/show_bug.cgi?id=1478600
- [x] send a commit with defects to Try, and trigger the above jobs, in order to evaluate how we can extract review comments from them
- [ ] prototype extracting and publishing review comments from the above Try job results
- [ ] measure end-to-end times from review request to publishable comments, and compare them to current `reviewbot` times

**Comment by jankeromnes** [comment]
Submitting a patch with `./mach try empty` automatically triggers linting jobs on Try:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=a1d689c88cca292a1a5b77d3f7bfd112de7659da

It found the expected 8 `mozlint` defects in my patch:

```
ES:
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/devtools/client/definitions.js:7:15 | Infix operators must be spaced. (space-infix-ops)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/devtools/client/menus.js:31:1 | Use the global form of 'use strict'. (strict)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/devtools/client/menus.js:42:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/devtools/client/shared/scroll.js:7:1 | Parsing error: Unexpected character '#' (eslint)

f8:
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/toolkit/components/telemetry/gen_event_data.py:37:16 | missing whitespace around operator (E225)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/toolkit/components/telemetry/gen_event_data.py:37:19 | at least two spaces before inline comment (E261)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/toolkit/components/telemetry/gen_event_data.py:37:100 | line too long (177 > 99 characters) (E501)
TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/toolkit/components/telemetry/gen_event_data.py:57:15 | continuation line under-indented for visual indent (E128)
```

... but still not the spelling mistake (not sure why).

It also ran a few other analyzers that I didn't know about.

**Comment by jankeromnes** [comment]
Next, I attempted to run `clang-tidy` static analysis on Try, or more specifically these jobs (found via `./mach try fuzzy`):

```
static-analysis-linux64-st-an/debug
static-analysis-win64-st-an/debug
static-analysis-win32-st-an/debug
static-analysis-linux64-st-an/opt
static-analysis-win64-st-an/opt
static-analysis-win32-st-an/opt
```

So I ran `/mach try -b do -p linux64,macosx64,win32,win64 -u static-analysis-linux64-st-an/debug,static-analysis-win64-st-an/debug,static-analysis-win32-st-an/debug,static-analysis-linux64-st-an/opt,static-analysis-win64-st-an/opt,static-analysis-win32-st-an/opt -t none` (not sure this is the right syntax).

This triggered https://treeherder.mozilla.org/#/jobs?repo=try&revision=5b00cde1127eb67795118e12087e4c1e89bf4cca

**Comment by marco-c** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1478600 to add clang-tidy as a source-test task.

**Comment by marco-c** [comment]
Another advantage that we didn't think of is that this would allow us to run analyses on both DEBUG and OPT configurations, fixing issues like #836 and #1428.
In mozilla-central we have code that is compiled only in DEBUG mode and code that is compiled only in OPT mode. In our current architecture, we are choosing between one of the two configurations (currently OPT, but we are switching to DEBUG as it's most comprehensive), but this means some issues might be missed by our bot.

**Comment by La0** [comment]
This is done :tada:
