### ISSUE TITLE
make app the default user in docker image

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1305]
the last time we tried to do this we had to [revert it](https://github.com/mozilla/release-services/pull/1301)

it should be possible to use non root user inside docker image, but next time we try this we should try running this on testing channel first.

**Comment by La0** [comment]
Totally agree, i think we only need a working directory owned by `app:app`, where the tasks & backend can work on temporary files or artifacts

**Comment by rail** [comment]
@La0 you mean adding `chown -R app: /app` after [this line](https://github.com/mozilla/release-services/blob/6e3d070fdb1ff015001d8a7c8dd973981f8ae092/nix/lib/default.nix#L846)?

Sounds very trivial. :) How should we test it before merging it again?

**Comment by garbas** [comment]
@La0 what if make this `/work` (or maybe even more descriptive name such as `/app-work` or  `/app-tmp`) and make this directory a temporary directory $TMPDIR. Then we can use `tempfile.gettempdir()`.
