### ISSUE TITLE
split cli_common and backend_common into multiple packages

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1314]
both `cli_common` and `backend_common` are growing in size. 

Current pain points I see with this approach are:
- any change to `cli_common` will trigger a redeployment of all python projects
- any change to `backend_common` will trigger a redeployment of all backend projects
- we can not depend on other extras from the same package (maybe we can, but when i tried it i failed)

For this i propose that each extra becomes its own packages, (eg. cli_common[log] -> common/log and when we use from python we would do: ``import common_log``). Before splitting this packages I would wait for #1295 is done so that it becomes easier to group packages.

Main argument against above approach would be that this would create many new projects that we would need to keep up to date. Maybe waiting for #1084 to be first implemented would make this less of a maintenance burden.

**Comment by garbas** [comment]
@La0 @marco-c @rail above are just my ideas. At one point this year I would like to solve this. I think starting a discussion regarding is step number one.

**Comment by marco-c** [comment]
I agree with the above. This might also be a good first step towards making projects less coupled. E.g. we could allow projects to update their dependencies separately even for these common packages, this way if you make a modification to `common_log` that is useful for project A but useless for project B, you could just update `common_log` for project A and leave it be for project B.

**Comment by garbas** [comment]
@marco-c awesome idea. i think we would need to add this support in pypi2nix. we would need to add a support for specifying a project in sub path of a repository. i wonder is there is anything like this already possible in requirements.txt specification.

**Comment by garbas** [comment]
looks like this is already part of the [spec](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format). we would need to support subdirectory in pypi2nix
