### ISSUE TITLE
Running update dependencies with not-existing packages doesn't throw any error

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1319]
To reproduce, just put a random name in requirements.txt of a project, try to update its dependencies and see that it says "DONE" even though it doesn't do anything.

**Comment by marco-c** [comment]
It looks like `nix-shell nix/update.nix --argstr pkg PROJECT` is exiting with 0 no matter if it succeeds or fails.

**Comment by garbas** [comment]
I assume this is because of https://github.com/garbas/pypi2nix/pull/211, correct?

With #1220 `nix/update.nix` script will go away and `please_cli` will call update script directly. eg. `nix-shell src/<project>/default.nix -A update`

**Comment by marco-c** [comment]
> I assume this is because of garbas/pypi2nix#211, correct?

garbas/pypi2nix#211 is improving the error thrown by pypi2nix, but it's still not shown as our scripts seem to eat the error.
