### ISSUE TITLE
Install a text editor in the docker image

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1322]
Sometimes it can be useful for debugging.

**Comment by garbas** [comment]
I almost don't dare to ask, but which editor should we add? vim? vi? nano? something else?

**Comment by marco-c** [comment]
Anything works for me, as long as there is something.

**Comment by kevinluvian** [comment]
@marco-c @garbas may I clarify that this issue means to install text editor in please-cli shell?
e.g all `./please shell <project>` should have text editor installed by default?

**Comment by garbas** [comment]
i'm sure i like polluting our base-image with more that is need to build things. otherwise we will quickly end up with 1GB docker image.

when needed you can already use `nix-env -f /etc/nix/nixpkgs -iA vim` command to install vim or any other tool that you need

**Comment by marco-c** [comment]
Let's not do it then, the images are already big enough.
