### ISSUE TITLE
pushing multi layer docker image fails

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1335]
[push](https://github.com/garbas/push/) was a quick hack to get this functionality working. meanwhile other more reliable tools were created that we can use for this task, [skopeo](https://github.com/projectatomic/skopeo).

instruction how can skopeo be used with nix is [here](https://discourse.nixos.org/t/push-docker-tgz-images-to-registry-directly/189)

**Comment by garbas** [comment]
This is blocking us to deploy to cloudops

**Comment by rail** [comment]
Working on this
