### ISSUE TITLE
shipit_code_coverage: Ignore awsy and talos when generating chunk mapping

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1337]

**Comment by marco-c** [comment]
https://github.com/mozilla/release-services/blob/5a5eb07c0d48e0dbfcec30ab54d11bd5be5be482/src/shipit_code_coverage/shipit_code_coverage/chunk_mapping.py#L156 and https://github.com/mozilla/release-services/blob/5a5eb07c0d48e0dbfcec30ab54d11bd5be5be482/src/shipit_code_coverage/shipit_code_coverage/chunk_mapping.py#L167 should be fixed to properly ignore `awsy` and `talos`. The awsy and talos chunks can be something like `awsy-base`, `talos-g5` and so on.
