### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by jan-ivar** [mozilla/release-services#1346]
**MozReview URL:** https://reviewboard.mozilla.org/r/173466/#comment345752

**Problem:** Is blocking review complaining about code no longer in the patch.

**Comment by sylvestre** [comment]
Arf, sorry, we don't have mozreview anymore, I cannot see the issue :(
We fixed a bunch of issues in issue detection lately, maybe we fixed that one...
