### ISSUE TITLE
please: Docker host networking not supported on Mac

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1353]
[The host networking driver only works on Linux hosts](https://docs.docker.com/network/network-tutorial-host/). https://github.com/mozilla/release-services/pull/1171 made `please` commands unusable on mac because of this reason.

I've reverted that commit locally to see if it still works. If it does, could we use binding ports for macos only?

**Comment by garbas** [comment]
oh I wasn't aware of this. I guess we can do something different for mac and windows.

@gabriel-v when you reverted #1171 did it work for you?

**Comment by gabriel-v** [comment]
@garbas Yes, it did work. I only tested the `releng-docs` project with the revert.

I'll submit a PR to use port binding on mac os.

**Comment by gabriel-v** [comment]
@garbas Abandoning the PR because of https://github.com/mozilla/release-services/issues/1410. I'm migrating to virtual machines for working on this project.
