### ISSUE TITLE
implement pleaserc.toml configuration without changing any functionality.

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1364]
Currently our configuration is stored in lib/please_cli/please_cli/config.py, and idea i would like to explore is to use context_settings when creating main please command. where default_map is being created by reading pleasetc.toml file.

I'd love to hear if there is any other pattern with click library that we could explore.

**Comment by La0** [comment]
This blocks #1221

**Comment by La0** [comment]
@garbas I think this is now solved through #1896

**Comment by garbas** [comment]
:+1:
