### ISSUE TITLE
Two reports on the same line aren't published

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#1384]
In this review: https://phabricator.services.mozilla.com/D3411, only one issue is being reported.

While locally, I found two
```
$ codespell  build/docs/toolchains.rst
build/docs/toolchains.rst:10: introdued  ==> introduced
build/docs/toolchains.rst:10: purpse  ==> purpose

```
Codespell version 1.13 finds it and it is the one we are using:
https://dxr.mozilla.org/mozilla-central/source/tools/lint/spell/codespell_requirements.txt

**Comment by La0** [comment]
Seems to work now: https://phabricator-dev.allizom.org/D698 (line 245)

We should try again your patch on staging

**Comment by La0** [comment]
Fixed
