### ISSUE TITLE
Figure out scopes needed to trigger action hooks

### ISSUE THREAD

**Issue by rail** [mozilla/release-services#1387]
In PR #1385 I needed to add a new scope to the existing client: `hooks:trigger-hook:project-gecko/in-tree-action-3-generic/dd6091ba01`.

The scope name is a bit awkward:
* The `project-gecko/in-tree-action-3-generic` prefix is too generic. You cannot tell what branch it is.
* The suffix `dd6091ba01` looks like a hash of something that may change. I assume this is the hash of `.taskclaster.yml`. If the hash changes, the scope wouldn't be usable anymore and would require extra manual work to update the client scopes.

Need to figure out how to make sure the client has sufficient, but not too broad scopes. We don't want to grant something like  `hooks:trigger-hook:project-gecko/in-tree-action-3-generic/*`

**Comment by rail** [comment]
@djmitche maybe you have some ideas here? The main idea is to have predictable scope names that we can assign to clients in advance. Or maybe there is another work around...

**Comment by djmitche** [comment]
I think you will want `hooks:trigger-hook:project-gecko/in-tree-action-3-generic/*`.  You're right about the hash.  And, the repo name is not included, but the level is.  For actions which require finer control over access, we can make them non-generic, so the scope would be something like `hooks:trigger-hook:project-gecko/in-tree-action-3-relpromo/*`.  That still applies across all level-3 repos, but means that someone with the level-3 generic scope couldn't trigger the action.

**Comment by rail** [comment]
Thanks for the confirmation. I think we can survive with the star scope for now. I wonder if we should consider adding the branch name somewhere in the scope, so we can have finer permissions.

**Comment by rail** [comment]
In my case it's the cancel-all action hook. In the future, it'll be also used by release-promotion.
