### ISSUE TITLE
Weird results from /v2/path?path=media

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1403]
Querying https://coverage.staging.moz.tools/v2/path?path=media/ (`media/` with final `/`) succesfully gives the coverage of known children (i.e. `media/webrtc/`):

```json
{
  "children": [
    {
      "coverage": 0.0873112030547771,
      "nb": 28,
      "path": "media/webrtc/",
      "type": "directory"
    }
  ],
  "type": "directory"
}
```

... but querying https://coverage.staging.moz.tools/v2/path?path=media (`media` without `/`) gives surprising results:

```json
{
  "children": [
    {
      "coverage": 0.10629189937103299,
      "nb": 23,
      "path": "media/",
      "type": "directory"
    }
  ],
  "type": "directory"
}
```

i.e. just `media/` as a single child.

I'd expect both queries to give the same results (i.e. `children: [ webrtc ]`).

**Comment by marco-c** [comment]
I guess we can WONTFIX this, as long as we're aware of this limitation.
