### ISSUE TITLE
Artifacts and reports should not be downloaded in src/shipit_code_coverage

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1411]
In the current implementation, running `shipit_code_coverage` downloads 10GB of code coverage artifacts under `src/shipit_code_coverage/ccov-artifacts/` and 100MB of reports to `src/shipit_code_coverage/ccov-artifacts/code-coverage-reports`.

I think we should add command line arguments to set these paths and stop dumping large files in the source dir.

**Comment by marco-c** [comment]
The fix for this might be the same as the fix for #1305.
