### ISSUE TITLE
Show defects which would not be shown in the automation

### ISSUE THREAD

**Issue by chmanchester** [mozilla/release-services#1417]
**Phabricator URL:** https://phabricator.services.mozilla.com/D3847

**Problem:** Comments were left on this file, however it's not included in our linting configuration, so the issues wouldn't cause a failure in automation. 

I ignored the first issue opened (marked it as "Done"), but a second issue, apparently a duplicate, was opened after lando re-based the patch.

**Comment by marco-c** [comment]
This should be fixed with the move to Try.
