### ISSUE TITLE
Add column with full task name to chunk mapping tables

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1426]
The chunk mapping could use a column `task` with the full task name (`run.key` from ActiveData).

After this is done, we can fix [bug 1485741](https://bugzilla.mozilla.org/show_bug.cgi?id=1485741).

**Comment by marco-c** [comment]
We'll fix bug 1485741 without this. Once things are more stable, we'll re-evaluate what to store in the chunk mapping and avoid mismatches.
