### ISSUE TITLE
Ingest Android Java coverage

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1442]
Even though we are building a replacement directory viewer, it would be nice to start injesting this data on codecov.io so we can show it to the world (and it shouldn't take too much).

@gabriel-v can you take this?

**Comment by gabriel-v** [comment]
We have a problem: our Java code coverage reports don't contain complete relative paths for each Java file. The paths we have in our coverage reports are relative to Java package root, and we have a few Java package roots around the repo.

ActiveData matches the files by taking suffixes of decreasing lengths, which fixes this problem.

We can try and push the reports to codecov.io and see what happens. I'll open a PR to do this.

**Comment by marco-c** [comment]
Yes, sounds easier to do it directly in grcov.
