### ISSUE TITLE
Phabricator base revision could be coming from a different repository than mozilla-central

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1446]
E.g. [log.txt](https://github.com/mozilla/release-services/files/2329397/log.txt)

The relevant part is:
static_analysis_bot.revisions: Failed to update to base revision (revision='48ca12e943f5f8514dcc01e4ba9ec1888dce8485' error=CommandError(b'update', b'-r48ca12e943f5f8514dcc01e4ba9ec1888dce8485', b'-C'))

48ca12e943f5f8514dcc01e4ba9ec1888dce8485 is an autoland revision. At some point it will be on mozilla-central too, but at the time the bot is triggered it isn't.

**Comment by marco-c** [comment]
https://hg.mozilla.org/integration/autoland/rev/48ca12e943f5f8514dcc01e4ba9ec1888dce8485

**Comment by La0** [comment]
According to [my latest dev on SA dashboard](https://static-analysis.testing.moz.tools/#/), 50% of all tasks are failing due to mercurial errors (mostly failing to update to a revision).

@marco-c I just have to replace `mozilla-central` to `mozilla-unified` to test your theory ?

**Comment by marco-c** [comment]
I think so, yes. Maybe you can take one of the recent failing tasks and try locally (has to be recent, otherwise the commit will now be on mozilla-central too).

**Comment by La0** [comment]
Testing uses mozilla-unified since yesterday, and i still get a lot of missing revisions :(

**Comment by marco-c** [comment]
I think it's better to reproduce locally so we can debug, maybe robustcheckout is not cloning all the branches of the unified repo.
What is an example missing revision?

**Comment by marco-c** [comment]
Fixed by #1488.
