### ISSUE TITLE
Delete unused shipit-uplift roles

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1464]
We have:
```
hook-id:project-releng/services-production-shipit_bot_uplift-bot
hook-id:project-releng/services-production-shipit-bot-uplift
hook-id:project-releng/services-production-shipit-bot-uplift-bot
hook-id:project-releng/services-staging-shipit-bot-uplift
```

**Comment by La0** [comment]
Should be OK to delete them before next release (v46)

**Comment by marco-c** [comment]
I don't have the scopes to remove these roles.

**Comment by La0** [comment]
Me neither. I removed the uplift hooks, but I can't remove those roles. 

Ping @garbas : if you want to remove them, feel free to do so. Thanks !

**Comment by marco-c** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1580135.
