### ISSUE TITLE
Add dockerflow api endpoints for each backend project

### ISSUE THREAD

**Issue by hwine** [mozilla/release-services#148]
Implement [Dockerflow](https://github.com/mozilla-services/Dockerflow) endpoints and the rest of their specification.

 - [ ] Add ``dockerflow_endpoints`` (True y default) argument to the ``create_app`` method in ``lib/backend_common/backend_common/__init__.py``

- [ ] implement ``configure_dockerflow_endpoints`` method in ``lib/backend_common/backend_common/__init__.py`` as it is done in [Balrog](https://github.com/mozilla/balrog/blob/master/auslib/dockerflow.py#L44).

- [ ] conditionally, if  ``dockerflow_endpoints`` argument is true, configure dockerflow endpoints in ``create_app`` method in ``lib/backend_common/backend_common/__init__.py``

- [ ] document dockerflow endpoints option in ``src/releng_docs/developing.rst``

- [ ] when creating docker also create a symlink of a project folder (from ``/nix/store/...``) to ``/app`` as described in Dockerflow specs

- [ ] create [/app/version.json](https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md) in a separate layer and then push the image.

**Comment by garbas** [comment]
I think I talked with Ben about this some time ago and he showed me a list of endpoints that CloudOps team wants all applications they serve to implement. A version just being one of them.

@mozbhearsum I know you showed me a GitHub repository with a list of this endpoints. Do you maybe remember the link?

**Comment by mozbhearsum** [comment]
That's part of the Dockerflow spec: https://github.com/mozilla-services/Dockerflow

**Comment by hwine** [comment]
AWS outage of today shows the need for (at least) ```/__heartbeat__``` being implemented. Once there, the hg.mozilla.org hooks can be updated to detect this situation and "fail closed" as desired.

The hg.mozilla.org work is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1343334

**Comment by hwine** [comment]
AWS outage of today shows the need for (at least) ```/__heartbeat__``` being implemented. Once there, the hg.mozilla.org hooks can be updated to detect this situation and "fail closed" as desired.

The hg.mozilla.org work is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1343334

**Comment by garbas** [comment]
@harikishen I updated the description of this ticket with more details. Does it make more sense now?

**Comment by harikishen** [comment]
@garbas somewhat

**Comment by rail** [comment]
Done in PR #1183
