### ISSUE TITLE
staticanalysis/bot: add a text field to enabled checkers to justify their use (e.g. in reviewbot comments)

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1481]
We could for example call this field `reason` (or `rationale` / `justification` / `why` / ...):

```
  - name: readability-braces-around-statements
    reason: "Mandated by Mozilla's style guide: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#Control_Structures"
```

This field could then be printed in the output when a related defect is found by `./mach static-analysis check`, and also in code review comments, like so:

```
dom/xslt/xslt/txPatternParser.cpp:240:

Warning: Statement should be inside braces [clang-tidy: readability-braces-around-statements]
  if (!XMLUtils::isValidQName(key, &colon))
                                          ^
                                           {
Reason: Mandated by Mozilla's style guide: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#Control_Structures
```

**Comment by rv404674** [comment]
hi @jankeromnes , can i take up this bug. I am a newcomer, can you guide me on how to proceed.

**Comment by jankeromnes** [comment]
Hi @rv404674, thanks a lot for your interest! We're so happy that you'd like to help. :smile: 

I'll do my best to guide you through the process, but if something doesn't make sense to you please never hesitate to ask.

The docs at https://docs.mozilla-releng.net/projects/shipit-static-analysis.html have a bit more detail on how to run `staticanalysis/bot` locally (Notes: It was recently renamed from `shipit-static-analysis`, and some parts of the docs might still use the old name. Also you can entirely skip `4. Setup a Mozreview test` since MozReview no longer exists).

**Comment by rv404674** [comment]
Thanks a lot ,@jankeromnes appreciated. Can you tell me which irc do you use??. And i how to connect to you using that.

**Comment by jankeromnes** [comment]
Sure! We usually hang out in `#release-services` in Mozilla's IRC network (not Freenode). You can join us there with riot.im (I find it a bit complicated) or KiwiIRC using this [direct link](https://kiwiirc.com/nextclient/irc.mozilla.org/?#release-services).

**Comment by rv404674** [comment]
hey @jankeromnes , i have messaged you on irccloud. Can you take a look.

**Comment by jankeromnes** [comment]
A few helpful pointers for this issue:

The YAML file in which we could add a `reason` field to each checker lives in the Firefox repository. It is called `tools/clang-tidy/config.yaml`, and can be found here:

https://hg.mozilla.org/mozilla-unified/raw-file/tip/tools/clang-tidy/config.yaml

It is downloaded at runtime by our bot here:

https://github.com/mozilla/release-services/blob/f1248769455a673e477c2a4d990fcda33adcda24/src/staticanalysis/bot/static_analysis_bot/config.py#L81-L95

Maybe we could start by adding a `reason` field to one of the checkers in our mock `config.yaml` (used in tests):

https://github.com/mozilla/release-services/blob/f1248769455a673e477c2a4d990fcda33adcda24/src/staticanalysis/bot/tests/mocks/config.yaml

Then, to start implementing this field, I suggest that if there exists a `reason` field for a specified clang-tidy checker, you copy it into a `self.reason` attribute in any corresponding `ClangTidyIssue`:

https://github.com/mozilla/release-services/blob/318207db2dcc79ad03247e4e0492bde51dafc7c8/src/staticanalysis/bot/static_analysis_bot/clang/tidy.py#L229

Notes:

- `ClangTidyIssue`s are created during a code analysis, and `self.check` correspond's to `config.yaml`'s `- name` field
- Also, there can be several `ClangTidyIssue`s with the same `self.check`, or there can be none, e.g. if no such issue was detected during analysis.

Later, when this issue is exported, we'll be able to serialize this `self.reason` field into the output.

**Comment by abpostelnicu** [comment]
I would advise to use the official documentation of clang-tidy here in order to argument the checker. Of course we can modify a little bit, but if we are to add some sort of argumentation we should start with the official description of each checker, for example see the description of [modernize-use-equals-default](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html)

**Comment by rv404674** [comment]
heyy @jankeromnes , i created a PR for this. Sorry if the code looks shitty.

**Comment by sylvestre** [comment]
@rv404674 bravo for this work. I think we will start using that feature more and more with coverity and infer. cc @abpostelnicu

**Comment by rv404674** [comment]
Thanks @sylvestre

**Comment by jankeromnes** [comment]
@rv404674 I'll join @sylvestre in congratulating you on this! Thanks a lot for your time and hard work, you've created a really cool and useful feature. :slightly_smiling_face: :+1: :tada:

**Comment by rv404674** [comment]
Thanks @jankeromnes , i enjoyed a lot in developing this feature. I have stopped contributing for some time to rel eng, due to my placement activities. But once it gets over, i will again start contributing. One more thing, is there any swe internship opputunity available in your team. :)

**Comment by jankeromnes** [comment]
It's always ok to stop contributing to a project, especially when we need to spend time on other things (e.g. work, studies, family, health, etc). But we're happy to review more pull requests if you're motivated! :smile: 

Also, unfortunately I don't think our team is hosting interns this summer, but you can always see Mozilla's current internship offers over here:

https://careers.mozilla.org/listings/?position_type=Intern

Feel free to apply to any offer that looks fun!

**Comment by sylvestre** [comment]
@rv404674 Hello
Sorry for the latency, I think there is enough information in this bug to start with, don't you think ? :)

**Comment by sylvestre** [comment]
I reported this in bugzilla too: https://bugzilla.mozilla.org/show_bug.cgi?id=1539072

**Comment by rv404674** [comment]
Hi @sylvestre . Yup there is, but i will not be applying for that project. To be frank i am not interested in testing at all and i found another project in mozilla for which i am greatly excited to to and it is being used by codecoverage - TUID. I hope you won't mind me applying for different project, btw i won't stop contributing to releng in my free time. ;).
