### ISSUE TITLE
Phabricator base revision might be non public

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1483]
Until https://bugzilla.mozilla.org/show_bug.cgi?id=1489509 is fixed, in some cases we won't have access to the base revision the Phabricator revision is based on.

I guess for static analysis we should just try to apply the patch in those cases and fail if it doesn't apply.

For code coverage, the API can return an error.

**Comment by jankeromnes** [comment]
FYI: With Lando, patches are always landed on top of `HEAD`, regardless of any base revision Phabricator might have:

> glob> janx: no, transplant doesn't care about the base revision; patches are always landed on HEAD
> glob> the steps are: a patch is uploaded to phabricator for review; that patch is approved via lando, which passes the patch to transplant for landing...
> glob> transplant updates its mozilla-central clone, and tries to apply the patch to the most recent commit
> glob> it isn't as foolproof than doing an import then rebase which we had with mozreview, however phabricator works with patches, not repositories

**Comment by marco-c** [comment]
OK, thanks! So, it sounds like the current approach we have is good enough (try to apply on the base revision first, otherwise try to apply on latest mozilla-central).

**Comment by marco-c** [comment]
(See also https://bugzilla.mozilla.org/show_bug.cgi?id=1483966)

**Comment by marco-c** [comment]
This was fixed a long time ago.
