### ISSUE TITLE
Fix uplift/backend bootstrap

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1495]
There are several issues for new developpers starting to work on `uplift/*`:

- [x] postgresql validation is disabled, hence DB creation (services is always missing !)
- [x] a DB migration `src/uplift/backend/migrations/versions/2158e8a5b554_.py` is failing
- [x] Default cache root to local dev tmp directory
- [x] Remove useless boot dep on redis
- [x] Missing sane default on `master` secret (a working TC client)
- [x] Update doc

**Comment by jankeromnes** [comment]
Blocks #1466.
