### ISSUE TITLE
Cleanup Taskcluster namespace usage

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1505]
We are using 2 Taskcluster namespaces for our projects: `project:shipit` and `project-releng`.
We should create a new one, and migrate everything inside (`project-release` ?)

There should be several roles for bots, users, and admins.

Migrating secrets would also be nice

**Comment by garbas** [comment]
@La0 :+1: on this.

let just specify here more in detail what we currently have and to what we would migrate it.
I would also like to document all the roles/scopes/clients/... as we are doing this migration.
