### ISSUE TITLE
Static analysis bot does not find all issues in the header file

### ISSUE THREAD

**Issue by jandem** [mozilla/release-services#1506]
See this commit: https://phabricator.services.mozilla.com/D5557

reviewbot found 24 issues (missing braces, required per new SpiderMonkey style). Excellent!

However, it did not flag similar missing-braces in Interpreter-inl.h 

@sylvestre @jankeromnes @marco-c

**Comment by jandem** [comment]
(I can't add the app:staticanalysis/bot label.)

**Comment by jankeromnes** [comment]
Thanks a lot for reporting this issue! Maybe there is a bug in our defect filtering system, which wrongly filtered out the similar issues in `Interpreter-inl.h`.

I'll try to dig up the Task and logs corresponding to this analysis, to find out more about what happened.

**Comment by jankeromnes** [comment]
I did find our internal email report about this analysis, titled `[production] New Static Analysis Phabricator #14467 - PHID-DIFF-vu55bvrhp4pu27i4yg6z`, but for some reason I can't find it on our internal [dashboard](https://static-analysis.moz.tools/#/), so I don't have a Task or any logs yet.

**Comment by jankeromnes** [comment]
So, all of these are not on "lines modified by the patch" (our current heuristic for filtering defects), so it's expected that they're not reported. (There might have been other defects detected by the bot, but I can't know, since the email was truncated and I couldn't find logs for this analysis.)

Most defects in `Interpreter-inl.h` seem to be inside `#ifdef ENABLE_BIGINT` / `#endif` blocks, which we may not compile during our `clang-tidy` analysis.

However, the following defects aren't, and should have been reported by the bot:

```
Unreported and not detected:
js/src/vm/Interpreter-inl.h:761
js/src/vm/Interpreter-inl.h:776
js/src/vm/Interpreter-inl.h:791
js/src/vm/Interpreter-inl.h:806
js/src/vm/Interpreter-inl.h:821
js/src/vm/Interpreter-inl.h:836
```

It seems our bot simply hasn't detected any defects that were new, but just the old ones. I'm a bit confused now.

**Comment by jankeromnes** [comment]
@La0 would you know a way to find the Task and the logs for this analysis which doesn't seem to be listed in the dashboard?

**Comment by jankeromnes** [comment]
Great suggestions from IRC:

> 09:26:14 bastien> janx: if the task executed it should be there, you can try papertrail otherwise, on both pulse listener & static analysis bot
> 09:26:29 bastien> janx: and you still can run the patch locally, see what happens

Thanks! I'll start with searching through papertrail.

**Comment by jankeromnes** [comment]
I was able to find the task via papertrail: https://tools.taskcluster.net/groups/UQzG5gHOSCmuq7qwhhLxvg

(Note: The relevant line in papertrail was:

> Sep 11 19:19:34 52.91.255.98 mozilla/release-services/production/static-analysis-bot: 2018-09-11 17:19:34.091862 taskcluster.utils: HTTP Payload: {"taskId":"UQzG5gHOSCmuq7qwhhLxvg","rank":0,"data":{"source":"phabricator","diff_phid":"PHID-DIFF-vu (limit 100 char)

which unfortunately truncates the diff-phid, so I couldn't find it by searching for `PHID-DIFF-vu55bvrhp4pu27i4yg6z`. Maybe we could increase the limit to 200 char or more?)

At first glance, it looks like there were a few `clang-diagnostic-errors` around the lines where we expected defects to be found:

```
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 761:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 776:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 776:39
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 791:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 791:39
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 806:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 806:39
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 821:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 821:39
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 836:10
static_analysis_bot.clang.tidy: Encountered a clang-diagnostic-error: [error] clang-diagnostic-error js/src/vm/Interpreter-inl.h 836:39
```

However, this doesn't give us any insight into what went wrong. I guess we'll have to reproduce the analysis locally in order to get more details about the diagnostic errors.

**Comment by jankeromnes** [comment]
@La0 just reminded me that our Tasks now include an artifact with the full `clang-tidy` output (I even added it, but forgot about it).

Here are the diagnostic errors:

```
/cache/sa-central/js/src/vm/Interpreter-inl.h:761:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, in))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:776:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:776:39: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
                                      ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:791:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:791:39: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
                                      ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:806:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:806:39: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
                                      ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:821:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:821:39: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
                                      ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:836:10: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
         ^
/cache/sa-central/js/src/vm/Interpreter-inl.h:836:39: error: use of undeclared identifier 'ToInt32OrBigInt' [clang-diagnostic-error]
    if (!ToInt32OrBigInt(cx, lhs) || !ToInt32OrBigInt(cx, rhs))
                                      ^
```

It appears that `clang-tidy` is missing the `ToInt32OrBigInt` identifier, and thus analysis failed on these lines.

This symbol seems to be introduced in [Part 2](https://phabricator.services.mozilla.com/D5556) (this analysis was for Part 3), but the present analysis ran on top of latest `mozilla-central` (`static_analysis_bot.workflow: Set repo back to Mozilla central top (rev=b'423bdf7a802b tip\n')`).

Luckily, we've just started supporting Phabricator Stacks, and our latest release (from yesterday) should be able to apply parent commits before running analysis. So, hopefully, re-uploading all patches today should not reproduce this bug.

**Comment by jandem** [comment]
> Luckily, we've just started supporting Phabricator Stacks, and our latest release (from yesterday) should be able to apply parent commits before running analysis.

Very interesting. Thanks for the analysis!
