### ISSUE TITLE
Ignore patches that are not for mozilla-central

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1510]
E.g. the tasks triggered for https://phabricator.services.mozilla.com/D4217 and https://phabricator.services.mozilla.com/D2561 failed because they apply to different projects (LANDO and NSS).

**Comment by marco-c** [comment]
As @La0 suggested, it's better to do this in the pulse listener so we don't even trigger the task.

**Comment by La0** [comment]
@marco-c After a day on testing, the ratio of successfully analysed patches is a bit better (86% on testing instead of 83% on production). 
This is not on the same period, but that looks good (and not *too good*)
