### ISSUE TITLE
add "enable" option to `please_cli/config.py` to be able to disable projects.

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1513]
Configuration for all projects and how/where we deploy them is in `lib/please_cli/please_cli/config.py` (look for `PROJECTS_CONFIG` variable)

There are times where we would like to *pause* the deployment of certain services for some time (eg. while an owner is on vacation or when service is in freeze mode). 

It would be easy just to comment out the deployments which we want to disable for a period of time, but this turned out to be problematic since some project's configuration is interdependent (eg: frontend needs to know to which backend to talk). 

We would need to be able to disable the a project's deployment without commenting out the project's configuration.

Scheduling of deployment happens with `./please tools decision-task ...` command (code: `lib/please_cli/please_cli/decision_task.py`) and this is where this change needs to be applied.

Each section which describes deployment of a channel should have `enable` option and  `./please tools decision-task ...` command should take that into the account when creating taskcluster tasks for deployment.

Example:

Current configuration for `shipit/api` project is

```python
{
    'target': 'DOCKERHUB',
    'options': {
        'testing': {
            'url': 'https://api.shipit.testing.mozilla-releng.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
        'staging': {
            'url': 'https://shipitbackend-default.dev.mozaws.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
        'production': {
            'url': 'https://shipit-api.mozilla-releng.net',
            'dns': 'shipitbackend-default.prod.mozaws.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
    },
}
```

and this configuration should be changed to

```python
{
    'target': 'DOCKERHUB',
    'options': {
        'testing': {
            'enable': true,
            'url': 'https://api.shipit.testing.mozilla-releng.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
        'staging': {
            'enable': true,
            'url': 'https://shipitbackend-default.dev.mozaws.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
        'production': {
            'enable': true,
            'url': 'https://shipit-api.mozilla-releng.net',
            'dns': 'shipitbackend-default.prod.mozaws.net',
            'nix_path_attribute': 'dockerflow',
            'docker_registry': 'index.docker.io',
            'docker_repo': 'mozilla/shipitbackend',
        },
    },
}
```

and once we want to disable some project's deployment we will change `enable` option to false for that channel.

**Comment by rv404674** [comment]
hey @garbas, a question regarding this. I need to add enable option in all places that have target = {s3 or heroku or dockerhub or taskcluster).   And for all projects - shipit, releng no??

**Comment by rv404674** [comment]
hey @garbas , i have opened a PR for it. Can you please review it when you get some time. Thanks :)
