### ISSUE TITLE
create deployment for please_cli project to taskcluster hook

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1514]
We need to deploy current base image taskcluster hook without being scheduled. we might use please_cli project to do this or make it a manual step during the deployment.

This can be then used to do manual deployments or even quick development environment.

We first need https://github.com/mozilla/release-services/issues/1598 to be done

**Comment by La0** [comment]
Meanwhile, here is how to deploy a single project using taskcluster on production:

## Requirements

* The published git commit of the head you want to deploy, let's name it `UPDATE_COMMIT`
* This revision should already be built by Taskcluster (on a PR for example)

## Find the last production deployment:

1. Lookup the [last release version](https://github.com/mozilla/release-services/releases). Now it's `47`
2. Go to the commit Head for this release: https://github.com/mozilla/release-services/commits/v47
3. Click on the green tick on the top commit, it should redirect you to [the last taskcluster deployment](https://tools.taskcluster.net/groups/aT-ycknwRyOg43kRY7_-mg)

## Trigger the right task for your project

1. On the taskcluster task group, click on the task related to your project: [staticanalysis/bot](https://tools.taskcluster.net/groups/aT-ycknwRyOg43kRY7_-mg/tasks/L8gkDKLpTAurTXapc5xN9A/details)
2. Double check you're viewing a deployment task on the righ env. (production!)
3. Click on `Actions > Edit Task`
4. Click on `Update timestamps`
5. :warning:  Here is the tricky part: replace every occurence of the old commit hash (lookup the `GITHUB_COMMIT` variable content), by your own `UPDATE_COMMIT` value. Be careful, there are several usages in the environment, but also in the command line. You should use a text editor to do that, and paste the result into Taskcluster
6. Click on `Create Task`
7. Wait for `please` to do its magic
8. ...
9. Profit !
