### ISSUE TITLE
staticanalysis/bot: Undetected defect + checkers not found

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1530]
**Review:** https://phabricator.services.mozilla.com/D5326

**Task:** https://tools.taskcluster.net/groups/OwfCid8jT7a4PVnykFL0FQ

**Problems:**

- [x] ~~in `js/src/vm/Time.cpp`, a missing brace is detected on line 50, but not on line 163 (and the logs include don't mention it at all, not even with a diagnotic error)~~ (expected, see [explanation](https://github.com/mozilla/release-services/issues/1530#issuecomment-424648076))
- [x] the Task's logs show many `clang-tidy check not found` errors (are we using the right version of `clang-tidy`?):

```
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-argument-comment" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-assert-side-effect" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-bool-pointer-implicit-conversion" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-forward-declaration-namespace" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-macro-repeated-side-effects" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-string-constructor" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-string-integer-assignment" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-suspicious-missing-comma" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-suspicious-semicolon" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-swapped-arguments" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "bugprone-unused-raii" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "clang-analyzer-security.insecureAPI.bcmp" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "clang-analyzer-security.insecureAPI.bcopy" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "clang-analyzer-security.insecureAPI.bzero" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "performance-implicit-conversion-in-loop" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "performance-inefficient-algorithm" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "performance-move-const-arg" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "performance-move-constructor-init" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "performance-noexcept-move-constructor" not found.
static_analysis_bot.clang.tidy: Specified clang-tidy check "readability-static-accessed-through-instance" not found.
```

View [full logs](https://taskcluster-artifacts.net/OwfCid8jT7a4PVnykFL0FQ/0/public/logs/live_backing.log).

**Comment by jankeromnes** [comment]
By (sorting and) diffing the list of available checkers from the logs against various `clang-tidy` versions, I was able to find out that the analysis was based on `clang-tidy-5.0` (instead of `clang-tidy-7`).

**Comment by jankeromnes** [comment]
I randomly tested one of our latest production tasks on our internal dashboard https://static-analysis.moz.tools/#/, i.e. https://tools.taskcluster.net/groups/dA2xZO0lSwqQSZ7u9cWefQ/, and it's also `5.0`.

**Comment by jankeromnes** [comment]
bc7af4bb9afe447261d1f84d97d816435c3b445f fixed our artifact URL from `clang-tidy 5.0.1` to `7.0.0`. The fix should be part of the next release tomorrow.

**Comment by jankeromnes** [comment]
I just ran the latest `master` locally against `PHID-DIFF-6xlnnhssoftbejhzleev` (from https://phabricator.services.mozilla.com/D5326), and it seems that `clang-tidy 7.0.0` was successfully used, however the bot still only found one of the two missing braces in `Time.cpp`:

```
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/vm/Time.cpp 44:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] readability-braces-around-statements js/src/vm/Time.cpp 50:50
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] modernize-use-nullptr js/src/vm/Time.cpp 58:23
```

So the first issue in the original post remains unfixed.

**Comment by La0** [comment]
@jankeromnes Do you reproduce this by using clang-tidy directly on your "bad" file ?
This looks like an issue from clang-tidy, not the bot (except if there is a parsing issue)

**Comment by abpostelnicu** [comment]
I can’t seem to reproduce this locally, maybe some logs from the task might help us, since could be a parsing issue.

**Comment by La0** [comment]
@abpostelnicu I created [a task on testing](https://tools.taskcluster.net/groups/JSYT0LLVSP2kv_fjFltU_A/tasks/JSYT0LLVSP2kv_fjFltU_A/runs/0/logs/public%2Flogs%2Flive.log) for this specific diff.

There should be the clang-tidy output in the artifacts in a few minutes

**Comment by jankeromnes** [comment]
Well done team! One more issue fixed. :slightly_smiling_face:
