### ISSUE TITLE
Break the CI when the version of clang-tidy isn't correct

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#1531]
We saw in https://github.com/mozilla/release-services/issues/1530 that we have been using the wrong version of clang-tidy. we should an entry check. especially as config.yaml has very specific checkers.

**Comment by jankeromnes** [comment]
One way we could achieve this is, in every analysis task, run the equivalent of `clang-tidy --version`, and assert that we have the right version.

The question is, how should we tell the bot what the "right version" is? Hard-coded in Python? Configured in secrets? Pinned in [config.yaml](https://hg.mozilla.org/mozilla-unified/raw-file/tip/tools/clang-tidy/config.yaml)?

**Comment by abpostelnicu** [comment]
We should add it in [config.yaml](https://hg.mozilla.org/mozilla-unified/raw-file/tip/tools/clang-tidy/config.yaml)

**Comment by jankeromnes** [comment]
Should we pin a specific version (e.g. `clang-tidy-version: "7.0.1"`), or set a version range (e.g. `clang-tidy-range: ">= 7; < 8"`), or just set the minimum version (e.g. `min-clang-tidy: "7.0.0"`)?

**Comment by abpostelnicu** [comment]
I would use a min-clang-tidy, since major updates are not that common.

**Comment by abpostelnicu** [comment]
Fired [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1493672) in Bugzilla for having min_clang_tidy option in our config file.

**Comment by La0** [comment]
So what's the implementation decision here ?
Either @jankeromnes or me implement the check in the bot, or @abpostelnicu does it in `./mach static-analysis check`

**Comment by jankeromnes** [comment]
How about we enforce it in `./mach static-analysis check`, but allow to bypass this check in case you really know what you're doing? E.g. we could fail with:

```
Error: The provided clang-tidy (5.0.1) is older than the minimum recommended version (7.0.0). Please use a more recent clang-tidy, or bypass this check by re-running with --allow-deprecated.
```

and replace this error with a simple warning if you provide `--allow-deprecated` while continuing with the analysis?

**Comment by abpostelnicu** [comment]
I like the idea of having it in mach, I will do that.
