### ISSUE TITLE
Post a comment when a patch cannot be applied

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1542]
This way the developer knows that the analysis cannot run (and also that Lando cannot be used to land their patch).

**Comment by sylvestre** [comment]
@markrcote This might be interesting for you

**Comment by La0** [comment]
This can be now be done in pulselistener, in the `MercurialWorker`. We have the patch stack being applied there, and the Harbormaster target PHID, so we can report directly on the build and/or post a comment on the revision.

**Comment by La0** [comment]
An option would be to abuse Unit tests results from Harbormaster, as they allow posting results without a path.

Here is a demo on phabricator-dev (the unit tests section has a "broken" test):

![](https://i.imgur.com/L5dsUpZ.png)

**Comment by La0** [comment]
Some [more tests](https://phabricator-dev.allizom.org/D1146)

We have access to remarkup formatting to display nicely complex informations.

**Comment by marco-c** [comment]
It's a bit of a stretch, but it looks good to me!

**Comment by La0** [comment]
After restarting the build, the unit tests disappear (which is good !)
