### ISSUE TITLE
Improve the way we download the clang-tidy artifact

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1543]
We are currently downloading it with a hardcoded URL to autoland, we should download it in a more robust way.

**Comment by marco-c** [comment]
Here's the mozilla-central source code that does the artifact downloading: https://searchfox.org/mozilla-central/source/python/mozbuild/mozbuild/artifacts.py.

Maybe we could even use it directly in our bot by importing it (since we have a mozilla-central clone).

**Comment by La0** [comment]
We are blocked by [this line in mach](https://dxr.mozilla.org/mozilla-central/source/python/mozbuild/mozbuild/mach_commands.py#1421).

@marco-c [has filed a bug to improve this](https://bugzilla.mozilla.org/show_bug.cgi?id=1497155).

Once we can run `./mach artifact toolchain --from-build linux64-clang-tidy` on taskcluster, we can remove the hardcoded artifact download

**Comment by abpostelnicu** [comment]
If we can I think we should let `./mach static-analysis check ... ` do its work behind the curtains and not directly call `./mach artifact toolchain --from-build linux64-clang-tidy`. In the end, `static-analysis` grabs the artifact from the [artifact manager](https://dxr.mozilla.org/mozilla-central/source/python/mozbuild/mozbuild/mach_commands.py#2416) and moves them into `.mozbuild` so this would bring us even more inline with what `mach` is doing.

**Comment by La0** [comment]
Outdated with the move to Try.
