### ISSUE TITLE
Notify via IRC when deployment via to testing/staging/production happens

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1565]
In `release-services` we can deploy all projects at once by just pushing code to `testing` / `staging` / `production` branch.

Once code is pushed to a branch a taskcluster a job, defined in `.taskcluster.yml`, is started. This job is to run `./please tools decision-task` command, which in turn checks what needs to be built and creates appropriate tasks.

The task in this ticket is to send IRC notification to `#release-services` **before** we start creating other tasks. The notification message should say: `New deployment on <CHANNEL> just started: <LINK_TO_TASKCLUSTER_TASK_GRAPH>`, where CHANNEL is one of testing, staging or production and where LINK_TO_TASKCLUSTER_TASK_GRAPH is a link to a graph of that deployment.

For IRC notification we can use taskcluster notify service: https://docs.taskcluster.net/docs/reference/core/taskcluster-notify/references/api
Taskcluster credentials and taskcluster python client should already be present in please_cli project.

Few more details:

- you can see how to "get" taskcluster service [here](https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/decision_task.py#L394). in this case we need to use [notify service]( https://docs.taskcluster.net/docs/reference/core/taskcluster-notify/references/api). you probably need to instantiate a notify service like

  ```python
  taskcluster_notify = cli_common.taskcluster.get_service('notify')
  ```

- notification should be send immediately so right after initializing notify service you should send out notification, but only if we are deploying. this means that channel (which is a passed and argument) is one of ``please_cli.config.DEPLOY_CHANNELS``.

- then simply send notification using ``taskcluster_notify.irc(dict(channel='#release-services', message=f'...'))``

**Comment by rv404674** [comment]
Hey @garbas, I am working on this one. Thanks.

**Comment by rv404674** [comment]
Hi @wizofe, I am still working on it.

**Comment by rv404674** [comment]
hey @garbas , i have opened a PR for this. Do take a look when you get some free time. Thanks. :)
