### ISSUE TITLE
Use consistent naming (both for specific projects and between projects)

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1570]
We have different terminology in config.py, in PROJECT_NAME in config.py and in setup.py and in the name of the directories.
E.g. sometimes we use staticanalysis, sometimes static-analysis, and sometimes static_analysis.

- [x] codecoverage/backend, #1566.
- [ ] codecoverage/bot
- [ ] codecoverage/crawler
- [ ] staticanalysis/bot
- [ ] staticanalysis/frontend

**Comment by marco-c** [comment]
We should do the same as https://github.com/mozilla/release-services/pull/1566 for all projects.

**Comment by garbas** [comment]
for PROJECT_NAME we should use the same name as when we invoke `./please run <project>` command. APP_NAME will be deprecated/

example: right now we should fix PROJECT_NAME for `codecoverage/backend` to be `codecoverage/backend`

reason for this is that with `common/naming` utility we need to most "rich" name possible, which we can then "dumb" down based on the limitations of the usage.
