### ISSUE TITLE
Automatically use the Rust version used on mozilla-central CI

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1571]
Switching to running the task on try is going to be quite a bit of work, without offering more features than we currently have (it's going to be more stable, more maintenable, but it's not going to add much in terms of features).

We have two options to workaround the periodic Rust update:
1) Don't use the Rust nix package, but download Rust from the mozilla-central toolchain task
2) Automatically open a PR to update the Rust nix package when we detect that mozilla-central is updating its Rust (we can do that by parsing some YAML files in the mozilla-central repository).

**Comment by garbas** [comment]
1. you would probably need to move away from gecko-env in this case
2. it would be possible to parse this yaml on the fly using nix. This would break task purity, but i don't think it is needed in your case. 

In case you go with 2. ping me if you need help with writing that nix expression.

**Comment by marco-c** [comment]
The benefit of 1 is that we don't need to re-deploy whenever mozilla-central changes the version of Rust they use. It's not clear how much work it would be though, as the Rust compiler has a lot of dependencies on binary stuff.

**Comment by garbas** [comment]
this is also what i mean with nr. 2 you can detect the version of rust from from nix as you execute gecko-env (aka nix-shell).

**Comment by La0** [comment]
Can't we simply do n°2 with the [automatic updates](https://github.com/mozilla/release-services/issues/1084) tool we'll implement ?

**Comment by La0** [comment]
Bumping this, as we lost a lot of analysis due to this (10+ days) during the christmas break.

**Comment by sylvestre** [comment]
Thanks, we should fix that asap

**Comment by garbas** [comment]
Does anybody know where in mozilla-central is specified the version of rust?

**Comment by marco-c** [comment]
It's the version of the toolchain in https://searchfox.org/mozilla-central/source/taskcluster/ci/toolchain/linux.yml#540 with the toolchain-alias == linux64-rust.

**Comment by La0** [comment]
It's also available in [build/moz.configure/rust.configure](https://hg.mozilla.org/mozilla-central/file/tip/build/moz.configure/rust.configure#l68)

The rust-cbindgen version is also described in [build/moz.configure/bindgen.configure](https://hg.mozilla.org/mozilla-central/file/tip/build/moz.configure/bindgen.configure#l17)

**Comment by La0** [comment]
Outdated with the move to Try.
