### ISSUE TITLE
clang-tidy: readability-implicit-bool-conversion does not match with our coding rules

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla/release-services#1585]
https://phabricator.services.mozilla.com/D6374

There are two warnings of clang-tidy: readability-implicit-bool-conversion. However, our coding rule does not allow this style. See https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#CC_practices

> When testing a pointer, use (!myPtr) or (myPtr); don't use myPtr != nullptr or myPtr == nullptr.

So, static-analysis shouldn't use this rule.

**Comment by sylvestre** [comment]
@abpostelnicu what do you think about that?
should we extend the clang-tidy to adjust to our coding style?

**Comment by abpostelnicu** [comment]
We have this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1479298) to track the progress.

**Comment by abpostelnicu** [comment]
This has been [integrated](https://phabricator.services.mozilla.com/rMOZILLACENTRAL33692f367564122728279498617718bbc235e542) into m-c, so closing the issue.
