### ISSUE TITLE
staticanalysis/bot: Let users know why analysis failed on their patch

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1588]
Sometimes, code analysis fails for various reasons, so reviewbot can't post a review on Phabricator.

See our internal dashboard for examples: 

We will soon have a way to display basic status information on Phabricator, but for some types of failures, it might be interesting to also post a comment with more details.

For example, sometimes analysis fails because a patch can't be applied (`AnalysisException('Failed to import target patch',)`):

```
hglib.error.CommandError: (255, b'applying patch from stdin', b'
patching file toolkit/components/telemetry/build_scripts/gen_event_data.py
Hunk #1 FAILED at 37
Hunk #2 FAILED at 61
2 out of 2 hunks FAILED -- saving rejects to file toolkit/components/telemetry/build_scripts
')
```

In this case, it might be interesting to let the developer know that their patch couldn't be applied, and suggest ways to address this, e.g.

```
Code analysis could not be completed, because reviewbot failed to apply this patch:

    Something something
    Hunk failed

To help reviewbot, please rebase your patch on top of mozilla-central, or provide a valid hg parent revision in the metadata [direct link or precise instructions].
```

**Comment by marco-c** [comment]
The failed to apply case is https://github.com/mozilla/release-services/issues/1542.

**Comment by La0** [comment]
We now report mercurial failures on Phabricator.
