### ISSUE TITLE
No issues found on revision which has issues

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1613]
On https://phabricator.services.mozilla.com/D8081, the "space after ," issues were not detected.
Here is the log of the staticanalysis/bot task: [live_backing.txt](https://github.com/mozilla/release-services/files/2465007/live_backing.txt).

**Comment by marco-c** [comment]
Linting is disabled on these files: https://dxr.mozilla.org/mozilla-central/rev/c291143e24019097d087f9307e59b49facaf90cb/testing/marionette/harness/.flake8.

**Comment by sylvestre** [comment]
I agree this is confusing.
