### ISSUE TITLE
Remove the uplift/backend project

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1618]
uplift/bot still depends on uplift/backend, but we should be able to remove this dependency and then remove uplift/backend.

**Comment by La0** [comment]
The plan is to trigger `uplift/bot` from `pulselistener` and thus remove the dependency on the `uplift/backend` which is just some sort of persistence layer, mostly unused since `uplift/frontend` is not used.

**Comment by La0** [comment]
Uplifts projects are off.
