### ISSUE TITLE
path endpoint returns a file instead of a directory

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1621]
This is not reproducible with all directories, but for example https://coverage.moz.tools/v2/path?path=media/webrtc/trunk/webrtc/sdk/android/api/org/webrtc/
returns
```
{
  "coverage": 0.0,
  "nb": 1,
  "path": "media/webrtc/trunk/webrtc/sdk/android/api/org/webrtc/AudioTrack.java",
  "type": "file"
}
```

**Comment by La0** [comment]
I think that's when there is only one file in the directory: https://github.com/mozilla/release-services/blob/master/src/codecoverage/backend/codecoverage_backend/v2/__init__.py#L37

**Comment by marco-c** [comment]
It's strange because `media/webrtc/trunk/webrtc/sdk/android/api/org/webrtc/` is not supposed to be a file, so that second condition should be false.

**Comment by marco-c** [comment]
Ah, I see, it's the children there.
Do you remember why we're doing this? I don't see the benefit, it might be better to just return the list of children even if there's a single one.

**Comment by marco-c** [comment]
Maybe we could make the endpoint assume it's a directory if path ends with "/", a file if it doesn't end with "/".

**Comment by marco-c** [comment]
This should be fixed with the gcp implementation, right @La0 ?

**Comment by La0** [comment]
Indeed !
