### ISSUE TITLE
store nix hash and revision to taskcluster index on data field for each deployment

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1641]
1. we need to change each deploy task in [decision_task.py](https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/decision_task.py#L82) so that it will create an index with a nix hash and revision.

2. read more about index service api here: https://docs.taskcluster.net/docs/reference/core/taskcluster-index/references/api

especially read the part about **Indexing Routes**.

3. each deploy task should have the following route defined

```json
{
  "routes": [
    "index.project.releng.services.deployments.<channel>.<project>"
  ],
  "extra": {
    "index": {
      "data": {
        "nix_hash": "<nix_hash>",
        "revision": "<git_revision>"
      }
    }
}
```

4. `<nix_hash>` is calculated [here](https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/decision_task.py#L435) for each project. in code we call it `project_hash`

5. `<git_revision>` is passed in as an argument `github_commit`

6. `<channel>` is also passes and an argument `channel`

**Comment by rv404674** [comment]
hey @garbas , as discussed over IRC i am taking this one. Can you please assign it to me. Thanks. :)

**Comment by garbas** [comment]
@d3prof3t it looks like @rv404674 does not have time, so feel free to take it. is the description in the ticket ok? if not join us in #release-services irc channel

**Comment by rv404674** [comment]
hey @d3prof3t , please feel free to work on this issue. I am not working on this anymore. :)

**Comment by d3prof3t** [comment]
@rv404674 Thanks. @garbas I would love to join you guys on the irc channel, and could use some background over the mentioned issue.

**Comment by rv404674** [comment]
Hey @garbas , can I take this one. @d3prof3t can I take this one or you are still working on it.

**Comment by rv404674** [comment]
@garbas , as discussed over irc, i am on it. :)

**Comment by rv404674** [comment]
@garbas , what does this means "In order to add this route to a task you'll need the scope queue:route:index.<namespace>. When a task has this route, it will be indexed when the task is completed successfully.". Basically how do i index the above route???. Any snippet in the existing code base you can point to.

**Comment by rv404674** [comment]
@garbas i need to write this whole code snippet in taskcluster.yml no??. I need to add it in all the three ( testing, prod, staging) no???. And i have sent you a mail. Please do see it when you get some time. THanks

**Comment by garbas** [comment]
above mentioned attributes need to be added to every deployment task generated in decision_task.py as linked in the description of this PR.

**Comment by rv404674** [comment]
hey @garbas , sorry for pinging you again and again, but i have stuck somewhere. So here is what basically i am trying to do. Can you take a look and tell me whether i am on right track??

1) Change each deploy task in get_deploy_task() ( i.e s3, heroku,taskcluster and dockerhub) as we want to index nix_hash and revision as well.  get_deploy_task() has github_commit, channel, project and project_hash (can be passed as arguement from cmd() ). So  i need to figure out how to pass these parameters to taskcluster.yml as task will be defined there.

2) So new task (in taskcluster.yml ) will look like

- metadata:
      name: "0. Decision task"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla/release-services/tree/master"
    routes:
      -index.project.releng.services.deployments.<channel>.<project>
    scopes:
      - queue:route:index.project.releng.services.deployments.<channel>.<project>
    extra:
      index:
        data:
              -"nix_hash":<nix_hash>,
              -"revision":<git_revision,
      github:
        env: true
        events:
          - push
      }
    }       
...........
.......
........

**Comment by garbas** [comment]
@rv404674 nothing should change in `.taskcluster.yml` i only provided it as example since you were looking for it. the change needs to happen in `decision_task.py`.

I'm thinking maybe this ticket is not that beginner friendly since it requires deeper understanding how things work, even if the implementation should be easy.
