### ISSUE TITLE
Problem with an automated review: variable modified only inside #ifdef

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/release-services#1645]
**Phabricator URL:** https://phabricator.services.mozilla.com/D9442

**Problem:**

We have a code pattern like this:

```
struct S { ... };
void Foo(const S& aS) {
    S local = aS;

#ifdef SOME_PLATFORM
    local = something else;
#endif

   Bar(local);  // Bar takes const S&
}
```

clang-tidy, when running on a platform that's not `SOME_PLATFORM` is complaining that we are making an unnecessary copy of `aS`, and we could make the type of `local` be `const S&` instead.

However, we can't actually make that change since compilation would break on `SOME_PLATFORM`.

We could conceivably refactor the code to the copy is only created on `SOME_PLATFORM`, but that would entail undesirable code duplication.

**Comment by marco-c** [comment]
Similar to #836 and #1428.
Note that, for *required* checks, this doesn't matter, it would break CI.

I'm not sure there's much we can do here, it is a suggestion that developers are free to ignore, but it might still be a useful suggestion in some cases (if the code is in a hot path you might want to optimize it on !SOME_PLATFORM).
