### ISSUE TITLE
Problem with an automated review: Implicit pointer to bool conversion is too strict.

### ISSUE THREAD

**Issue by emilio** [mozilla/release-services#1657]
**Phabricator URL:** https://phabricator.services.mozilla.com/D9988

**Problem:** The bot complains about an implicit pointer too bool conversion like so:

```
Warning: Implicit conversion 'nsIFrame *' -> bool [clang-tidy: readability-implicit-bool-conversion]

primaryFrame &&
^~~~~~~~~~~~
( != nullptr)
```

Where the code looks like:

```cpp
const bool isColumnSpan =
    primaryFrame &&
    primaryFrame->IsColumnSpan() &&
    primaryFrame->HasAnyStateBits(NS_FRAME_HAS_MULTI_COLUMN_ANCESTOR);
```

I'd argue that using `primaryFrame != nullptr` is way less legible.

**Comment by sylvestre** [comment]
@abpostelnicu what do you think?

**Comment by jorendorff** [comment]
This is the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1500241 .

**Comment by abpostelnicu** [comment]
Since [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1500241) landed, we can close this bug.

**Comment by sylvestre** [comment]
If you still see it, rebase your patch against tip.
