### ISSUE TITLE
shipit/api is built when changing unrelated projects

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1664]
Very often, when I make changes to codecoverage/bot (exclusively), I see the build task for shipit/api being triggered.

CC @garbas

**Comment by marco-c** [comment]
Interestingly, a PR where this happened showed "All checks passed" even though "1.01. Building shipit/api" was still running.

**Comment by rail** [comment]
This is kind of expected, because the `shipit/api.dockerflow` attribute depends on the git revision being inside the docker image, so it changes every time. I wonder if we should disable building this attribute on some branches (master, PRs?)

**Comment by garbas** [comment]
running `curl -i https://api.github.com/repos/mozilla/release-services/contents/src/shipit` will give us last revision of a `shipit/api` project, and that should be used

**Comment by marco-c** [comment]
No longer needed as we are phasing out the repo.
