### ISSUE TITLE
Issues detected in new files are not published

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1674]
https://phabricator.services.mozilla.com/D11190 is adding a test_results.py with some issues. The issues are detected but not published because the bot thinks they are not in the patch:
```
{
  "time": 1541612296.424006,
  "revision": {
    "source": "phabricator",
    "diff_phid": "PHID-DIFF-ys2l54m2lvbwewiekczg",
    "phid": "PHID-DREV-ha523hqb5kuful6kliyz",
    "id": 11190,
    "url": "https://phabricator.services.mozilla.com/D11190",
    "has_clang_files": false,
    "title": "Bug 1503599 - [mozlint] Default lineno to 0 in result.Issue if unset",
    "bugzilla_id": "1503599"
  },
  "issues": [
    {
      "analyzer": "mozlint",
      "level": "error",
      "path": "python/mozlint/test/test_result.py",
      "linter": "flake8",
      "line": 8,
      "column": 1,
      "nb_lines": 1,
      "rule": "F401",
      "message": "'pytest' imported but unused",
      "validation": {
        "third_party": false,
        "disabled_rule": false
      },
      "in_patch": false,
      "is_new": false,
      "validates": true,
      "publishable": false
    },
    {
      "analyzer": "mozlint",
      "level": "error",
      "path": "python/mozlint/test/test_result.py",
      "linter": "flake8",
      "line": 16,
      "column": 25,
      "nb_lines": 1,
      "rule": "E711",
      "message": "comparison to None should be 'if cond is None:'",
      "validation": {
        "third_party": false,
        "disabled_rule": false
      },
      "in_patch": false,
      "is_new": false,
      "validates": true,
      "publishable": false
    }
  ],
  "patches": {}
}
```

**Comment by marco-c** [comment]
The problem is in how we're using parsepatch:
https://github.com/mozilla/release-services/blob/b975ab38c8dcad840cb5b7c68ced9796f9d8c624/src/staticanalysis/bot/static_analysis_bot/revisions.py#L59

For the patch in D11190, `Patch.parse_patch` returns:
```
{
	'python/mozlint/mozlint/result.py': {
		'added': [],
		'deleted': [],
		'touched': [85],
		'new': False
	},
	'python/mozlint/test/python.ini': {
		'added': [10],
		'deleted': [],
		'touched': [],
		'new': False
	},
	'python/mozlint/test/test_result.py': {
		'new': True
	},
	'tools/lint/wpt/wpt.py': {
		'added': [27, 30],
		'deleted': [],
		'touched': [],
		'new': False
	}
}
```

Then we transform this to an object from filename to touched and added lines at https://github.com/mozilla/release-services/blob/b975ab38c8dcad840cb5b7c68ced9796f9d8c624/src/staticanalysis/bot/static_analysis_bot/revisions.py#L59, so clearly `test_results.py` has no lines.

Then, to detect if the issue is in the patch we do:
https://github.com/mozilla/release-services/blob/b975ab38c8dcad840cb5b7c68ced9796f9d8c624/src/staticanalysis/bot/static_analysis_bot/revisions.py#L84

In order to fix this, we should either modify parsepatch to add lines to `added` when a new file is created, or take into account that new files have no `added` lines.

**Comment by sylvestre** [comment]
@calixteman could you please fix that as it seem to be on your side?

**Comment by calixteman** [comment]
With parsepatch the file is detected as new:
``'python/mozlint/test/test_result.py': {
		'new': True
	},``
So in this case every line in the file can be considered as added.
But of course if you absolutely need to have this info then I can add it.

**Comment by marco-c** [comment]
We can either fix it in parsepatch by making it report new lines as added lines, or fix it in the bot by taking into account the `new` attribute.

**Comment by sylvestre** [comment]
Maybe updating the bot is the safest way to do it!

**Comment by marco-c** [comment]
> Maybe updating the bot is the safest way to do it!

It should be more or less the same, or maybe updating parsepatch might be a little safer as it's a really self-contained dependency, while the bot has a lot of dependencies between classes (Revision, Issue, and so on).
Also the `number of analyzed lines` statistics would be wrong if parsepatch doesn't return added lines for new files (unless we read the files in the bot, but this would make the code more complex and basically duplicate an operation that parsepatch is already doing).

**Comment by calixteman** [comment]
I'm fixing it in parsepatch.

**Comment by marco-c** [comment]
@calixteman after fixing parsepatch, we just need to update the parsepatch dependency in the bot and probably add a regression test. Maybe @jankeromnes can help, since IIRC he's written tests about related stuff not so long ago.

**Comment by calixteman** [comment]
I just updated parsepatch on pip:
https://pypi.org/project/parsepatch/
The new version is 0.1.3 and it adds lines for new files by default so except your requirements.txt and your tests, you've nothing to change.
