### ISSUE TITLE
staticanalysis/bot: Extra unreported fixes in clang-format improvement patch

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1697]
**Phabricator URL:** https://phabricator.services.mozilla.com/D12684#310396

**Problem:** The automated review mentions 6 defects reported by `clang-tidy` (none by `clang-format`), but it still provides an improvement patch URL. The patch reformats the lines where other defects have been found.

**Comment by La0** [comment]
Fixed.
