### ISSUE TITLE
Code review bot for ESLint missed trailing white space in new file

### ISSUE THREAD

**Issue by Standard8** [mozilla/release-services#1712]
I was testing the patch for https://phabricator.services.mozilla.com/D12983 (diff 1) locally, and noticed that there's trailing whitespace on line 131 of browser_library_warnOnOpen.js - which is a new file in that patch.

Seeing as ESLint picked that up when run locally, I'd have expected the code review bot to pick that up as well.

**Comment by marco-c** [comment]
This is very similar to #1674, which should have been fixed by #1679.

**Comment by marco-c** [comment]
It looks like the task analyzing that differential timed out: https://tools.taskcluster.net/tasks/E0uJ-4pxSB-UcG3ajk7u4A.

**Comment by marco-c** [comment]
I've retriggered it to see if it was a temporary issue.

**Comment by marco-c** [comment]
Not sure what's wrong with this task, but I don't seem to be able to retrigger it successfully. Anyway, I think this was an intermittent issue, feel free to reopen if it happens again.
