### ISSUE TITLE
staticanalysis/frontend: Dashboard wrongly says "No issues!"

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1720]
When opening:

https://static-analysis.moz.tools/#/task/cx-rHe9xSvahlfGnvIl5_Q

you'll see `Loading report...`, and then `No issues!`.

However, by opening the devtools, you'll see that it fetches this report:

https://taskcluster-artifacts.net/cx-rHe9xSvahlfGnvIl5_Q/0/public/results/report.json

which contains 148 issues.

Maybe the `report.json` format has changed?

**Comment by La0** [comment]
Seems fixed.
