### ISSUE TITLE
staticanalysis/bot: before/after sometimes decides an issue `is_new` when it's not

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1722]
In the following analysis task:

https://tools.taskcluster.net/groups/Is-U5PvZQ4y35jUEef7Oig/

We can see (in [report.json]()) that analysis found the following issue:

```json
{
  "analyzer": "clang-tidy",
  "path": "js/src/jsapi.cpp",
  "line": 121,
  "nb_lines": 1,
  "char": 1,
  "check": "google-global-names-in-headers",
  "type": "warning",
  "message": "using declarations in the global namespace in headers are prohibited",
  "body": "\nusing JS::AutoStableStringChars;\n^",
  "reason": null,
  "notes": [],
  "validation": {
    "publishable_check": false,
    "third_party": false,
    "is_expanded_macro": false
  },
  "in_patch": false,
  "is_new": true,
  "validates": false,
  "publishable": false
}
```

Notice that `is_new` is `true`.

However, in [live.log](https://taskcluster-artifacts.net/Is-U5PvZQ4y35jUEef7Oig/0/public/logs/live_backing.log), we can see that analysis found this issue both **before**:

```
[...]
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-build-using-namespace js/src/jsapi.cpp 110:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 110:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 112:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 113:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 114:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 116:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 117:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 118:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 119:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] readability-implicit-bool-conversion js/src/jsapi.cpp 375:10
[...]
```

and **after**:

```
[...]
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-build-using-namespace js/src/jsapi.cpp 115:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 115:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 117:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 118:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 119:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 121:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 122:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 123:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] google-global-names-in-headers js/src/jsapi.cpp 124:1
static_analysis_bot.clang.tidy: Found in-tree code issue [warning] bugprone-suspicious-missing-comma js/src/jsapi.cpp 132:3
[...]
```

So why does it say that the issue is new?

Note, here is `is_new` for all the other `google-global-names-in-headers` issues:

- `115: is_new = true`
- `117: is_new = false`
- `118: is_new = false`
- `119: is_new = false`
- `121: is_new = true`
- `122: is_new = true`
- `123: is_new = true`
- `124: is_new = true`

**Comment by jankeromnes** [comment]
I suspect that the heuristic is thrown off by the changing line numbers:

Maybe it considers 117, 118 and 119 as *not* new, because the same issue existed before and after, on the same line.

However, as we can see in the example, all "after" lines have been incremented by 5. Tracking added/removed lines in the heuristic would probably make it much better.

**Comment by marco-c** [comment]
The heuristic should be resistant to lines moving, it creates an hash of the contents of the lines after ignoring white space changes.

https://github.com/mozilla/release-services/blob/43b84ba4807c81e1eb10891050e82ffa27c7bb1c/src/staticanalysis/bot/static_analysis_bot/__init__.py#L47

There must be some mistake somewhere, as theoretically it should work.

**Comment by jankeromnes** [comment]
Thanks for the pointer! I'm also copying a useful excerpt from IRC:

> 15:05:15 marco> best way to debug this is to add some logging in those two functions
> 15:05:24 marco> __hash__ and build_lines_hash
> 15:05:35 marco> and see why for a BEFORE issue and for an AFTER issue the hash is different

Let's try to debug this.

**Comment by jankeromnes** [comment]
Here are the hashes **before**:

- TODO

And the hashes **after**:

- js/src/jsapi.cpp 115:1
  - content: 'using namespace js;\n'
  - hash: 7132762609209277246
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "da1c3e1d96d25fa4aa2737a50830b514242beefef01a51178594bc1203909e90"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 117:1
  - content: 'using mozilla::Maybe;\n'
  - hash: -8476859607231312330
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "c2bc74cd17f6e452078b35ff8eeb206e946b78e5213459a8276169fbd9cbcb28"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 118:1
  - content: 'using mozilla::PodCopy;\n'
  - hash: -5194419984576085445
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "eac3449f2aa7d779ea18b920ff5ef4216fc17dafbc06b82a01e278435749503f"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 119:1
  - content: 'using mozilla::Some;\n'
  - hash: -7206976740688316400
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "c39a562786e914babcca83f3145d5ba514a05305d4a41b58073073b454dc5b50"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 121:1
  - content: 'using JS::AutoStableStringChars;\n'
  - hash: -8670201117344823670
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "95fe2c900cb728ae8002c0df0c9559ea076b6b4b7b3ae667711a3dc442193488"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 122:1
  - content: 'using JS::CompileOptions;\n'
  - hash: -7183649478631043568
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "27e86ae2f0272d825f7774b0ceddd1bbed66c2805b3742a30292123e8a432db9"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 123:1
  - content: 'using JS::ReadOnlyCompileOptions;\n'
  - hash: 8207118118802874974
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "3eca5f13e90b0bb0570b4a07f1234a79dd429802911b1b5cd414882b87366152"
    - path: "js/src/jsapi.cpp"
    - type: "warning"
- js/src/jsapi.cpp 124:1
  - content: 'using JS::SourceText;\n'
  - hash: -41057799915944244
  - hash_payload:
    - char: 1
    - check: "google-global-names-in-headers"
    - class: "ClangTidyIssue",
    - lines_hash: "6f34af40df00cba016b28b27eabe58c291099bbc119dc49574613bff76bb0192"
    - path: "js/src/jsapi.cpp"
    - type: "warning"

**Comment by marco-c** [comment]
> Hmm, in conclusion, the hashes look ok and should produce the expected result. The bug might be somewhere else.

Good, so if we can rule out the hashes, there is less places where the bug could be.

**Comment by marco-c** [comment]
The failure is likely here:
https://github.com/mozilla/release-services/blob/43b84ba4807c81e1eb10891050e82ffa27c7bb1c/src/staticanalysis/bot/static_analysis_bot/workflow.py#L228

before_patch is a list of issues, and Python should use this function to check if two issues are equal:
https://github.com/mozilla/release-services/blob/43b84ba4807c81e1eb10891050e82ffa27c7bb1c/src/staticanalysis/bot/static_analysis_bot/__init__.py#L44

Maybe this is not fully correct? You could try to write a simple reproduction case for a "mock" class instead of Issue

**Comment by marco-c** [comment]
```Python
class Issue():
    def __init__(self, name):
        self.name = name

    def __eq__(self, other):
        return self.__hash__() == other.__hash__()

    def __hash__(self):
        return hash(self.name)


issue1 = Issue('marco')
issue2 = Issue('marco')
issue3 = Issue('janx')

lst = [issue1, issue3]

print(issue1 == issue2)
print(issue1 == issue3)

if issue1 in lst:
    print('issue1 in lst')

if issue2 in lst:
    print('issue2 in lst')

if issue3 in lst:
    print('issue3 in lst')
```
outputs:
```
True
False
issue1 in lst
issue2 in lst
issue3 in lst
```

So it should be correct.

**Comment by jankeromnes** [comment]
Hmm, the issue actually doesn't even reproduce for me locally. :confused: 

Attempting a new validation run, with debug logs, both on staging ([LcptlLJrQMOj-rd1s_9zXA](https://tools.taskcluster.net/groups/LcptlLJrQMOj-rd1s_9zXA)) and locally.
