### ISSUE TITLE
Python 3.6 as minimum version

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1732]
Even though #867  switched all projects to python 3.6, `mapper/api` fails when trying to build `cli_common` using an f-string ([example build failure](https://tools.taskcluster.net/groups/C6f3WnSVR-SbzEZWuwOn_g/tasks/PG5ydcTLRUaJtC84fBk9DA/runs/0/logs/public%2Flogs%2Flive.log))

@garbas @rail Is there a reason why `mapper/api` is using Python 3.5 ?

**Comment by rail** [comment]
Probably because we didn't update the deps. I'm not aware of anything that would block it.

**Comment by garbas** [comment]
this is happening in #1730 

mapper/api needs an update of pypi2nix to make this work

**Comment by garbas** [comment]
also i'm updating all packages to 3.7 and lets see if this works
