### ISSUE TITLE
Problem with an automated review: Third party webrtc.org code is being reviewed

### ISSUE THREAD

**Issue by dminor** [mozilla/release-services#1735]
**Phabricator URL:** https://phabricator.services.mozilla.com/D13839

**Problem:** We shouldn't be running reviewbot on third party code, e.g. our in tree copy of webrtc.org as is the case here.

**Comment by La0** [comment]
You are totally right, we already do this for `clang-tidy` and `mozlint` issues, the check was not implemented for `clang-format`.
