### ISSUE TITLE
staticanalysis/bot: Artifact already exists, with different contentType or error message

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1747]
Example failed Task: https://tools.taskcluster.net/groups/Rz1j8igjSDG6KxtyWB1q1w/

Error:

> b'[\'Static analysis failure (revision=PHID-DIFF-my7st3qwentekw7m5aly error=TaskclusterRestFailure(\\\'Artifact already exists, with different contentType or error message\\\\n\\\\nExisting artifact information: {\\\\n  "storageType": "blob",\\\\n  "contentType": "text/plain; charset=utf-8",\\\\n  "expires": "2019-01-11T11:45:14.610Z"\\\\n}\\\\n\\\\n---\\\\n\\\\n* method:     createArtifact\\\\n* errorCode:  RequestConflict\\\\n* statusCode: 409\\\\n* time:       2018-12-13T11:45:15.943Z\\\'))\']'

STR:

1. Deploy `master` (including 3ee50c9cdd4df8948fb8b59f561a5a75d6227277) to `staging`
2. Upload two [bad](https://github.com/jankeromnes/gecko-dev/commit/2fb98e0f1aa7a76e07732c2e22063515c3fbbab6) [patches](https://github.com/jankeromnes/gecko-dev/commit/9ff258a75d1b267c769d0bbb675411d6ab965713) to Phabricator-dev
3. Watch some analysis tasks fail with this error

**Comment by jankeromnes** [comment]
Cc @La0

**Comment by La0** [comment]
I'll try to fix this tommorow or next week.
I think adding a unique element to the artifact name would solve this.

Le jeu. 13 déc. 2018 à 15:45, Jan Keromnes <notifications@github.com> a
écrit :
