### ISSUE TITLE
staticanalysis/bot: Assert the repository is in a clean state when hashing code lines (before/after)

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1759]
Following up on #1745, it would be great to assert that the repository is in a clean state when building an Issue's `line_hash`.

This could help prevent hashing code that has been modified (e.g. by another analyzer), thus altering an Issue's hash and causing false positives or false negatives in a before/after analysis.

**Comment by La0** [comment]
Outdated
