### ISSUE TITLE
shipit_frontend: Display concerned release next to the patches

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#177]
Not every patch attached to an uplift request on bugzilla is linked to all concerned releases.
So we need to display the concerned releases next to each patch + their merge status.

**Comment by La0** [comment]
Turns out it's more complicated than i thought, as libmozdata gets data directly from revisions, not from attachments. Need to discuss this with Calixte & marco later next week

**Comment by rail** [comment]
Project renamed, let's close the bugs
