### ISSUE TITLE
Pulse listener is broken on staging because it can't access `exchange/taskcluster-queue/v1/task-group-resolved` exchange

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1779]
aioamqp.exceptions.ChannelClosed: (403, "ACCESS_REFUSED - access to exchange 'exchange/taskcluster-queue/v1/task-group-resolved' in vhost '/' refused for user 'releng-services-staging'")

CC @La0

**Comment by marco-c** [comment]
On production instead it is failing with:
> 2019-01-08T22:47:20.913800+00:00 app[worker.1]: aioamqp.protocol: Connection lost exc=BrokenPipeError(32, 'Broken pipe')

**Comment by marco-c** [comment]
It's possible that the update to aioamqp 0.12.0 broke this on staging. Not sure why it's failing on production.

**Comment by marco-c** [comment]
Ah maybe we're using 0.12.0 too on production? @La0 do you recall exactly what revision we released on prod?

**Comment by La0** [comment]
Last version deployed should be the release one ([Taskcluster deployment task](https://tools.taskcluster.net/groups/BZQ5o57mSmmkFHQNX3FqZw/tasks/Qgl31c0TTcWsq30eg4_HVQ/details) shows commit `62d1a69b098073ced1dd9fb28004a19ad8d6892c` was used).

At this revision, pulse listener uses [aioamqp==0.11.0](https://github.com/mozilla/release-services/blob/62d1a69b098073ced1dd9fb28004a19ad8d6892c/src/pulselistener/requirements_frozen.txt#L1)

Maybe we should freeze this version on staging & see if that works again. This bug should be reproducible locally.

**Comment by marco-c** [comment]
@La0 remember that we released manually in December?

**Comment by marco-c** [comment]
I found the manual deployment task, the GitHub commit hash is a34d3c34f6eb006c347a735e7f1d653971bf6f0e.

**Comment by marco-c** [comment]
So, the version of aioamqp is the same between staging and production, 0.12.0, https://github.com/mozilla/release-services/blob/a34d3c34f6eb006c347a735e7f1d653971bf6f0e/src/pulselistener/requirements_frozen.txt#L1.

Maybe the problem is coming from the server side?

**Comment by La0** [comment]
It's weird that we don't have the same error message then.

Totally forgot about the manual release !

**Comment by marco-c** [comment]
It's failing when declaring the exchange at: https://github.com/mozilla/release-services/blob/a1e608f01c63e573fc821e2eb6a756168c206f4a/lib/cli_common/cli_common/pulse.py#L50

**Comment by marco-c** [comment]
Turns out this was introduced with https://github.com/mozilla/release-services/pull/1777.

I've removed that line in https://github.com/mozilla/release-services/pull/1784 but not merging it yet as @garbas is going to look into the failure.

In the meantime, we should not update staging as otherwise we'd break code coverage on staging.

**Comment by garbas** [comment]
@marco-c to disable some project being deployed you can disable it in `src/please_cli/please_cli/config.py`

**Comment by marco-c** [comment]
@garbas the problem is that I can't stop it being deployed as I need to validate other stuff on staging.
