### ISSUE TITLE
shipit_frontend: Remove immediately the uplift request bug once approved/rejected

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#178]
Right now the bug just display the updated status, but this is not easily visible.
2 solutions:
 * Display a message after approval / rejection to the user and remove the bug from the list (the backend should also flag or delete the bug from database)
 * Use 2 sections on the page, one for nominated bugs (on top), another for approval/rejections (also a flag on backend).

**Comment by rail** [comment]
Project renamed, let's close the bugs
