### ISSUE TITLE
Replace % operator and `.format` with Python 3's f-strings

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1792]
Instead of `'%s is my name' % name` or `'{} is my name'.format(name)`, we should use the much more readable `f'{name} is my name'`.

**Comment by rv404674** [comment]
@marco-c  i am on it. :)

**Comment by Utkarsh1308** [comment]
Can I take this issue if someone else is not working on it?

**Comment by marco-c** [comment]
@Utkarsh1308 there is already a PR that is fixing this.
