### ISSUE TITLE
Create new 'OS Symbols' project, migrating code from the previous repos

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1799]
This is marked as a good first bug, but it is a pretty involved project, even though self-contained enough.
**If you have never contributed before, I suggest looking at a different good first bug.**

We should migrate the code from https://github.com/marco-c/breakpad-mac-update-symbols and https://github.com/marco-c/breakpad-win-update-symbols to release-services, as it would make maintenance much less expensive (most of the taskcluster code could be removed, by relying on release-services existing libs and tools).

**Comment by marco-c** [comment]
My idea for the architecture of this:
- os_system/trigger will be a project running with a Taskcluster hook daily, which will trigger os_system/win and os_system/mac tasks, and os_system upload tasks depending on the first two;
- os_system/win will be a task fetching symbols from Microsoft;
- os_system/mac will be a task fetching symbols from Apple;
- os_system/upload will be a task uploading symbols to symbols.mozilla.org.

All of these are "bot" projects, because they don't need a backend or a frontend.

os_system/trigger corresponds to https://github.com/marco-c/breakpad-win-update-symbols/blob/d3774b678e542a3a6e0a7c808c257724fc2947f6/hook.json and https://github.com/marco-c/breakpad-mac-update-symbols/blob/4267a6dd501dccb86def7da2391d85818ccad8f8/hook.json.
os_system/win corresponds to https://github.com/marco-c/breakpad-win-update-symbols/blob/d3774b678e542a3a6e0a7c808c257724fc2947f6/fetch-task.json.
os_system/mac corresponds to https://github.com/marco-c/breakpad-mac-update-symbols/blob/4267a6dd501dccb86def7da2391d85818ccad8f8/fetch-task.json.
os_system/upload corresponds to https://github.com/marco-c/breakpad-win-update-symbols/blob/d3774b678e542a3a6e0a7c808c257724fc2947f6/upload-task.json and https://github.com/marco-c/breakpad-mac-update-symbols/blob/4267a6dd501dccb86def7da2391d85818ccad8f8/upload-task.json.

**Comment by MatheshShan** [comment]
Hi, I'm interested in this job.
Would you explain me  what to be done exactly , As I'm new to this .
if you give me some guidance it will be better for me  to complete this work.

**Comment by marco-c** [comment]
Hello @MatheshShan, this is not really a good first bug to start with, as it is pretty complex. I'd suggest looking at another one.

**Comment by MatheshShan** [comment]
okie Thank you @marco-c

**Comment by pgadige** [comment]
I'm working on it. I'm familiar with [Taskcluster](https://tools.taskcluster.net/) tool, specifically with creating tasks, hooks and managing secrets.

I'm starting with setting up of `os_system/trigger` project. I'll refer to one of the existing bot projects to get an idea for an outline.

I'd like to write up a design doc so @marco-c can review it and give feedback.
