### ISSUE TITLE
Problem with an automated review: reviewbot complains about clang-format ignored files

### ISSUE THREAD

**Issue by froydnj** [mozilla/release-services#1817]
**Phabricator URL:** https://phabricator.services.mozilla.com/D17252

**Problem:** `reviewbot` complained about the style in patched files:

https://phabricator.services.mozilla.com/D17252#439670

But the files in those directories are deliberately ignored during clang-format:

https://searchfox.org/mozilla-central/rev/6c784c93cfbd5119ed07773a170b59fbce1377ea/.clang-format-ignore#52

`reviewbot` should not complain about such files.

**Comment by abpostelnicu** [comment]
Thanks for reporting this, this issue is related with https://github.com/mozilla/release-services/issues/1815
I’m aware why this happens and we will have a fix for this shortly.

**Comment by La0** [comment]
@abpostelnicu Is this fixed ?

**Comment by abpostelnicu** [comment]
Ye, it is.
