### ISSUE TITLE
trychooser allows to make invalid try syntax

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/release-services#1822]
STR
===

- select any kind of build
- select `all` in the platforms
- add `win64 code coverage` to the platforms

Observed
===

The generated try line is: `try: -b do -p all,win64-ccov -u none -t none`, which is not valid.

For instance: https://treeherder.mozilla.org/#/jobs?repo=try&revision=d975fd252168a5ad309beac3cacbadb2870a4c07&selectedJob=223714228

See the code parsing the try syntax, special-casing `all`: https://searchfox.org/mozilla-central/source/taskcluster/taskgraph/try_option_syntax.py#330

**Comment by garbas** [comment]
@bclary trychooser via the web is slowly going to be deprecated (i was told) and i'm only doing the minimal maintenance until then (eg. if you have a patch I'll review and merge it). I would suggest to try to use `./mach try chooser` which is suppose to supersede this version of trychooser.

**Comment by bclary** [comment]
I think you meant to address @bnjbvr and either mach try chooser to mach try fuzzy which is my go to solution these days. ;-)
