### ISSUE TITLE
Issue to track out of band releases

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1825]
Since we have forgotten about them in the past, we can use this issue to track out of band releases.

Edit this comment adding a row like:
PUSH DAY - PUSHED COMMIT - PUSHED PROJECT(S) - PREVIOUS RELEASED COMMIT

**Comment by abpostelnicu** [comment]
25/Jan/2018 - Add LLVM_OBJDUMP to geckoenv. (#1824) - staticanalysis/bot - 2e1a9647f49112aa853cb82aeb097d72edea0681

**Comment by marco-c** [comment]
We're not really doing this so often anymore.
