### ISSUE TITLE
Long delay between a diff being submitted and review bot comment

### ISSUE THREAD

**Issue by jyavenard** [mozilla/release-services#1846]
Today I submitted a new diff to phabricator at 11:27AM.

The bot added comments about lint errors at 3:53PM only.

4h26m to get an otherwise very useful comment is too long.

I personally relies on the autobot to make those checks.

https://phabricator.services.mozilla.com/D18762

**Comment by La0** [comment]
Hello Jean Yves,

Unfortunately, the review bot [taskcluster task](https://tools.taskcluster.net/groups/CJA-1WCjR1OxvogZoiOwJg/tasks/CJA-1WCjR1OxvogZoiOwJg/details) for the first diff `PHID-DIFF-e7gqgedrgr62jyqvqs6x` on this revision failed (certainly a worker failure, as the task is in exception, not failed state)

Only the second diff `PHID-DIFF-cbxjy367kjaftco6bbot` got [analyzed all the way through](https://tools.taskcluster.net/groups/B0AzQq74TEqsvzZ2RkMpqA/tasks/B0AzQq74TEqsvzZ2RkMpqA/runs/0/logs/public%2Flogs%2Flive.log) and reported the 2 issues.

I'm working on enhancing the reliability of the review bot, and will try to fix this kind of exceptions ASAP. 
Ssorry you got this issue :disappointed:

**Comment by marco-c** [comment]
We can close as a duplicate of #704.
