### ISSUE TITLE
Problem with an automated review: Review message should indicate which diff it applies to.

### ISSUE THREAD

**Issue by glandium** [mozilla/release-services#1848]
**Phabricator URL:** https://phabricator.services.mozilla.com/D18807

**Problem:** The review message should indicate which diff it applies to. In this case, I ran clang format between the first and the second diffs attached to the revision, but before the bot said anything, so I guess the review applies to the first. But it should be clearer.

**Comment by sylvestre** [comment]
Yeah, instead of having
`Code analysis found 1 defect in this patch:` 
we could have
`Code analysis found 1 defect in this patch (Diff 104147):`

Would be much more clear
