### ISSUE TITLE
staticanalysis/bot: Update the integration of static analyzers in order to be more scalable

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla/release-services#1850]
We want our static-analysis framework to be very salable and easy to work on, right now it's very hard to match a static-analyzer for a build target, please see the integration of [infer](https://github.com/mozilla/release-services/commit/689fbdae1de6996f6dd2b3968de72905ac36c167#diff-1a2788e1cef7cfddcdac0370d5c01d7a) that looking back on it it's sub-optimal and in the context where we also add [coverity](https://github.com/mozilla/release-services/pull/1849), in the first place for ```C/C++``` and later on for ```Java``` and ```JavaScript``` we must provide a mechanism where we create build targets associated with analyzers.

**Comment by La0** [comment]
I think it's now outdated since the move to Try.
What do you think @abpostelnicu @marco-c ?

**Comment by abpostelnicu** [comment]
Since we've moved to try this is no longer a concern for us.
