### ISSUE TITLE
Tag docker images with channel names

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1856]
Currently the images published (on docker hub) through skopeo are [only tagged with their hash](https://github.com/mozilla/release-services/blob/b8801a184d158f0c883dcdd1ff6b4871b538c71a/lib/please_cli/please_cli/deploy.py#L475) which makes it impossible to use outside of release-services.

As we need to use the `staticanalysis/bot` image from the try taskgraph, a pinned version is mandatory to avoid updating constantly the in-tree description.

For example, a staging push would produce the following tags for `staticanalysis/bot`:
- `mozillareleng/services:docker-image-python3.7-mozilla-staticanalysis-bot-1.0.0-abcdef12345` - which is currently implemented
- `mozillareleng/services:staticanalysis-bot-staging` - using the project name and current channel

**Comment by rail** [comment]
You can specify `docker_stable_tag` in your config to do that, like [here](https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/config.py#L904). Is this what you were looking for?

**Comment by La0** [comment]
Thank you @rail ! I did not know this existed, neither @marco-c i think.

I'll make a simpe PR to add these tags to staticanalysis/bot before the next release

**Comment by rail** [comment]
\o/
less bugs is better :)
