### ISSUE TITLE
staticanalysis/bot: max_comments in build_comment seems unused

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1873]
CC @La0 were we using it in the past and not using it anymore? Can we remove it?

**Comment by La0** [comment]
I think it was a reviewboard requirement. We can remove it

**Comment by amey-kudari** [comment]
Can i try solving this? This will be my first actual bug, can you please guide me?

**Comment by marco-c** [comment]
Sure, you can pick it up.
It's a really simple bug, you just need to remove max_comments parameter and its usage from the build_comment function.

**Comment by amey-kudari** [comment]
done, i removed the if statement, and that parameter.

**Comment by marco-c** [comment]
Fixed by https://github.com/mozilla/release-services/pull/1875.
