### ISSUE TITLE
Coverity posts pre-existing issues unrelated to the patch

### ISSUE THREAD

**Issue by jandem** [mozilla/release-services#1885]
**Phabricator URL:** https://phabricator.services.mozilla.com/D19760

**Problem:** I'm all for static-analysis, but when a file has pre-existing issues reporting them on every revision that touches this file gets very noisy very fast :)

**Comment by sylvestre** [comment]
Yeah, this is a bug, should be fixed today or tomorrow

**Comment by abpostelnicu** [comment]
Hello Jan,

Thank for reporting this issue and I'm sorry you're having this bad experience, I'm aware of the issue and we have a fix for it [#1884](https://github.com/mozilla/release-services/pull/1884).

**Comment by jandem** [comment]
Fantastic! Thanks to both of you :)

**Comment by sylvestre** [comment]
One more occurrence: https://phabricator.services.mozilla.com/D19779

**Comment by abpostelnicu** [comment]
We’ve pushed the fix to the testing environment. Tomorrow we will push it in production.

**Comment by marco-c** [comment]
And in the meantime I've disabled Coverity on production.

**Comment by abpostelnicu** [comment]
Production has been redeployed with the fix and Coverity has been re-enabled.

**Comment by jandem** [comment]
I'm seeing this behavior again, for example https://phabricator.services.mozilla.com/D31038#912541

Is this expected or a bug?

**Comment by La0** [comment]
It's now expected, as we publish Coverity issues for any modified files in a patch (an issue introduced by a patch may be detected at some other place by Coverity).
