### ISSUE TITLE
Export phabricator numerical diff id in Taskcluster payload

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1921]
Only the `diff_phid` is exported, but it's not really user friendly in the dashboard as we only see the numerical id.

The patch is easy: add `diff_id: self.diff_id` in the `as_dict` method of `PhabricatorRevision` in `src/staticanalysis/bot/static_analysis_bot/revisions.py` and fix unit tests

Bonus point for displaying it in the staticanalysis frontend

**Comment by rv404674** [comment]
I am interested in doing it. Can I take it as well @La0

**Comment by La0** [comment]
Sure.
