### ISSUE TITLE
Get failed status when tasks get killed by Taskcluster

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1927]
We show an invalid status `started` when tasks fail during the clone and get killed by Taskcluster.
The taskcluster index is not updated, so it stays in its initial place.

I think it's almost impossible to fix in the task code, but we could update the index from pulselistener in that case.

Suggestions welcome.

**Comment by marco-c** [comment]
We could consider tasks in starting state which have been there for more than a few hours as failed.

**Comment by La0** [comment]
That would be an easy solution to implement. It could even be done at the frontend level, without impacting the index (even though i would prefer the index update)
