### ISSUE TITLE
user picture does not show up on ship it

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#1962]
I see alt text instead of my picture:
![Screenshot_2019-03-18 Ship-it ](https://user-images.githubusercontent.com/49649/54550188-ee5a1280-4981-11e9-9686-510f3bc7c162.png)

The image source points at https://s.gravatar.com/avatar/2bb0ca53105183631a435b12682ef49e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fbh.png, which loads fine. I thought it might be related to Content Blocking, but even with that off it appears to still be an issue.

**Comment by rail** [comment]
Smells like a content blocking issue... Do you have anything that would block the picture from loading?

**Comment by rail** [comment]
Maybe something in the console?

**Comment by mozbhearsum** [comment]
It looks like it's something configured by the site. I have this in the console:
 Content Security Policy: The page’s settings blocked the loading of a resource at https://i2.wp.com/cdn.auth0.com/avatars/bh.png?ssl=1 (“img-src”).

I also have this, but I don't think it's relevant (and the problem still occurs with content blocking disabled):
 Request to access cookie or storage on “https://s.gravatar.com/avatar/2bb0ca53105183631a435b12682ef49e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fbh.png” was blocked because it came from a tracker and content blocking is enabled.

**Comment by rail** [comment]
Ohhh, interesting, https://i2.wp.com/cdn.auth0.com/avatars/bh.png?ssl=1 is the final url and it's not whitelisted. For some reason gravatar redirects to this resource.
