### ISSUE TITLE
Replace type by level in ClangTidyIssue

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1980]
As `type` is a reserved keyword in Python, it makes sense to rename all occurences of `ClangTidyIssue.type` to `ClangTidyIssue.level`.
Please take care to also fix the unit tests.
Bonus: make a PR for the staticanalysis/frontend which use the type information in the `Tasks.vue`

**Comment by risingsmoke** [comment]
Hey can I work on this?
I understand that the PR should include changes to this file:
[https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/static_analysis_bot/clang/tidy.py](url)
along with changing all the references of `type` in the code base.
Do correct me if I am missing something.

**Comment by La0** [comment]
That's it ! You'll need to run the setup to test your modifications https://docs.mozilla-releng.net/develop/contribute.html

```
./please check staticanalysis/bot
```

**Comment by risingsmoke** [comment]
Nice. I will do that then. Thanks.

**Comment by risingsmoke** [comment]
I am facing a issue similar to one mentioned in this: [https://github.com/mozilla/release-services/issues/1027](url). 
My stdout looks as follows: [https://paste.ofcode.org/HWRpwARs9BnHXJBWv6DdiA](url)
Should I make an account as mentioned in the above issue in Task Cluster?

**Comment by La0** [comment]
You can create an account on Taskcluster, then add your credentials to the project using:

```
./please tools signin
```

**Comment by risingsmoke** [comment]
Cool. I also found the page in the documentation page you shared: [https://docs.mozilla-releng.net/projects/staticanalysis-bot.html](https://docs.mozilla-releng.net/projects/staticanalysis-bot.html)
Guess, I should have looked more. 
Thanks!

**Comment by risingsmoke** [comment]
So, I was able to signin and follow the same steps mentioned in [https://github.com/mozilla/release-services/issues/1027](https://github.com/mozilla/release-services/issues/1027). But I am facing the same issue: `Missing value NIX_CACHE_SECRET_KEYS in secrets`.
The stdout is as follows: [https://paste.ofcode.org/3ttEmtz4YTYMBhjN9rtZeX](https://paste.ofcode.org/3ttEmtz4YTYMBhjN9rtZeX).
Did I miss anything else in setting up the environment?

**Comment by risingsmoke** [comment]
I was able to successfully run `./please check staticanalysis/bot` after I adding `NIX_CACHE_SECRET_KEYS` with `[]` under common of the secrets configuration yaml, following #1027 
After running, I got a `DONE`.
Please let me know if I am missing anything.

**Comment by La0** [comment]
No it's all right. When you do your modifications, if a check fails it will be shown in this command.

You can also do:

```
./please shell staticanalysis/bot
pytest
flake8
```

To get more output

**Comment by shahidikram0701** [comment]
Hi,
I'm a newbie here and was looking forward to start contributing to open-source. If this issue isnt handled yet, Can I take it up?

**Comment by risingsmoke** [comment]
@La0 
I made a pull request for this issue. Can you check and let me know if it needs anymore changes?

**Comment by La0** [comment]
Thank you @risingsmoke, i've made some comments in the PR.

Sorry @shahidikram0701, this issue is already being worked on. You can lookup other [good-first-bug issues](https://github.com/mozilla/release-services/labels/skill%3Agood-first-bug)

**Comment by shahidikram0701** [comment]
@La0 Sure, Thanks I'll check out other issues!

**Comment by risingsmoke** [comment]
@La0 I made the necessary changes to the pull request, my while running `./please check staticanalysis/bot` the build fails with the following stderr: [https://paste.ofcode.org/VCuUWharWmssZuUQkPYRc9](https://paste.ofcode.org/VCuUWharWmssZuUQkPYRc9)
Can you take a look?

**Comment by risingsmoke** [comment]
@La0 I have updated the pull request, can you review? I have checked that all the tests have passed. let me know if I have missed anything else.

**Comment by La0** [comment]
The `staticanalysis/bot` side is now merged, a simple patch is now needed on `staticanalysis/frontend` to use the level variable

**Comment by risingsmoke** [comment]
I am a bit unfamiliar with the javascript part actually, If you can guide me how `ClangTidyIssue` is being referenced in `Tasks.vue`, I can make a change for the Bonus part as well.

**Comment by La0** [comment]
I checked the frontend project, and there is no need for changes !
The [existing tests](https://github.com/mozilla/release-services/blob/master/src/staticanalysis/frontend/src/Task.vue#L180) already support `level`.

Thanks @risingsmoke, i'm closing this issue.
