### ISSUE TITLE
HarborMaster WebHook support

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1989]
Pulselistener needs to listen on an HTTPS endpoint for incoming requests from HarborMaster.
Each request will have a diff phid and build target phid and must trigger a push to try.

**Comment by marco-c** [comment]
This will also fix the problem where we can miss some revisions because of race conditions when polling (when a revision is just created and is in the secure state and before turning into the visible state).

**Comment by La0** [comment]
This is blocking the [creation of a production build plan](https://bugzilla.mozilla.org/show_bug.cgi?id=1539745).

The endpoint must be a POST endpoint, supporting PHID query parameters:

* `build`
* `diff` the target Differential diff
* `target` as the Harbormaster build target
* `repository`

It can also support basic HTTP authentication
