### ISSUE TITLE
PERFHERDER record has bad form

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/release-services#2014]
The PERFHERDER record has extra ` (timestamp='2019-04-01 04:03:04')` appended to the line

Example (search for `"vcs"`)

```
static_analysis_bot.workflows.local: clone: PERFHERDER_DATA: {"framework": {"name": "vcs"}, "suites": [{"extraOptions": ["c5.xlarge"], "lowerIsBetter": true, "name": "clone", "shouldAlert": false, "subtests": [], "value": 541.6883771419525}, {"extraOptions": ["c5.xlarge"], "lowerIsBetter": true, "name": "update", "shouldAlert": false, "subtests": [], "value": 462.7900149822235}, {"extraOptions": ["c5.xlarge"], "lowerIsBetter": true, "name": "overall", "shouldAlert": false, "subtests": [], "value": 1005.2304649353027}, {"extraOptions": ["c5.xlarge"], "lowerIsBetter": true, "name": "overall_clone", "shouldAlert": false, "subtests": [], "value": 1005.2304649353027}, {"extraOptions": ["c5.xlarge"], "lowerIsBetter": true, "name": "overall_clone_fullcheckout", "shouldAlert": false, "subtests": [], "value": 1005.2304649353027}]} (timestamp='2019-04-01 04:03:04')
```
example file

https://taskcluster-artifacts.net/EzAU4HM5QQyZRseFSXKNzQ/0/public/logs/live_backing.log

might be related to 

https://bugzilla.mozilla.org/show_bug.cgi?id=1540259

**Comment by La0** [comment]
The timestamp is automatically added by our logger.

We didn't log the robustcheckout output until a few weeks. Do you need this record to be displayed in a specific form ?

**Comment by marco-c** [comment]
@klahnakoski what are you using this data for?

**Comment by klahnakoski** [comment]
gps used it to get median timings for a number of measures in the "vcs" framework. Catlee was also looking into it, presumably to find optimization opportunities in taskcluster; he noticed that the windows records were not in ActiveData.  I use the "perf" table to report the new platforms (and therefore signatures to expect out of perfherder)

**Comment by klahnakoski** [comment]
The PERFHERDER record is in fine form, just that it should be on its own line.

This is not a problem for ingestion; it already looks for this timestamp suffix and removes it.  I only bring this up in case others may be trying the parse the same.

**Comment by La0** [comment]
I'm closing this as we do not clone anymore.
