### ISSUE TITLE
Provide a failure reason on Phabricator when the static analysis bot fails

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#2050]
Maybe we could (ab)use unit test results, we have to see what the UI would look like.
Otherwise, we'll need upstream support.

The main objective is to show differently failures due to the infra (which developers might want to retrigger), vs failures due to the presence of static analysis issues in a patch.

When we do #1542, a possible retriggerable failure would be the inability to apply the patch.

**Comment by La0** [comment]
This is done :tada:
