### ISSUE TITLE
Code review crash on unsupported file in Phabricator revision

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2062]
Example [1](https://tools.taskcluster.net/groups/VmpRE0GoSsyOuFMNY1Mkyw/tasks/VmpRE0GoSsyOuFMNY1Mkyw/runs/0/logs/public%2Flogs%2Flive.log) & [2](https://tools.taskcluster.net/groups/OLuk0sEHQtOD7R8ApLpDsw/tasks/OLuk0sEHQtOD7R8ApLpDsw/runs/0/logs/public%2Flogs%2Flive.log)

**Comment by marco-c** [comment]
I see some of these are header files, @abpostelnicu did you fix the issue about those?

**Comment by abpostelnicu** [comment]
@marco-c this has only been implemented for ```Coverity```, I will create a separate task for this.

**Comment by La0** [comment]
LInked to #2028.

I'm working on this now as this is the last major source of failed builds
