### ISSUE TITLE
Build clang-format patch

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2065]
The remote workflow does not produce any `clang-format` diff patches anymore.
The `clang-format` task in-tree **only** produces a [JSON payload compatible](https://taskcluster-artifacts.net/IYZkISboR7W8wFcq3tEs3w/0/public/code-review/clang-format.json) with our parser.

As our publication workflow does not produce inline comments for clang-format, and does not produce a patch anymore, nothing is publishable, so [the bot does not publish](https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/static_analysis_bot/report/phabricator.py#L97) any comment when only [clang-format issues are detected on a patch](https://phabricator.services.mozilla.com/D29545). But the build status is `fail` ! 

This patch is also needed for future work on Lando, and should be available as an artifact on our task, and not from the analyzer itself (especially as we would have to run twice clang-format to get both JSON & DIFF outputs).

So we should build the diff version of the json patch in the bot.

**Comment by La0** [comment]
After discussion, it seems better to build the diff in the analyzer, as it takes the same time to build json+diff than just json (configure is reused !).

So i did a [patch in mozilla-central](https://phabricator.services.mozilla.com/D29662) that does just that.

I'm now working on exposing that patch from our own task

**Comment by sylvestre** [comment]
Or we could write a json to diff converter (joking) :)

Le jeu. 2 mai 2019 à 15:33, Bastien Abadie <notifications@github.com> a
écrit :

**Comment by La0** [comment]
In tree patch landed: https://hg.mozilla.org/mozilla-central/rev/f5f8345a5c87
