### ISSUE TITLE
Remove Coverity secret/options

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2082]
And only keep one for full stack

**Comment by abpostelnicu** [comment]
@La0 I would also remove the one for ```full_stack``` and use it only if we have it from the json file.
Also I'm not sure we need to remove coverity auth and the rest that is related to it, what if we want to use the bot for a project that doesn't support try tasks, for example ```NSS```?

**Comment by La0** [comment]
Good idea, remove all the settings, and simply display the stack when available !

Regarding `NSS` & others, we are not there yet, that would need significant work anyway; and we should not run any analyzers in that code base anymore. It's fine to remove the conf now

**Comment by abpostelnicu** [comment]
@La0 is this still something that is actual, since looking around the code I see only `settings.cov_full_stack`. I would remove that as well and if we get the `stack` from `try` then use it.
