### ISSUE TITLE
Big Phabricator stack fail to apply

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2100]
A [revision with a big stack](https://phabricator.services.mozilla.com/D30252?id=103046) fail to apply, pulselistener behaves accordingly and [posts a failed unit test](https://phabricator.services.mozilla.com/harbormaster/unit/view/7081/)

Maybe some landed patches are applied, and give a conflict ?

**Comment by La0** [comment]
The full stack applied cleanly until the last patch. Here is the [papertrail log](https://papertrailapp.com/systems/3be31906-5484-49c0-8049-8055a8cdf77b/events?focus=1064603626456186897)

**Comment by La0** [comment]
The stack is applied on base commit [8c0a7e7ccb508dabf38dd17f66aa93bed01c0754](https://hg.mozilla.org/mozilla-central/rev/8c0a7e7ccb508dabf38dd17f66aa93bed01c0754) as this revision is found as the base of the first patch on Phabricator [PHID-DIFF-mugxlbeyyulfonpdf5gl](https://phabricator.services.mozilla.com/D24988)

But this revision on mozilla-central misses `dom/ipc/BrowserChild.h` that the patch n°19 modifies (hence the build error).

That would imply we do not use the right base revision for that case...

**Comment by marco-c** [comment]
This is a mistake by the developer in the end, as his patch is not based on the right revision.

**Comment by La0** [comment]
Yes and No .... There is no way (that i know of) to update the base revision of the first patch in a stack.
So if you want to keep working on a stack, but your earlier patches land, you can't do much to help us

**Comment by marco-c** [comment]
The right way would be for them to rebase the first patch in the stack that hasn't landed yet on top of latest mozilla-central. They are going to have to do it anyways, as otherwise they won't be able to land the patch.

**Comment by marco-c** [comment]
> The right way would be for them to rebase the first patch in the stack that hasn't landed yet on top of latest mozilla-central

Which they have to do locally too, otherwise their patch won't even build!

**Comment by La0** [comment]
That's exactly what he did (rebase on top of MC). It's just that the bot has **not** that information and use a deprecated information.

@Callek also got bitten by the [same issue here](https://phabricator.services.mozilla.com/D28120)

**Comment by marco-c** [comment]
This seems like an issue in moz-phab then? Why didn't it update the base revision of the patch?

**Comment by La0** [comment]
I made a simple patch that stops loading the stack once a base revision is found in the repository.

The original revision from this issue applies with this patch
