### ISSUE TITLE
Remove bugbug project

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#2110]
It has been moved to a separate repository.

**Comment by La0** [comment]
We could disable the deployment right now, and remove the hooks after next global release. That would really test the migration to the new workflow

**Comment by marco-c** [comment]
Depends on https://github.com/mozilla/relman-auto-nag/pull/661.

**Comment by marco-c** [comment]
https://github.com/mozilla/relman-auto-nag/pull/661 has been merged, so we can now do this.

**Comment by marco-c** [comment]
Fixed by #2119.
