### ISSUE TITLE
Use alternative or no auth for local development

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#212]
When developing locally, it's very inconvenient to need to log in with Taskcluster. Not only does it make it impossible to do testing without an internet connection, it's a huge barrier of entry to contributors, who shouldn't need to go through the process of acquiring special accounts to contribute. In some cases (eg: first time contributors) they may not even be able to login to Taskcluster in any way. In others, they may not have the scopes needed to do testing.

We should have some way of disabling auth or doing it via another means for local development.

**Comment by La0** [comment]
The best way to do that would be to create another auth user model in `lib/releng_common/auth.py` and have some settings redirect the header check from `taskcluster_user_loader`.
You do not want to add complexity to the frontends, but only add a *dummy* authentication mode for development in the backends.

**Comment by mozbhearsum** [comment]
The frontends is what I was mainly concerned with, actually. In my brief local testing yesterday, the backends seemed to work fine without any auth (I was able to get empty JSON data from them, in my cost cases). The frontends refused to show me anything except an empty screen with "Login" in the top right. Am I missing something, or will your proposed solution address that case, too?

**Comment by garbas** [comment]
another solution would be to just package ``login.taskcluster.net``[1](https://github.com/taskcluster/taskcluster-login) and have a dummy instance running in development mode.

**Comment by La0** [comment]
@mozbhearsum Yes my solution would address that case. But shipit_frontend must not show any information right now to anonymous users as security bugs can be read from it in production (only release managers have access to it)

**Comment by mozbhearsum** [comment]
Turns out this is a big pain for apps like shipit_signoff, which use auth0. I pretty much can't do anything with it in local development because I get blocked by the auth decorators.

Can we please prioritize this? Employees can work around this in some cases by logging into the production auth system with their local app, but volunteers are completely out of luck. This is a huge burden to contribution.

**Comment by La0** [comment]
Linked to #786
