### ISSUE TITLE
Stop uploading reports to codecov/coveralls

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#2123]

**Comment by La0** [comment]
When do you want to stop these uploads ? It would remove a lot of code from the bot & backend, only leaving GCP+covdir processing

**Comment by marco-c** [comment]
I think we can stop them when we have a backend/basic frontend that people can use instead of codecov/coveralls.

**Comment by La0** [comment]
Coveralls support removed.

**Comment by La0** [comment]
Done.
