### ISSUE TITLE
Support multiple repositories

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#2152]
In order to extend code review bot across multiple repositories, pulselistener needs to clone multiple repositories, and trigger try jobs on them

**Comment by La0** [comment]
Dev is done, running on testing, not on production yet

**Comment by sylvestre** [comment]
Can i try it yet?

Le mer. 3 juil. 2019 à 09:26, Bastien Abadie <notifications@github.com> a
écrit :

**Comment by La0** [comment]
I'll setup the full environment on testing, right now it's running a different set of PR

**Comment by La0** [comment]
This is done.
