### ISSUE TITLE
Add container for shipit_upliftbot, or kill it

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#216]
The docker-compose being added in #207 doesn't do anything for shipit_upliftbot, because I was told that it might be going away. If it is, this is a no-op. If it's going to continue to exist, we should run it as part of the shipit family of apps. This might not be easy, because part of its job is to make changes to external production servers...so we may need a way to mock those parts out.

**Comment by La0** [comment]
I don't think it will be killed anytime soon, as @sylvestre wants to add more features and even expand towards multiple bots (static analysis, automated merge tests, bugzilla reports through comments, ...).
However, it may evolve into a separate project at some point.
