### ISSUE TITLE
ESLint errors failed to report to Phabricator UI

### ISSUE THREAD

**Issue by Standard8** [mozilla/release-services#2162]
I was applying https://phabricator.services.mozilla.com/D33798 for test locally, and was surprised to see a relatively amount of ESLint failures listed locally.

The link to the source code analysis said that it passed: https://phabricator.services.mozilla.com/harbormaster/build/102283/

However the link to treeherder clearly shows ESLint as failing:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=45fcb0e6e9db380b8aa93170c41403007a4e5b8d

**Comment by La0** [comment]
The eslint task did not produce [a JSON artifact](https://tools.taskcluster.net/groups/KGU9f1UVRW6-5nU0aREmAg/tasks/JRJ8h8uZRqeRibi4s0Jlwg/runs/0/artifacts). There should be a `public/code-review/mozlint.json` here.

Our publication task [detected that the file was missing](https://tools.taskcluster.net/groups/GfnuGQ_tSyyS6VOCWnWZrg/tasks/GfnuGQ_tSyyS6VOCWnWZrg/runs/0/logs/public%2Flogs%2Flive.log#L26), but did not crash.
@marco-c Maybe we should simply crash the review task or post an error on phabricator warning the developer that an analyzer was not processed ?

**Comment by marco-c** [comment]
Why was the artifact missing?
Adding a warning makes sense to me, unless this is a very rare occurrence and we can fix the underlying problem easily.

**Comment by La0** [comment]
I just noticed that the eslint command misses the json output argument on CLI !

It's weird because it's [still present on MC](https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/ci/source-test/mozlint.yml#l81)

This definitely should not happen.

**Comment by marco-c** [comment]
So probably this is just because the patch was based on a old revision of mozilla-central: https://hg.mozilla.org/try/file/45fcb0e6e9db380b8aa93170c41403007a4e5b8d/taskcluster/ci/source-test/mozlint.yml#l68.
