### ISSUE TITLE
Make the Docker dev environment work on Windows

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#218]
I gave this a brief try while testing #207, and hit some issues. I gave up quickly, because I don't know of any current developers who are running Windows. But it's ideal if we don't limit ourselves to only people who run Linux or Mac. Balrog's Docker containers work on Windows, so I suspect we can make this work too.

**Comment by garbas** [comment]
with #928 being merged this is possible by manually running docker command which you can find in `./please` shell script. But to get this really nice we would have to probably create `./please.bat` file and do some powershell magic.

@mozbhearsum do you know somebody who knows a little bit of powershell? I basically need to convert [this](https://github.com/mozilla-releng/services/blob/master/please#L49-L61) to powershell.

**Comment by mozbhearsum** [comment]
I do not.
