### ISSUE TITLE
[shipit] Don't allow promoting the same release twice

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/release-services#2226]
The Firefox `69.0b9` beta release was accidentally promoted twice. Ship It was then in an invalid state, since it was only tracking the second promotion, but the first promotion still existed and was hogging resources. Cancelling the release only cancelled the second graph.

**To reproduce:**
1. Click to promote a release
2. Click "do eet" multiple times
3. Multiple graphs are created

**Expected behaviour:**
* [ ] The server that's receiving the requests shouldn't allow more than one promotion for a release
* [ ] The web frontend should disable the "do eet" button while the request to the server is in-progress

**Comment by mitchhentges** [comment]
@rail or @garbas: could you point me towards docs on getting ship-it running locally?
I have the frontend "running", but what do I need to run the backend/api?
I'm guessing I need to create a postgres database and give shipit access to it? Where is the schema located, or will flask manage that? How do I invoke it, do I just call `shipit_api/__init__.py`? When I do, it complains that `module 'taskcluster' has no attribute '_client_importer'`.

Do we have quick-start dev docs for ship-it?

**Comment by rail** [comment]
there is https://docs.mozilla-releng.net/develop/contribute.html, but it doesn't cover shipit as it shoudl be.

What I usually do is:
* open 3 terminals and in each run the following
1) ./please run postgresql
2) ./please shell shipit/api --taskcluster-client-id=$TASKCLUSTER_CLIENT_ID --taskcluster-access-token=$TASKCLUSTER_ACCESS_TOKEN --taskcluster-secret repo:github.com/mozilla-releng/services:branch:master
3) ./please shell shipit/frontend --taskcluster-client-id=$TASKCLUSTER_CLIENT_ID --taskcluster-access-token=$TASKCLUSTER_ACCESS_TOKEN --taskcluster-secret repo:github.com/mozilla-releng/services:branch:master

The TC credentials should have scopes to read the secret from `repo:github.com/mozilla-releng/services:branch:master`. 

Then I usually go to the API to confirm the self signed cert exception at https://localhost:8015/ and then you can browse the UI at https://localhost:8010/

Most of the changes should trigger autoreload in api and frontend.

Please let me know if this helps.
