### ISSUE TITLE
Removing DATADOG_API_KEY

### ISSUE THREAD

**Issue by srfraser** [mozilla/release-services#2248]
Our Datadog account is closing, so we should remove references to it. 

`repo:github.com/mozilla-releng/services:branch:*` currently mentions DATADOG_API_KEY, and it doesn't get mentioned anywhere in the current master branch of release-services. 

May I please get a +1 on removing only the DATADOG_API_KEY reference from all `repo:github.com/mozilla-releng/services:branch:*` secrets, and any preference on a time to do this? I'm assuming we shouldn't overlap with a deployment.

**Comment by La0** [comment]
I also use Datadog on the code-review & code-coverage projects which were previously hosted in that repo. What's the official replacement for tracking stats now ?

**Comment by srfraser** [comment]
> I also use Datadog on the code-review & code-coverage projects which were previously hosted in that repo. What's the official replacement for tracking stats now ?

A hosted InfluxDB option. bpitts is the person to talk to.

**Comment by La0** [comment]
Ok, thanks Simon for the heads up, i'll contact bpitts.

Regarding `mozilla/release-services`, I think you can safely remove the secret from all `repo:github.com/mozilla-releng/services:branch:*` secrets: it seems we removed all the projects using it.

**Comment by srfraser** [comment]
I've left references to the datadog api key in code-coverage and static-analysis-bot sections, but removed entries in 'common'

**Comment by La0** [comment]
These projects have been fully removed: there is no more any datadog api key.
