### ISSUE TITLE
Add mozilla-unified to TreeStatus

### ISSUE THREAD

**Issue by mars-f** [mozilla/release-services#2249]
The `mozilla-unified` repository is not listed on https://mozilla-releng.net/treestatus.  The repo is present on the list of repositories at https://hg.mozilla.org/.

**Comment by nthomas-mozilla** [comment]
mozilla-unified is a bit of a special case that consolidates pushes from several repos. No-one pushes directly to it so it doesn't need an entry on treestatus.
