### ISSUE TITLE
shipit_analysis: Implement a static-analysis bot that auto-reviews Firefox changesets

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#240]
When a Firefox developer requests a code review on some changeset, a TaskCluster bot should automatically run a few sanity checks on the code, and post quick feedback on the review request.

Triggers:
- `pulse` push on review repository: YES (similar to Travis builds on GitHub pull requests)
- `pulse` push on mozilla-central: MAYBE (to build a database of analysis data per mozilla-central revision, in order to (1) analyze a changeset incrementally and (2) identify which code issues are actually related to the changeset)
- `r?` flags on BMO: ? (could add support for non-mozreview patches)

Data storage:
- TaskCluster task cache: ? (not a persistent storage)
- TaskCluster artifacts: ?
- sccache: ? (does it even work with `./mach static-analysis check`?)
- heroku database: MAYBE (for the database of analysis data per mozilla-central revision)

Generate analysis:
- Implement `try: --task-set=review-analysis`: NO (looks too complex and slow for now)
- TaskCluster task with `./mach static-analysis check`: YES (currently 40min on 16cpu, should be faster)

Types of analysis (checkers):
- TODO: Find a list of checkers that are fast and give crucial feedback 

Process analysis:
- Diff analysis data between base mozilla-central revision and changeset: MAYBE (might include too much info, e.g. feedback data that didn't change from mozilla-central except it's on a different line now)
- Run analysis only on functions actually touched by the changeset, or neighbours in the call tree: MAYBE (can we even (1) find out which functions were impacted, and (2) make the analyzer only generate feedback on these particular functions?)

Publish feedback:
- Post as comment on bugzilla
- Post as code issues in review tool

**Comment by jankeromnes** [comment]
To detect pushes to the review repository, we could listen for [exchange/hgpushes/v1](https://wiki.mozilla.org/Auto-tools/Projects/Pulse/Exchanges#hg.mozilla.org) Pulse messages. However, these are not sent yet for pushes to https://reviewboard-hg.mozilla.org.

**Comment by jankeromnes** [comment]
Here is an example how we could run a static analysis task on a given commit series (after cloning mozilla-unified and having checked out the review revision):

    sudo apt-get install clang-tidy
    ./mach configure && ./mach build-backend --backend=CompileDB && ./mach build pre-export && ./mach build export
    run-clang-tidy.py -j 18 -p obj-x86_64-pc-linux-gnu/ -checks=-*,modernize-loop-convert,modernize-use-auto,modernize-use-default,modernize-raw-string-literal,modernize-use-bool-literals,modernize-use-override,modernize-use-nullptr *

We can also limit the analysis to the exact files that were actually modified by the changeset by replacing the last `*` with the result of:

    hg status --no-status --rev <base-revision>:<review-tip-revision>

**Comment by marco-c** [comment]
This is done!
