### ISSUE TITLE
Document that the Heroku apps are deployed via the container registry/runtime

### ISSUE THREAD

**Issue by edmorley** [mozilla/release-services#368]
Broken out from #366.

Apps like TreeStatus are hosted by Heroku, but yet there is no Procfile in this repo (and the Heroku app doesn't have the GitHub link feature set up with this repo), which caused confusion in #366.

It turns out that the apps are deployed via the Heroku [container registry/runtime method](https://devcenter.heroku.com/articles/container-registry-and-runtime) which overrides many of the standard Heroku features (such as buildpacks, Procfile, etc).

Heroku could do a much better job of making this clear via the web dashboard/CLI - since currently there's no indication that the app is using that deploy method. I've filed: 
https://help.heroku.com/tickets/483981

However, it would still be good to document on https://docs.mozilla-releng.net/deploying.html (or wherever appropriate) that:
* The app is deployed via the container runtime/registry feature, not the standard Heroku workflow
* That the docker image (and thus docker `CMD` that is used instead of a `Procfile`) is created using the scripts [here](https://github.com/mozilla-releng/services/blob/ce5f078d8cc686fd6df77061097aa68c4dcb7973/nix/lib/default.nix#L577)

Many thanks!

**Comment by garbas** [comment]
@edmorley tnx a ton! this is an awesome TODO list to document.
