### ISSUE TITLE
shipit_signoff docs do not show up in production

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#436]
They show up when I build the docs locally (Sphinx 1.5.5), but they don't show up on https://docs.mozilla-releng.net/family_shipit.html#src-shipit-signoff -- we end up with a completely blank section.

**Comment by cgsheeh** [comment]
The docs build properly on my local device as well. I just noticed that the shipit_signoffs folder is a symlink though, maybe we could swap where the real file and the symlink live and see if that solves the issue. I can't find any references to that file in the [logs](https://public-artifacts.taskcluster.net/IE8GyTxsSn2sZr3Coka0Sg/0/public/logs/live_backing.log) but I can find references to the files in the contributing folder (developing.rst, etc).
