### ISSUE TITLE
No papertrail logs

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#553]
The service `shipit_pulse_listener` now runs on Heroky worker dyno, but no logs are sent to Papertrail.

**Comment by La0** [comment]
Bump.

@garbas Any idea why that might happen ? Because it's an heroku worker dyno ?

**Comment by garbas** [comment]
@La0 no idea, i'm seeing this also for releng-tooltool worker.

**Comment by La0** [comment]
I solved it for `shipit-pulse-listener`, it just needs another env variable, `APP_CHANNEL`. 
It's set for Taskcluster hook, but not for Heroku envs.

**Comment by garbas** [comment]
ah right, that makes sense.  i will do the same for releng-tooltool worker

**Comment by garbas** [comment]
Thinking about it again. Should we try to parse channel from TAKCLUSTER_SECRET?

**Comment by marco-c** [comment]
@garbas the pulselistener problem is fixed, do you want to keep this open for another reason? Can you update the title if so, or close the issue otherwise?

**Comment by garbas** [comment]
@marco-c thank you for pinging me on this. i'm looking is this was done already in releng-tooltool

**Comment by garbas** [comment]
fixed
