### ISSUE TITLE
Prefix logs by the name of the hook that generated them

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#557]
This way it's easier to grep the pulse listener logs.

**Comment by garbas** [comment]
you can add multiple parameters to the log since we are using [structlog](https://pypi.python.org/pypi/structlog)

you can also use a "scoped" logger, example:

```python
import cli_common.log
logger = cli_common.log.get_logger(__name__)

def handle_hook(hook_name):
    logger_hook = logger.bind(hook=hook_name)
    # ... some code ...
    logger_hook.error('something bad happened')

```

does is make sense?

**Comment by La0** [comment]
As we don't have hooks anymore, this is done : one logging instance by project.
