### ISSUE TITLE
Make it more obvious that only docker (and git) is required ("hide" Nix a bit in docs)

### ISSUE THREAD

**Issue by armenzg** [mozilla/release-services#575]
If developing on Mac, there's no mention what docker image is recommended running to get the services going:
https://docs.mozilla-releng.net/develop/contribute.html

**Comment by garbas** [comment]
``./please run releng-docs`` pulls the correct image and runs Sphinx (and everything that is needed) in development mode. I'm just updating documentation for each project, I'm yet to finish the one for [releng-docs](https://docs.mozilla-releng.net/projects/releng-docs.html)

**Comment by armenzg** [comment]
This was a misunderstanding on my part.

I got confused with not being able to install Nix (since I'm on OSX) and I was thinking that there were instructions missing. I was thinking of "oh I need to get a docker image and put nix on it before I can get started" since Nix is mentioned as a requirement.

Feel free to close this or repurpose it.

**Comment by garbas** [comment]
I think it would make sense to make it more obvious. I'm sure others will hit the same problem. I will try to make it more obvious what is the requirement.
