### ISSUE TITLE
releng_notification_*: Domain name not configured

### ISSUE THREAD

**Issue by cgsheeh** [mozilla/release-services#579]
The domain names for the notification services are not configured. This is the reason the NagBot front end hangs with "Network Error" when any action is attempted. According to docs the endpoint should be ```https://notification-identity.mozilla-releng.net```, but the front end is attempting to connect to ```https://identity.notification.mozilla-releng.net```. Once a domain is set up these links should all be the same.

**Comment by garbas** [comment]
will be solved with https://github.com/mozilla-releng/services/pull/574
