### ISSUE TITLE
shipit_static_analysis: Incorrect publication of clang-format defects

### ISSUE THREAD

**Issue by gcp** [mozilla/release-services#697]
**MozReview URL:** https://bugzilla.mozilla.org/show_bug.cgi?id=1386404#c27

**Problem:**

1) The comments are visible by default. This spams up the actual bug work.
2) The rules seem partly contradictory: we require nsCString& foo but we also require const char *foo. This is even contradictory to our own C++ coding style guide.
3) The system matches lines that were modified. But this can be incredibly noisy (and nonsensical) if existing code was modified. Consider limiting it to ADDED code only.
4) The "incorrect coding style" message is completely generic and unhelpful. Even the "replace by" part is often useless in determining what exactly the system finds objectionable.
5) I don't think it's a good idea to warn about function argument alignment in the first place.

**Comment by La0** [comment]
Hi @gcp, thanks for your feedback on the static analysis bot.

Your commit was used as a test for a future version of the bot, the review **should not have been published**. Sorry about that, you can safely ignore it.

I appreciate your concerns about wording and the bot being too noisy, they will be reported to the team.

**Comment by jankeromnes** [comment]
Thanks again for your excellent and helpfully detailed feedback! And apologies for accidentally spamming your bug.

We are currently exploring what coding style feedback could look like with clangbot, and we haven't yet decided how to report it, or even whether there exists a useful way to report coding style problems.
