### ISSUE TITLE
Clone mozilla-central locally

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#712]
We perform a lot of queries to hgmo. If we had a local clone of mozilla-central, we would be able to perform these queries almost for free.

**Comment by marco-c** [comment]
This probably won't be feasible with Heroku.

**Comment by marco-c** [comment]
Or maybe it's going to be feasible with https://bugzilla.mozilla.org/show_bug.cgi?id=1428470.

**Comment by garbas** [comment]
yes, basically heroku cleans up the disk space once dyno is restarted[1], which is at least once a day. but maybe this would still be good enough optimization, to clone m-c. also is all of the history needed or we could use eg. last year only. that could reduce the size as well.

[1] https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Comment by marco-c** [comment]
We need to do `hg annotate`, so we probably need to have all history.

**Comment by marco-c** [comment]
@La0 this would be a huge perf improvement if we decide to serve source code. We don't even need to checkout to different revisions, we can just do something like `hg cat -r REVISION SOURCE_FILE`, which should not require locking so should be quite fast.

**Comment by La0** [comment]
We do not query HGMO from the backend anymore.
