### ISSUE TITLE
Task ID should be logged somehow on Sentry so we can map Sentry errors to task IDs

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#750]
E.g. from https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/796712/, I'd like to know which task actually failed (e.g. https://tools.taskcluster.net/groups/Hr0gsbtRSWGlulMGgm2naQ/tasks/Hr0gsbtRSWGlulMGgm2naQ/details).

**Comment by garbas** [comment]
i think we could add a custom [structlog processor](http://www.structlog.org/en/stable/api.html#module-structlog.processors) that would add taskId (and maybe other useful info) from the `sys.environ`.
