### ISSUE TITLE
shipit_static_analysis: Please rename the bot in phabricator

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#765]
As we discussed in https://github.com/mozilla-releng/services/issues/764, we should have the same name as mozreview for the bot.
Currently, it is using Bastien's account:
https://phabricator.services.mozilla.com/D389

**Comment by La0** [comment]
We need a Phabricator API token linked to another account. Can we get a `relmanbot@mozilla.com` email account ?

**Comment by sylvestre** [comment]
@markrcote is it possible? Thanks

**Comment by markrcote** [comment]
Sorry for missing this earlier. Phabricator uses BMO for authorization, so you just need to create such an account in BMO and then log into Phabricator to generate an API token. You should be able to do that all yourself unless I'm misunderstanding something.

**Comment by marco-c** [comment]
@La0 is this done?

**Comment by sylvestre** [comment]
yeah.
