### ISSUE TITLE
setup: Generate a requirements_generated.nix per environment

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#783]
We just had a bad bug on Static Analysis where the `flake8` configuration built by Nix was used by `./mach lint` thus activating our extras checks on the mozilla-central codebase.

As we used `flake8-quotes` and `flake8-coding` for our own codebase, as required in `src/shipit_static_analysis/requirements-dev.txt`, the Nix environement is shipped with this feature.

Is it possible to easily build a dev and a production environment ?

**Comment by garbas** [comment]
I'm not sure I understand the last line (question). a dev and prod environment for `shipit_static_analysis`? for mozilla-central codebase? we can also talk (now that i'm back from PTO) on irc.

**Comment by marco-c** [comment]
@garbas the requirement would be that the environment for building `shipit_static_analysis` must be different than the environment where `shipit_static_analysis` runs. In this case, we want those `flake8` plugins when building the project, but we don't want them when running the project.

**Comment by garbas** [comment]
aha I see. since we run `nix-shell` via python we need to make sure that you run at mozilla-central checkout and that you run `nix-shell` with `--pure` option. that way you are not affected by whatever environment you are in.
