### ISSUE TITLE
Assert that the files in the SF entries of the INFO files exist

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#800]
Follow-up to #629.

**Comment by marco-c** [comment]
The assertion was present in the LCOV rewriter, but now that we're going to run it on the test machine, the assertion has to go (at least until test machines have a source checkout).

**Comment by isacben** [comment]
Hello @marco-c,

I am a newcomer. I would like to help with this one. I read issue #629 and I think the code already changed a bit since that time? I guess the target script is now:

https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/codecov.py

Also, I do not know if this example report you shared before is still valid?

https://codecov.io/gh/marco-c/gecko-dev/commit/d01a76279978ad965981936db5cc321f8c6de225/build

Would you please advice?
Thanks!

**Comment by marco-c** [comment]
Hello @isacben!

> I am a newcomer. I would like to help with this one. I read issue #629 and I think the code already changed a bit since that time? I guess the target script is now:
> https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/codecov.py

Correct.

> Also, I do not know if this example report you shared before is still valid?
> https://codecov.io/gh/marco-c/gecko-dev/commit/d01a76279978ad965981936db5cc321f8c6de225/build

Yes, the format of the reports should still be the same.

Note, #629 is a dependency of this, so if you want to work on this, you should work on #629 first.

**Comment by m-agboola** [comment]
@isacben are you still working on this?

**Comment by sbeesm** [comment]
Hi @marco-c! Can I work on this one?

**Comment by marco-c** [comment]
Yes, consider an issue to be free to work on unless there is already someone working on it actively.

**Comment by sbeesm** [comment]
Are we considering some specific info files or all the info files in `release-services/src/codecoverage/bot/tests/fixtures/`?

Also, can you please suggest how to make sure that a file in SF entry exists in a repository.

**Comment by marco-c** [comment]
@sbeesm this is about the info files that we pass to grcov at runtime, not the test fixture ones.

Here is where we pass the info files:
https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/codecov.py#L140

The `self.artifactsHandler.get()` returns a list of ZIP files containing INFO files. To fix this issue, we will have to read the INFO files, and for each SF: line check that the file exists in the `self.repo_dir` directory.

**Comment by sbeesm** [comment]
Ok, thanks for the clarification. So I shall run the project locally first and try to parse the ZIP files to get the info files and implement the checks.

**Comment by marco-c** [comment]
You can also get a ZIP file full of INFO files from https://queue.taskcluster.net/v1/task/asm0mhRRR8eZADT7k1BUTg/runs/0/artifacts/public/test_info//code-coverage-grcov.zip.

**Comment by sbeesm** [comment]
Do the zip files contain multiple info files? If there is only one info file, this should work:
```
zip_f = self.artifactsHandler.get()

for z in zip_f:
    zf = zipfile.ZipFile(z, 'r').open('grcov_lcov_output.info', 'r')
    l = zf.read().decode('utf-8').splitlines()
    sf = [s[3:] for s in l if s.startswith('SF')]

    assert all(f in self.repo_dir for f in sf), 'INFO file does not exist'
```

And if we can use the variable `f` from `all`  outside of the function, where it first returns false, we can also print which file is missing in `self.repo_dir`. Any suggestions how we can do that?

**Comment by marco-c** [comment]
They currently only contain one info file, but we should be generic and assume there could be multiple info files.
There are a few problems with your snippet:
1) You are opening the zip file but never closing it. You should use `with` so this is handled for you;
2) f in self.repo_dir won't work, self.repo_dir is a path.

**Comment by sbeesm** [comment]
```
def find(name, path):     # function to search the path
    for root, dirs, files in os.walk(path):
        if name in files:
            return True
        else:
            return False


for zf in self.artifactsHandler.get():      # For each zip file in the list
    with zipfile.ZipFile(zf, 'r') as uz:    # open zip file as uz
        for i in uz.namelist():             # for each info file in uz
            with uz.open(i, 'r') as fl:     # open info file as fl   
                l = fl.read().decode('utf-8').splitlines()
                sf = [s[3:] for s in l if s.startswith('SF')]
            
            assert all(find(f, self.repo_dir) for f in sf), 'INFO file does not exist'
```

Also, the SF: files are in this format:
```
[...
'netwerk/ipc/SocketProcessChild.cpp',
 'media/libwebp/src/utils/bit_reader_inl_utils.h',
 'dom/svg/SVGFEGaussianBlurElement.h',
 'layout/xul/nsScrollbarButtonFrame.cpp',
 'media/webrtc/trunk/webrtc/modules/congestion_controller/probe_bitrate_estimator.h',
 'media/libopus/silk/decode_pitch.c'
...]
```
All the file names have some path before them. Do we need this path also or we just need the file name and search it directly in the `self.repo_dir` path?

**Comment by marco-c** [comment]
Those are the paths of the files under the self.repo_dir path. E.g. https://searchfox.org/mozilla-central/source/netwerk/ipc/SocketProcessChild.cpp (consider `https://searchfox.org/mozilla-central/source' to be the root of the repo).
You should assert that the file `netwerk/ipc/SocketProcessChild.cpp` exists under self.repo_dir, so you don't need to find it, you can just append the path to self.repo_dir.

**Comment by sbeesm** [comment]
So instead of writing a `find` function, we can do:

`assert all(os.path.exists(self.repo_dir + f) for f in sf), 'INFO file does not exist.'`

**Comment by sbeesm** [comment]
Shall I submit a PR now?

And is it important to print the name of file also which is missing?  Using `f` in error message of the assertion to print the file name doesn't work as it is out of scope. 
Any suggestions how to do it?

**Comment by marco-c** [comment]
You could collect the names in a list, and then assert that the list is empty:
```Python
missing_files = [f for f in sf if not os.path.exists(self.repo_dir + f)]
assert len(missing_files) == 0, f'{missing_files} are missing'
```

**Comment by sbeesm** [comment]
Can we do something like this:

```
missing_files = list(filter(lambda x: not os.path.exists(x), (os.path.join(self.repo_dir, s[3:]) for s in l if s.startswith('SF'))))
```

Although it is not very readable but this way we won't have to traverse the list two times for creating and finding missing files.

**Comment by marco-c** [comment]
It actually seems better if you have a list of missing files and add files to the list in the loop where you iterate over the zip entries.

**Comment by sbeesm** [comment]
So the final code can be like this:

```
for zf in self.artifactsHandler.get():
    with zipfile.ZipFile(zf, 'r') as uz:
        for i in uz.namelist():
            with uz.open(i, 'r') as fl:
                l = fl.read().decode('utf-8').splitlines()

                missing_files = list(filter(lambda x: not os.path.exists(x),
                                            (os.path.join(self.repo_dir, s[3:]) for s in l if s.startswith('SF'))))

                assert len(missing_files) == 0, f'{missing_files} are missing'
```

Shall I submit a PR now?

**Comment by marco-c** [comment]
Yes! It's much easier to discuss on code with PRs.

**Comment by sbeesm** [comment]
I've created a PR #1812 
Waiting for review!
