### ISSUE TITLE
shipit_static_analysis: Run clang-tidy, clang-format and mozlint in parallel

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#805]

**Comment by vsham20** [comment]
Hi  @marco-c , I want to work on this issue. Can you please provide some details. Thanks

**Comment by marco-c** [comment]
Hey @vsham20, to start contributing I suggest you take one of the issues marked as `skill:good-first-bug`: https://github.com/mozilla-releng/services/issues?q=is%3Aissue+is%3Aopen+label%3Askill%3Agood-first-bug.

**Comment by La0** [comment]
Done with the move to Try !
