### ISSUE TITLE
Notify when a hg commit is missing on git

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#806]
Notify both me and dhouse, so he can fix it and I can retrigger the task once it's fixed.

**Comment by m-agboola** [comment]
Hi @marco-c  Can i work on this issue?

**Comment by marco-c** [comment]
Sure! You can take inspiration from https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/notifier.py (which is sending a notification for another thing), and you can add the notification either at https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/codecov.py#L119 or in this function https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/github.py#L44.

**Comment by m-agboola** [comment]
Alright. Thanks!

**Comment by prajwalshimpi** [comment]
Hi @marco-c ,
Can I work on this as my first task if this is not solved yet? 
Thanks!

**Comment by prajwalshimpi** [comment]
Hi @marco-c ,
Thank you!

Since I am a beginner, I have the firefox built on my macOS. Do I need to setup some additional environment?

**Comment by marco-c** [comment]
@prajwalshimpi this is a different project than Firefox, unfortunately it's quite a different environment that you will have to setup. https://docs.mozilla-releng.net/develop/contribute.html#requirements

Once you setup the env, try running `./please check codecoverage/bot` (don't run `./please run codecoverage/bot` as it will take too much time).

**Comment by sangimanishrao** [comment]
Hey, I've written the code to fix the issue, but when I try to run `./please check codecoverage/bot` it says `Exception: Missing taskcluster in /etc/hosts`

**Comment by marco-c** [comment]
You'd need a Taskcluster account.
For now, please just submit the PR and our automation will take care of running `please check` for you. I'll figure out how to get you a Taskcluster account.

**Comment by sangimanishrao** [comment]
Can I send you my patch once, before I generate a PR?

**Comment by marco-c** [comment]
Creating a PR is the best way to show me your patch :)
