### ISSUE TITLE
shipit_static_analysis: Incorrect "\" for [ ]

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#810]
As you can see:
![image](https://user-images.githubusercontent.com/733326/35748267-bec69c3a-084d-11e8-9ca3-efa1b74b9fc1.png)
_\[eslint: quotes\]_ should be _[eslint: quotes]_

https://reviewboard.mozilla.org/r/217536/diff/2-4/

**Comment by La0** [comment]
Outdated
