### ISSUE TITLE
shipit_pulse_listener: Start one TC task per static analysis revision

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#814]
Right now shipit-pulse-listener will start one TC static analysis task per pulse message. But some pulse messages contain too many revisions and do not finish before the 1 hour timeout
Example on task [BCWwnpNtSUKTmVwIEknfBg](https://tools.taskcluster.net/groups/BCWwnpNtSUKTmVwIEknfBg/tasks/BCWwnpNtSUKTmVwIEknfBg/runs/0/logs/public%2Flogs%2Flive.log).

**Comment by marco-c** [comment]
Isn't it going to be more expensive?

**Comment by La0** [comment]
Indeed, it would be more time consuming. We could batch the revisions under a fixed limit (like 5 revisions max. per task...)

**Comment by marco-c** [comment]
When we have more data in datadog we can choose a good number based on the runtime

**Comment by La0** [comment]
Outdated
