### ISSUE TITLE
shipit_static_analysis: Run `mach lint` once with all paths

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#829]
We're currently running it once per modified file:
https://github.com/mozilla-releng/services/blob/2f0fefea887db0d7601fa63937272b674a34c99d/src/shipit_static_analysis/shipit_static_analysis/lint.py#L116

I think we can run it once with the list of modified files, thus saving the time needed to instantiate mach (which means starting a new Python process, importing modules, etc.) multiple times.

**Comment by marco-c** [comment]
The other option would be to run multiple `mach lint` in parallel, unless it's done automatically when you pass multiple paths to mach lint.

CC @ahal

**Comment by ahal** [comment]
Yes, |mach lint| already parallelizes paths and linters automatically. So all the linters run in parallel jobs, and if multiple paths are passed in, there will even be multiple jobs per linter.

**Comment by marco-c** [comment]
Thanks @ahal, so it sounds like the best option is the one outlined in the first comment.

**Comment by La0** [comment]
Outdated with the move to try.
