### ISSUE TITLE
shipit_static_analysis: Warning that value stored to 'rv' is never read is wrong

### ISSUE THREAD

**Issue by valenting** [mozilla/release-services#836]
**MozReview URL:** https://reviewboard.mozilla.org/r/217134/#comment285608

**Problem:** 
Code review bot opens this issue:
Warning: Value stored to 'rv' is never read [clang-tidy: clang-analyzer-deadcode.DeadStores]
But the value is actually used on the next line in MOZ_ASSERT(NS_SUCCEEDED(rv));

**Comment by marco-c** [comment]
Maybe it's compiled out because `MOZ_ASSERT` is basically nothing in a non-debug build.
Perhaps we should "--enable-debug" in the bot.

**Comment by sylvestre** [comment]
yeah, I was going to say the same! We should use --enable-debug. I am doing the same with codechecker & coverity.

**Comment by marco-c** [comment]
I see in mozilla-central we have both a opt- and a debug- static analysis job: https://dxr.mozilla.org/mozilla-central/source/browser/config/mozconfigs/linux64/opt-static-analysis-clang and https://dxr.mozilla.org/mozilla-central/source/browser/config/mozconfigs/linux64/debug-static-analysis-clang.
So perhaps the patch in question would fail on automation too?
