### ISSUE TITLE
shipit_static_analysis: wrong flake8 errors reported

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla/release-services#844]
**MozReview URL:** https://reviewboard.mozilla.org/r/220560/#review226540

**Problem:** `basestring` is a valid identifier in the python 2 world https://docs.python.org/2.7/library/functions.html#basestring. Furthermore, they are not reported by `./mach lint`

Interestingly, there were 2 other linter errors reported `./mach lint`, but none of them are displayed in the review. For reference, these were:

```
TEST-UNEXPECTED-ERROR | /home/jlorenzo/hg/firefox/taskcluster/taskgraph/transforms/beetmover.py:467:1 | expected 2 blank lines, found 1 (E302)
TEST-UNEXPECTED-ERROR | /home/jlorenzo/hg/firefox/taskcluster/taskgraph/transforms/beetmover_source.py:36:9 | local variable 'upstream_artifacts' is assigned to but never used (F841)
```

**Comment by sylvestre** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1424482#c4

**Comment by marco-c** [comment]
The `basestring` issue is https://github.com/mozilla-releng/services/issues/819.

The two missing issues should be fixed by https://github.com/mozilla-releng/services/pull/835.
