### ISSUE TITLE
Add tests for the coverage API endpoints that require Redis

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#882]
`GET /coverage/changeset/{changeset}` and `GET /coverage/changeset_summary/{changeset}` use rq backed by Redis.

These should be tested (possibly with https://pypi.python.org/pypi/pytest-redis) after https://github.com/mozilla-releng/services/pull/876 is merged.

**Comment by marco-c** [comment]
#876 has been merged, so this should now be feasible.

**Comment by akankshanayak2111** [comment]
I am working on this issue :)
