### ISSUE TITLE
Add unit tests for the functions in the coverage module

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#883]

**Comment by mutterroland** [comment]
I would like to give it a try . Can I get some guidance?

**Comment by garbas** [comment]
The docs to start contributing are at https://docs.mozilla-releng.net/develop/contribute.html. 

In short
 - Install Docker
 - Fork this repository and clone it
 - Always run `./please` command from the root of the clone of this repository

To enter the development environment for `shipit_uplift` project and run tests do:

```
$ ./please shell shipit-uplift
(nix-shell) $ pytest pytest --capture=no tests/
(nix-shell) $ exit
$
```

`./please shell <project>` will put you in the environment with all the dependencies / tool available. It is marked as `(nix-shell)` in the beginning of the console. To exit from this development environment you can type `exit` or press `CTRL-D`.

The code that needs tests to be written is https://github.com/mozilla-releng/services/blob/master/src/shipit_uplift/shipit_uplift/coverage.py. You can check existing tests (for reference) in https://github.com/mozilla-releng/services/tree/master/src/shipit_uplift/tests folder.

If you get stuck feel free to join us on `#shipit` channel and we will try to help you.

**Comment by La0** [comment]
Outdated.
