### ISSUE TITLE
add code coverage support for python projects

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#901]
quoting @marco-c  :)
```
14:29:46  marco | yep, I think we should introduce code coverage
14:29:54        | it's a shame that the code coverage project doesn't have code coverage :P 
```

**Comment by marco-c** [comment]
We are using both codecov.io and coveralls.io for Firefox code coverage. codecov.io has a nicer UI, showing the coverage info about the repo as a tree. I think this is really useful for us, since we interested in seeing coverage information both overall, by project (directory) and by file (while the coveralls.io UI is only good for overall and by file).

**Comment by garbas** [comment]
I really like flags feature of codecov - https://docs.codecov.io/docs/flags

**Comment by garbas** [comment]
it was pointed by @catlee on irc that all other releng projects use coveralls. It would be nice to use one service for code coverage. Either we (1) use coveralls in services or (2) we also migrate all of the other projects to codecov. On the end we should end up with one service.

It was also pointed out by @catlee  that coveralls is acting slow on many occasions. @escapewindow chipped in that his projects also use coveralls, but has no strong opinion if we have good reasons to switch to codecov.

@marco-c i think you have the most experience with this 2 services since you were working with them for the last year. How hard is it to switch from one to the other? I think we should first estimate how expensive switching would be before committing to something.

**Comment by marco-c** [comment]
In terms of performance, they are both bad (but for Firefox code coverage, which is a LOT of data compared to what we are going to have). codecov is maybe a little better, but don't expect miracles. The main differentiator is the UI in my opinion.

As far as switching between them, it shouldn't be hard. Codecov supports the same coverage format as Coveralls (indeed for Firefox we upload the same report to both codecov and coveralls). You would lose the coverage history though if you switch.
