### ISSUE TITLE
shipit-static-analysis: Python code triggers a bad mozlint json output 

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#905]
* [Mozreview](https://reviewboard.mozilla.org/r/225352/) from @sylvestre 
* [Datadog event](https://app.datadoghq.com/event/event?id=1497106118350060079)
* [Taskcluster Task](https://tools.taskcluster.net/groups/Nfq6GP_FTiqbqmGUY7IGCg/tasks/Nfq6GP_FTiqbqmGUY7IGCg/runs/0/logs/public%2Flogs%2Flive.log)

**Comment by marco-c** [comment]
Maybe the task should fail in a case like this?

**Comment by sylvestre** [comment]
We should also show more information to help debugging (even if this means updating mozlint)

**Comment by La0** [comment]
Added a [patch to Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1443508#c3), as there is a problem with flake8.

**Comment by marco-c** [comment]
It looks like using the flake8 from the virtualenv was made on purpose: https://hg.mozilla.org/mozilla-central/rev/365a91ab41e2.

**Comment by marco-c** [comment]
@La0 this is fixed, right?

**Comment by La0** [comment]
Fixed
