### ISSUE TITLE
Write tests for functions in the github module

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#910]
Starting from the ones which use the hg<->git mapper. The other functions maybe are not so easy/useful to test.

- [ ] `update_geckodev_repo`;
- [ ] `post_github_status`;
- [x] `get_commit`;
- [x] `get_mercurial`;
- [ ] `update_codecoveragereports_repo`.

**Comment by divyabaid16** [comment]
May I work on this issue? If yes, can you please guide me?

**Comment by marco-c** [comment]
Sure! The tests are to be written in this directory: https://github.com/mozilla-releng/services/tree/master/src/shipit_code_coverage/tests.
This is the module to test: https://github.com/mozilla-releng/services/blob/master/src/shipit_code_coverage/shipit_code_coverage/github.py.

You can look at the other tests for examples.

Start with the simplest tests (`get_commit` and `get_mercurial`, then `post_github_status`). Feel free to either make separate PR for each test you add or a single one with all the tests.

Here's how you setup the project: https://docs.mozilla-releng.net/develop/contribute.html.
I suggest you don't run the project, as it takes too much time, but directly the tests (with the `./please check shipit-code-coverage` command).

Feel free to ask if you need more details.

**Comment by SimiCode** [comment]
@marco-c 
Are there still tasks on this issue? I would be interested in contributing.

FYI These links don't work anymore:
- https://github.com/mozilla-releng/services/tree/master/src/shipit_code_coverage/tests.
- https://github.com/mozilla-releng/services/blob/master/src/shipit_code_coverage/shipit_code_coverage/github.py.

**Comment by marco-c** [comment]
The two links should now be https://github.com/mozilla/release-services/tree/master/src/codecoverage/bot/tests and https://github.com/mozilla/release-services/tree/master/src/codecoverage/bot/codecoverage_bot/github.py.

**Comment by marco-c** [comment]
Yes, there are still tests to write (the unticked ones from the first comment in this issue).

**Comment by madhavkulkarni1986** [comment]
@marco-c  get_commit and get_mercurial methods aren't available anymore in github.py.
I am referring to:  release-services/src/codecoverage/bot/code_coverage_bot/github.py
I am on the right file? Has something changed? I want to work on this, kindly help.

**Comment by marco-c** [comment]
They were renamed to `git_to_mercurial` and `mercurial_to_git` (you can look at the history to see that), but they are the only two functions you shouldn't care about since there are already tested :)

**Comment by shahidikram0701** [comment]
Hi,
I am new to Open source. Can I work on this issue?

**Comment by marco-c** [comment]
Sure, feel free to work on any issue that you see open and unassigned (an issue is assigned when there is a PR open to fix an issue).

**Comment by shahidikram0701** [comment]
I started looking at test for post_github_status functionality, and I noticed that the code(in github.py) is making a post request to GitHub through a taskcluster, which I assume is a third party library, so I was wondering how exactly to go about testing the function. Should the Task Cluster Github service be mocked? And since the function is not returning anything what exactly is to be mocked(if mocking is the right way to go about it). Since I'm a beginner to this, I would appreciate any guidance in how to approach writing the tests.

**Comment by madhavkulkarni1986** [comment]
IMO you should assert if the method is called with the right values/parameters. I am not sure if this can be mocked. Experts here can give inputs. I was working on this but setting up the dev environment is getting a bit tedious for me. I will relook after I complete the work on hand.

**Comment by marco-c** [comment]
Yes, it should be mocked, and the mock will check that the method was called with the right values/parameters.

@madhavkulkarni1986 if you have problems setting up the dev environment, you can join the #release-services channel on Mozilla's IRC and somebody can help you.

**Comment by madhavkulkarni1986** [comment]
@marco-c thank you :) I will follow-up soon

**Comment by gonemad97** [comment]
Hi! Can I get started on one of the unticked functions? Are they still open?

**Comment by marco-c** [comment]
Sure!

**Comment by La0** [comment]
Github module has been removed.
