### ISSUE TITLE
Write tests for the artifacts module

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#911]
At the moment, only a subset of the functions of the module are tested.

- [ ] `generate_path`;
- [x] `get_chunks`;
- [x] `get`;
- [x] `download`;
- [x] `download_all`.

**Comment by clarammdantas** [comment]
HI! :)
Can I take this bug?

**Comment by marco-c** [comment]
Hello @clarammdantas! Sure!
The relevant source code is at https://github.com/mozilla-releng/services/blob/master/src/shipit_code_coverage/shipit_code_coverage/artifacts.py.
The current tests are at https://github.com/mozilla-releng/services/blob/master/src/shipit_code_coverage/tests/test_artifacts.py. They are only testing `get` and `get_chunk`. We should add tests for `download` and `download_all` (in the `download` tests, `taskcluster` should be mocked; in the `download_all` tests, both `taskcluster` and `download` should be mocked).

You can follow the steps at https://docs.mozilla-releng.net/develop/contribute.html to setup your environment (I suggest Nix, https://docs.mozilla-releng.net/develop/install-nix.html#develop-install-nix).
Once the environment is set up, you can run `./please check shipit-code-coverage` to run the tests.

**Comment by garbas** [comment]
Regarding setting up the environment, there are less steps to do if you go with docker approach.
This means:
 - Install Docker
 - Clone the repository
 - From the root of the repository run `./please ...` commands

To get the development environment for `shipit-code-coverage` project you need to run
```
$ ./please shell shipit-code-coverage
```

Also it might be a bit hidden, but we currently support only OSX and Linux OSes.

**Comment by clarammdantas** [comment]
@garbas Ok. I use Ubuntu and Debian on a daily bases.

@marco-c I can run the `./please check shipit-code-coverage` without any problems, but I'm trying to print some stuff in the test_artifacts.py just to understand a little bit more how everything works and nothing is being printed on the terminal, it just say when all assertations are true and show me the problem when it's not. How can I print things the I want? 

Also, I'm having a bit of hard time trying to figure out how to mock taskcluster. I mean do I need to change taskcluster.py code to make it pass the artifacts' test as it seems that the index_base and queue_base seems not to be working at the moment?

**Comment by marco-c** [comment]
For development, I'd suggest running `./please shell shipit-code-coverage`. Then in the shell that is open, you can run `pytest --capture=no tests/`.

For mocking, I suggest using https://docs.pytest.org/en/latest/monkeypatch.html. You can replace the functions of the module just in the testing environment and make them return what you want them to return.

**Comment by marco-c** [comment]
#998 added tests for artifacts.download.

**Comment by clarammdantas** [comment]
I'm working on the test for artifacts.download_all already :)

**Comment by marco-c** [comment]
https://github.com/mozilla-releng/services/pull/1156 is adding tests for download_all.

Only `generate_path` is missing now.

**Comment by clarammdantas** [comment]
Can I do the generate_path tests? :)

**Comment by marco-c** [comment]
Sure!

**Comment by marco-c** [comment]
(I've had to add tests for download_all as I was modifying it)

**Comment by clarammdantas** [comment]
That's ok! :)
I'm sorry that I take too long anyway, I was a little busy

**Comment by strodew** [comment]
Hi,

Are there any further tests that you need writing for this? I'd be happy to help out if there is! 

Thanks!

**Comment by marco-c** [comment]
Yes, there are still no tests for `generate_path`.

**Comment by marco-c** [comment]
See https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/tests/test_artifacts.py and https://github.com/mozilla/release-services/blob/master/src/codecoverage/bot/code_coverage_bot/artifacts.py.

**Comment by strodew** [comment]
Great, I'll take a look at that today. Thanks!

**Comment by strodew** [comment]
Been trying to get docker set up today but having some problems where it's either running out of space or inodes while trying to execute ./please (check/shell) shipit_code_coverage so I've not been able to get much done yet today but I took a look at the source code and I think I have a decent idea of what to do once I sort this out.

Did you have any specific test criteria / specs for what cases need to be tested for generate_path?

**Comment by strodew** [comment]
Right, I had to spend a couple of hours tinkering with my VM's drive in GParted because it wasn't big enough to run the docker commands for testing (oops) but I've got it working now I believe so I'll get to work on the actual coding tomorrow... 

Were there any specific cases you wanted to test for the generate_path method or does it just need to verify that it can generate a path string given appropriate arguments?

**Comment by strodew** [comment]
Oh and I thought I should check, it seems that ./please check shipit_code_coverage no longer works - I looked at the help commands and presume that codecoverage/bot is the correct project for this issue but I might be mistaken - if you could clarify on that that would be great!

**Comment by marco-c** [comment]
You can just test calling the function with a couple possible options for the parameters and assert that the result is what you expect.

> ./please check shipit_code_coverage no longer works

What error are you seeing?

**Comment by garbas** [comment]
i assume you have to provide taskcluster credentials

**Comment by strodew** [comment]
![please_check_shipit_code_coverage](https://user-images.githubusercontent.com/22817802/49733401-4265a480-fc79-11e8-87a1-3c75766a711e.PNG)

This is the terminal output I get from running ./please check shipit_code_coverage - if I use one of the options listed in the error string then it works fine.

**Comment by strodew** [comment]
I'm working on the test function and I have a good idea what I want to assert but I'm not quite sure of what form the inputs for generate_path are meant to take? My best understanding is that platform and chunk are strings ('linux' and 'xpcshell-7' for instance) but artifact I'm not really sure on - is there some documentation I could look at as to what the inputs are meant to look like?

**Comment by strodew** [comment]
#1738 - submitted a pull request with my patch - hopefully it's good but let me know if anything needs to be changed :)

p.s. Sorry about the multiple test runs, I got a little confused as it's my first time submitting a pull request...
