### ISSUE TITLE
Write tests for some functions in the codecov module

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#912]
At least the following functions should be tested:

- [x] `generate_chunk_mapping`;
- [x] `generate_zero_coverage_report`;
- [ ] `generate_suite_reports`.

**Comment by vsham20** [comment]
@marco-c I want to work on this if its still available. If yes, can you please guide me a little with this. I see that you have already written tests for generate_zero_coverage_report, so I can start with other functions mentioned.

**Comment by marco-c** [comment]
Sure, any issue that is open and is not linked to a PR is available :)
I suggest you take a look at the PR which introduced the tests for `generate_zero_coverage_report` to have an idea on how to implement the other tests.
Please submit a PR for each test and not a single PR adding all tests, this way we can iterate faster.
Also, when you add tests for a function, move that function in `report_generators.py` first.

I would start with `generate_suite_report`, which should be simpler to test.

**Comment by marco-c** [comment]
Feel free to ask here or on IRC if you need any help.

The docs to start contributing are at https://docs.mozilla-releng.net/develop/contribute.html.

**Comment by vsham20** [comment]
@marco-c Thanks. I will start with generate_suite_report first.

**Comment by teh-f00l** [comment]
@marco-c @vsham20 Is this still open for a contribution?

**Comment by marco-c** [comment]
Only `generate_suite_reports` is not tested yet, I've opened https://github.com/mozilla/release-services/issues/1030 for it, but @rv404674 is working on it.
