### ISSUE TITLE
Most tasks are hanging while trying to upload to s3

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#942]
This is happening very very often now. I don't remember if we already have an issue filed about this.

**Comment by marco-c** [comment]
All current PRs are blocked on this, rerunning them multiple times didn't help.

**Comment by garbas** [comment]
I think the problem was that AWS credentials were wrong. I wonder what changed here. Anyway, i rotated the credentials for all branches and it looks like it is working now.

I'm closing this issue now, but it the error reappears we should reopen it

**Comment by marco-c** [comment]
Recent examples:
https://tools.taskcluster.net/groups/aj50jwYoQAibTJ7s8qpSrg/tasks/N0coBOhtTWeCNmr4EG_pYg/details
https://tools.taskcluster.net/groups/aso5rLOMRXCutbGqQOJIsw/tasks/ECIXjUrYRkCJ85A3lA46Nw/details

**Comment by marco-c** [comment]
I think this has been fixed.
