### ISSUE TITLE
When we have a stack of revisions, analyze only the last one?

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#944]
Here, the bot is analyzing patches one by one without applying all of them before.

For example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1438839#c23
The second patch ( _Bug 1438839 - autopep8 -i --max-line-length 99 on the tools/_ ) is being analyzed without the third (  _Bug 1438839 - Fix the remaining flake8 issues by hand_ ) which fixed most of them.

**Comment by sylvestre** [comment]
Not sure it is an enhancement, I would say bug.
I had to push using inbound to avoid closing the +50 incorrect defects.

**Comment by marco-c** [comment]
Duplicate of #655.
