### ISSUE TITLE
Separate worker type for builds and production

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#946]
This way, if for some reason the builds are blocked, we don't block the tasks running on production.

This would have avoided the problem we were seeing yesterday, where some hanging builds were causing static analysis not to run.

(This is already done for code coverage, which is using releng-svc-compute instead of releng-svc)

**Comment by marco-c** [comment]
I have created `releng-svc-prod` that is an equivalent of `releng-svc`.
I don't know if we should use three (one for builds, one for staging, one for production) or just two (one for builds and one for staging/production).

**Comment by garbas** [comment]
@marco-c :+1: for the `releng-svc-prod`. should we then also create `releng-svc-prod-compute`?

**Comment by marco-c** [comment]
We're good here for now.
