### ISSUE TITLE
shipit_static_analysis: Incorrect reports on mozilla-implicit-constructor & modernize-use-equals-default

### ISSUE THREAD

**Issue by nnethercote** [mozilla/release-services#953]
**MozReview URL:** https://reviewboard.mozilla.org/r/226034/diff/2#index_header

**Problem:** See https://bugzilla.mozilla.org/show_bug.cgi?id=1411469#c30, which explains the two problems.

**Comment by marco-c** [comment]
CC @Abpostelnicu

**Comment by marco-c** [comment]
Duplicate of #888 and #999.
