### ISSUE TITLE
Support running integration tests

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#963]
The integration tests might be implemented as a separate deployment of a project.

CC @La0 @garbas 

depends on #962

**Comment by garbas** [comment]
:+1: exactly ... it should deploy a taskcluster hook with runs periodically. we also need to define a way to report this somewhere. maybe report to sentry when things brake.

**Comment by La0** [comment]
Bump.
We really need integration tests, to avoid #1209 kind of bugs.

@garbas I'll discuss this with you during the All Hands
