### ISSUE TITLE
move project configuration from lib/please_cli/please_cli/config.py to project's default.nix

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#977]

**Comment by wittenator** [comment]
Hi @garbas, I am a first time contributor and would like to take this on. Currently I am doing a deep dive into Nix and the structure of the project. Is there anything I should keep in mind while doing that?

**Comment by garbas** [comment]
hi @wittenator,

if you look to work on something around Nix related, this ticket might be a better start -> #1363 
if you are looking for some work around with python, then this ticket might be a better start -> #1221 

You will most likely need help with either of those tickets and if you have questions join us in #release-services irc channel.

**Comment by garbas** [comment]
I'm closing this ticket since this work is tracked under #1220
