### ISSUE TITLE
move everything in lib/ folder to src/

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#978]
When developing on `releng_treestatus`, which depends on `cli_common` and `backend_common`, make sure that all projects from this repository are pulled in for development.

**Comment by Rishabh0712** [comment]
I would like to have some more info on that. Maybe I can work on it.

**Comment by garbas** [comment]
@Rishabh0712 this requires non trivial amount of changes all over the places. I think for first tickets it would be better to take some different ticket with a [label good-first-bug](https://github.com/mozilla/release-services/issues?q=is%3Aissue+is%3Aopen+label%3Askill%3Agood-first-bug)
