### ISSUE TITLE
display in which project shell you are

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#990]
`./please shell <project>` command drops you in a custom shell environment. Since we are using a tool called `nix-shell` which appends `(nix-shell)` at the beginning of our console prompt.

It would be nice to instead of `(nix-shell)` to show the name of the project you just entered, eg `(releng-frontend) ... $`

Every time you run `./please shell <project>` a snippet of shell (bash) code should be executed as part of `shellHook` phase of  `stdenv.mkDerivation` function appropriately setting the `PS1` variable replacing `(nix-shell)` with a `(<project>)`.

We need to write a new function in `./nix/lib/default.nix` which wraps `stdenv.mkDerivation` and sets `shellHook` which sets `PS1` variable correctly.  Then we need to go to all projects and use this function instead of  `stdenv.mkDerivation`.

I know Nix can feel different at first (it is a functional language), but learning the basic syntax shouldn't take much time (https://learnxinyminutes.com/docs/nix).

# Simple example of a problem

You can use base image of this project to enter the environment  with Nix already installed, by doing: `docker run --rm -ti --privileged -v $(pwd):/app mozillareleng/services:base-new-36 bash`

Having the following `default.nix` for an example package.

```nix
{ pkgs ? import <nixpkgs> {}
}:

let
  name_and_version = "example-1.0";
  x = builtins.parseDrvName name_and_version;
in pkgs.stdenv.mkDerivation {
  name = name_and_version;
  shellHook = ''
    # this is simple bash inside nix multi line string
    echo "I am in Nix shell"
    echo "Name of the project is: ${x.name}"
    echo "Version of the project is: ${x.version}"
  '';
}
```

and running `nix-shell default.nix` it should drop you into the development environment of this example project. `shellHook` is a bash string which will get executed after you enter nix shell. And here is where you need to change `PS1` variable to show `(example)` as shell prompt instead of `(nix-shell)`.

To play around with Nix language interactivly you can also use `nix repl` command.

**Comment by clarammdantas** [comment]
Can I work on this one?

**Comment by garbas** [comment]
@clarammdantas ofcourse

I will go more in details in description, but i first need my morning coffee :)

**Comment by garbas** [comment]
@clarammdantas I updated the description as much as could think of. I assume this will be your first time using Nix so please don't hesitate to ping me with questions either here on IRC.

**Comment by clarammdantas** [comment]
It will be my first time using Nix, but I have programmed before using functional paradigm, so I hope it's not going to be that hard to learn :)

**Comment by kevinluvian** [comment]
hi @garbas I just finished this in this PR: https://github.com/mozilla/release-services/pull/1676

I am not sure what the function name for wrapping stdenv.mkDerivation should be, so I named it as shellWithProjectName

summary of what I done:
- added shellWithProjectName
- added project name for shipit-frontend and staticanalysis-frontend
- added name args to mkYarnFrontend
- added PS1 variable change to mkYarnFrontend and mkPython because they use yarn2nix.mkYarnPackage and python.mkDerivation
- checked with all project listed when running ./please


at first I was thinking to have "func" parameter in my shellWithProjectName function like below
however, it seems that nix doesn't allow to pass function type as an argument
```
betterShellWithProjectName =
  args @
  { func
  , name
  , shellHook ? ""
  , ...
  }:
  let
    self = func (args // {
      shellHook = shellHook + ''
        PS1="\n\[\033[1;32m\][${name}:\w]\$\[\033[0m\] "
      '';
    });
    in self;
```
so I can call the function like:
```
betterShellWithProjectName {
  func = python.mkDerivation;
  name = "${name}-${version}";
  ...
}
```

is there some way to do it?

**Comment by garbas** [comment]
i think the following should work

```nix
{

mkProjectName = builtins.replaceStrings ["/" "_"] ["-" "-"];
mkProjectModuleName = builtins.replaceStrings ["/" "-"] ["_" "_"];

mkProject =
  { project_name
  , version
  , module_name ? mkProjectModule project_name
  , src_path ? mkProjectPath project_name
  , mkDerivation ? stdenv.mkDerivation
  } @ args:
  mkDerivation (
    (releng_pkgs.pkgs.lib.filterAttrs
      (n: v: n != "src_path"
          || n != "module_name"
          || n != "version"
      )
      args
    ) // {
      name = "mozilla-${mkProjectName}-${version}";
      shellHook = args.shellHook + ''
        PS1="\n\[\033[1;32m\][${project_name}:\w]\$\[\033[0m\] "
      '';
      passthru.module_name = module_name;
      passthru.src_path = src_path;
    });

}
```

**Comment by kevinluvian** [comment]
so in summary of our discussion,
we should change shellWithProjectName to mkProject
and only pass project_name, and calculate other variable (module_name, src_path) from project_name

I will make the necessary changes and update you again, thanks!
