### ISSUE TITLE
create json schema for secrets and enforce it when fetching

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#992]
with more and more projects (currently 17) and more and more channels  (currently 4) it is becoming harder to manage secrets, since it is easier to forget what is missing until things break in unexpected way.

It would make a lot of sense to have a json schema, which we should check right after fetching them from taskcluster secrets.

It would be also nice to have a `./please` command that we could check secrets schema compatibility before pushing to production.

**Comment by gonemad97** [comment]
Hi! Is this issue still open? If no one is assigned to it, can I help?

**Comment by noiarek** [comment]
Hi there! This issue has the label good first bug so I would like to work on this! is it still available? And if it is, can you please guide me?

**Comment by marco-c** [comment]
@noiarek we are moving a few things around in this project, so I'd suggest picking another one to contribute to (you can use https://codetribute.mozilla.org/ to find a project that might be of interest).
