### ISSUE TITLE
"versioned" secrets for production channel

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#994]
when deploying to production a lot of times changes in secrets also have to be made. usually this is possible to do in advance but not always. then it becomes hard to remember what you need to dhqng3 in production secrets.

this convention would give us 2 things:
- we can prepare, in advance, the secrets needed for next release, alongside currently active secrets
- if something goes terribly wrong we can rollback also the secrets part

instead of only fetching `repo:github.com/mozilla-releng/services:branch:production` we would also add a version to that secret, so instead we would be fetching `repo:github.com/mozilla-releng/services:branch:production-v34` being the current version of services is 34.

**Comment by garbas** [comment]
@La0 @marco-c @rail would you have any thoughts on this?

**Comment by rail** [comment]
I like the idea! Sounds Nix-ish :) This way we keep the secrets up to date by generating a template to populate.
My only concern is how to garbage collect the unused secrets from TC.
